
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models"
import { type PrismaClient } from "./class"

export type * from '../models'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.3.0
 * Query Engine version: 9d6ad21cbbceab97458517b147a6a09ff43aa735
 */
export const prismaVersion: PrismaVersion = {
  client: "7.3.0",
  engine: "9d6ad21cbbceab97458517b147a6a09ff43aa735"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  User: 'User',
  TrainingItem: 'TrainingItem',
  Sentence: 'Sentence',
  UserNote: 'UserNote',
  VideoTrainingItem: 'VideoTrainingItem',
  VideoCaption: 'VideoCaption',
  VideoCharacter: 'VideoCharacter',
  VideoPhraseNote: 'VideoPhraseNote',
  VideoCaptionNote: 'VideoCaptionNote',
  LearningDailyStat: 'LearningDailyStat'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "user" | "trainingItem" | "sentence" | "userNote" | "videoTrainingItem" | "videoCaption" | "videoCharacter" | "videoPhraseNote" | "videoCaptionNote" | "learningDailyStat"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    User: {
      payload: Prisma.$UserPayload<ExtArgs>
      fields: Prisma.UserFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findFirst: {
          args: Prisma.UserFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findMany: {
          args: Prisma.UserFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        create: {
          args: Prisma.UserCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        createMany: {
          args: Prisma.UserCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        delete: {
          args: Prisma.UserDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        update: {
          args: Prisma.UserUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        deleteMany: {
          args: Prisma.UserDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        upsert: {
          args: Prisma.UserUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        aggregate: {
          args: Prisma.UserAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUser>
        }
        groupBy: {
          args: Prisma.UserGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserCountAggregateOutputType> | number
        }
      }
    }
    TrainingItem: {
      payload: Prisma.$TrainingItemPayload<ExtArgs>
      fields: Prisma.TrainingItemFieldRefs
      operations: {
        findUnique: {
          args: Prisma.TrainingItemFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TrainingItemPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.TrainingItemFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TrainingItemPayload>
        }
        findFirst: {
          args: Prisma.TrainingItemFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TrainingItemPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.TrainingItemFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TrainingItemPayload>
        }
        findMany: {
          args: Prisma.TrainingItemFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TrainingItemPayload>[]
        }
        create: {
          args: Prisma.TrainingItemCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TrainingItemPayload>
        }
        createMany: {
          args: Prisma.TrainingItemCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.TrainingItemCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TrainingItemPayload>[]
        }
        delete: {
          args: Prisma.TrainingItemDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TrainingItemPayload>
        }
        update: {
          args: Prisma.TrainingItemUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TrainingItemPayload>
        }
        deleteMany: {
          args: Prisma.TrainingItemDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.TrainingItemUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.TrainingItemUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TrainingItemPayload>[]
        }
        upsert: {
          args: Prisma.TrainingItemUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TrainingItemPayload>
        }
        aggregate: {
          args: Prisma.TrainingItemAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateTrainingItem>
        }
        groupBy: {
          args: Prisma.TrainingItemGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TrainingItemGroupByOutputType>[]
        }
        count: {
          args: Prisma.TrainingItemCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TrainingItemCountAggregateOutputType> | number
        }
      }
    }
    Sentence: {
      payload: Prisma.$SentencePayload<ExtArgs>
      fields: Prisma.SentenceFieldRefs
      operations: {
        findUnique: {
          args: Prisma.SentenceFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SentencePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.SentenceFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SentencePayload>
        }
        findFirst: {
          args: Prisma.SentenceFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SentencePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.SentenceFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SentencePayload>
        }
        findMany: {
          args: Prisma.SentenceFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SentencePayload>[]
        }
        create: {
          args: Prisma.SentenceCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SentencePayload>
        }
        createMany: {
          args: Prisma.SentenceCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.SentenceCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SentencePayload>[]
        }
        delete: {
          args: Prisma.SentenceDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SentencePayload>
        }
        update: {
          args: Prisma.SentenceUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SentencePayload>
        }
        deleteMany: {
          args: Prisma.SentenceDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.SentenceUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.SentenceUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SentencePayload>[]
        }
        upsert: {
          args: Prisma.SentenceUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SentencePayload>
        }
        aggregate: {
          args: Prisma.SentenceAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateSentence>
        }
        groupBy: {
          args: Prisma.SentenceGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SentenceGroupByOutputType>[]
        }
        count: {
          args: Prisma.SentenceCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SentenceCountAggregateOutputType> | number
        }
      }
    }
    UserNote: {
      payload: Prisma.$UserNotePayload<ExtArgs>
      fields: Prisma.UserNoteFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserNoteFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserNotePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserNoteFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserNotePayload>
        }
        findFirst: {
          args: Prisma.UserNoteFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserNotePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserNoteFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserNotePayload>
        }
        findMany: {
          args: Prisma.UserNoteFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserNotePayload>[]
        }
        create: {
          args: Prisma.UserNoteCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserNotePayload>
        }
        createMany: {
          args: Prisma.UserNoteCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserNoteCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserNotePayload>[]
        }
        delete: {
          args: Prisma.UserNoteDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserNotePayload>
        }
        update: {
          args: Prisma.UserNoteUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserNotePayload>
        }
        deleteMany: {
          args: Prisma.UserNoteDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserNoteUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserNoteUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserNotePayload>[]
        }
        upsert: {
          args: Prisma.UserNoteUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserNotePayload>
        }
        aggregate: {
          args: Prisma.UserNoteAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUserNote>
        }
        groupBy: {
          args: Prisma.UserNoteGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserNoteGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserNoteCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserNoteCountAggregateOutputType> | number
        }
      }
    }
    VideoTrainingItem: {
      payload: Prisma.$VideoTrainingItemPayload<ExtArgs>
      fields: Prisma.VideoTrainingItemFieldRefs
      operations: {
        findUnique: {
          args: Prisma.VideoTrainingItemFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoTrainingItemPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.VideoTrainingItemFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoTrainingItemPayload>
        }
        findFirst: {
          args: Prisma.VideoTrainingItemFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoTrainingItemPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.VideoTrainingItemFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoTrainingItemPayload>
        }
        findMany: {
          args: Prisma.VideoTrainingItemFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoTrainingItemPayload>[]
        }
        create: {
          args: Prisma.VideoTrainingItemCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoTrainingItemPayload>
        }
        createMany: {
          args: Prisma.VideoTrainingItemCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.VideoTrainingItemCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoTrainingItemPayload>[]
        }
        delete: {
          args: Prisma.VideoTrainingItemDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoTrainingItemPayload>
        }
        update: {
          args: Prisma.VideoTrainingItemUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoTrainingItemPayload>
        }
        deleteMany: {
          args: Prisma.VideoTrainingItemDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.VideoTrainingItemUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.VideoTrainingItemUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoTrainingItemPayload>[]
        }
        upsert: {
          args: Prisma.VideoTrainingItemUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoTrainingItemPayload>
        }
        aggregate: {
          args: Prisma.VideoTrainingItemAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateVideoTrainingItem>
        }
        groupBy: {
          args: Prisma.VideoTrainingItemGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.VideoTrainingItemGroupByOutputType>[]
        }
        count: {
          args: Prisma.VideoTrainingItemCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.VideoTrainingItemCountAggregateOutputType> | number
        }
      }
    }
    VideoCaption: {
      payload: Prisma.$VideoCaptionPayload<ExtArgs>
      fields: Prisma.VideoCaptionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.VideoCaptionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCaptionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.VideoCaptionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCaptionPayload>
        }
        findFirst: {
          args: Prisma.VideoCaptionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCaptionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.VideoCaptionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCaptionPayload>
        }
        findMany: {
          args: Prisma.VideoCaptionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCaptionPayload>[]
        }
        create: {
          args: Prisma.VideoCaptionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCaptionPayload>
        }
        createMany: {
          args: Prisma.VideoCaptionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.VideoCaptionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCaptionPayload>[]
        }
        delete: {
          args: Prisma.VideoCaptionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCaptionPayload>
        }
        update: {
          args: Prisma.VideoCaptionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCaptionPayload>
        }
        deleteMany: {
          args: Prisma.VideoCaptionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.VideoCaptionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.VideoCaptionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCaptionPayload>[]
        }
        upsert: {
          args: Prisma.VideoCaptionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCaptionPayload>
        }
        aggregate: {
          args: Prisma.VideoCaptionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateVideoCaption>
        }
        groupBy: {
          args: Prisma.VideoCaptionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.VideoCaptionGroupByOutputType>[]
        }
        count: {
          args: Prisma.VideoCaptionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.VideoCaptionCountAggregateOutputType> | number
        }
      }
    }
    VideoCharacter: {
      payload: Prisma.$VideoCharacterPayload<ExtArgs>
      fields: Prisma.VideoCharacterFieldRefs
      operations: {
        findUnique: {
          args: Prisma.VideoCharacterFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCharacterPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.VideoCharacterFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCharacterPayload>
        }
        findFirst: {
          args: Prisma.VideoCharacterFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCharacterPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.VideoCharacterFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCharacterPayload>
        }
        findMany: {
          args: Prisma.VideoCharacterFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCharacterPayload>[]
        }
        create: {
          args: Prisma.VideoCharacterCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCharacterPayload>
        }
        createMany: {
          args: Prisma.VideoCharacterCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.VideoCharacterCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCharacterPayload>[]
        }
        delete: {
          args: Prisma.VideoCharacterDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCharacterPayload>
        }
        update: {
          args: Prisma.VideoCharacterUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCharacterPayload>
        }
        deleteMany: {
          args: Prisma.VideoCharacterDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.VideoCharacterUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.VideoCharacterUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCharacterPayload>[]
        }
        upsert: {
          args: Prisma.VideoCharacterUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCharacterPayload>
        }
        aggregate: {
          args: Prisma.VideoCharacterAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateVideoCharacter>
        }
        groupBy: {
          args: Prisma.VideoCharacterGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.VideoCharacterGroupByOutputType>[]
        }
        count: {
          args: Prisma.VideoCharacterCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.VideoCharacterCountAggregateOutputType> | number
        }
      }
    }
    VideoPhraseNote: {
      payload: Prisma.$VideoPhraseNotePayload<ExtArgs>
      fields: Prisma.VideoPhraseNoteFieldRefs
      operations: {
        findUnique: {
          args: Prisma.VideoPhraseNoteFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoPhraseNotePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.VideoPhraseNoteFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoPhraseNotePayload>
        }
        findFirst: {
          args: Prisma.VideoPhraseNoteFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoPhraseNotePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.VideoPhraseNoteFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoPhraseNotePayload>
        }
        findMany: {
          args: Prisma.VideoPhraseNoteFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoPhraseNotePayload>[]
        }
        create: {
          args: Prisma.VideoPhraseNoteCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoPhraseNotePayload>
        }
        createMany: {
          args: Prisma.VideoPhraseNoteCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.VideoPhraseNoteCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoPhraseNotePayload>[]
        }
        delete: {
          args: Prisma.VideoPhraseNoteDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoPhraseNotePayload>
        }
        update: {
          args: Prisma.VideoPhraseNoteUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoPhraseNotePayload>
        }
        deleteMany: {
          args: Prisma.VideoPhraseNoteDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.VideoPhraseNoteUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.VideoPhraseNoteUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoPhraseNotePayload>[]
        }
        upsert: {
          args: Prisma.VideoPhraseNoteUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoPhraseNotePayload>
        }
        aggregate: {
          args: Prisma.VideoPhraseNoteAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateVideoPhraseNote>
        }
        groupBy: {
          args: Prisma.VideoPhraseNoteGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.VideoPhraseNoteGroupByOutputType>[]
        }
        count: {
          args: Prisma.VideoPhraseNoteCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.VideoPhraseNoteCountAggregateOutputType> | number
        }
      }
    }
    VideoCaptionNote: {
      payload: Prisma.$VideoCaptionNotePayload<ExtArgs>
      fields: Prisma.VideoCaptionNoteFieldRefs
      operations: {
        findUnique: {
          args: Prisma.VideoCaptionNoteFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCaptionNotePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.VideoCaptionNoteFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCaptionNotePayload>
        }
        findFirst: {
          args: Prisma.VideoCaptionNoteFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCaptionNotePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.VideoCaptionNoteFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCaptionNotePayload>
        }
        findMany: {
          args: Prisma.VideoCaptionNoteFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCaptionNotePayload>[]
        }
        create: {
          args: Prisma.VideoCaptionNoteCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCaptionNotePayload>
        }
        createMany: {
          args: Prisma.VideoCaptionNoteCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.VideoCaptionNoteCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCaptionNotePayload>[]
        }
        delete: {
          args: Prisma.VideoCaptionNoteDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCaptionNotePayload>
        }
        update: {
          args: Prisma.VideoCaptionNoteUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCaptionNotePayload>
        }
        deleteMany: {
          args: Prisma.VideoCaptionNoteDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.VideoCaptionNoteUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.VideoCaptionNoteUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCaptionNotePayload>[]
        }
        upsert: {
          args: Prisma.VideoCaptionNoteUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoCaptionNotePayload>
        }
        aggregate: {
          args: Prisma.VideoCaptionNoteAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateVideoCaptionNote>
        }
        groupBy: {
          args: Prisma.VideoCaptionNoteGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.VideoCaptionNoteGroupByOutputType>[]
        }
        count: {
          args: Prisma.VideoCaptionNoteCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.VideoCaptionNoteCountAggregateOutputType> | number
        }
      }
    }
    LearningDailyStat: {
      payload: Prisma.$LearningDailyStatPayload<ExtArgs>
      fields: Prisma.LearningDailyStatFieldRefs
      operations: {
        findUnique: {
          args: Prisma.LearningDailyStatFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LearningDailyStatPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.LearningDailyStatFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LearningDailyStatPayload>
        }
        findFirst: {
          args: Prisma.LearningDailyStatFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LearningDailyStatPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.LearningDailyStatFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LearningDailyStatPayload>
        }
        findMany: {
          args: Prisma.LearningDailyStatFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LearningDailyStatPayload>[]
        }
        create: {
          args: Prisma.LearningDailyStatCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LearningDailyStatPayload>
        }
        createMany: {
          args: Prisma.LearningDailyStatCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.LearningDailyStatCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LearningDailyStatPayload>[]
        }
        delete: {
          args: Prisma.LearningDailyStatDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LearningDailyStatPayload>
        }
        update: {
          args: Prisma.LearningDailyStatUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LearningDailyStatPayload>
        }
        deleteMany: {
          args: Prisma.LearningDailyStatDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.LearningDailyStatUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.LearningDailyStatUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LearningDailyStatPayload>[]
        }
        upsert: {
          args: Prisma.LearningDailyStatUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LearningDailyStatPayload>
        }
        aggregate: {
          args: Prisma.LearningDailyStatAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateLearningDailyStat>
        }
        groupBy: {
          args: Prisma.LearningDailyStatGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.LearningDailyStatGroupByOutputType>[]
        }
        count: {
          args: Prisma.LearningDailyStatCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.LearningDailyStatCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  avatarUrl: 'avatarUrl',
  passwordHash: 'passwordHash',
  role: 'role',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const TrainingItemScalarFieldEnum = {
  id: 'id',
  title: 'title',
  audioUrl: 'audioUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TrainingItemScalarFieldEnum = (typeof TrainingItemScalarFieldEnum)[keyof typeof TrainingItemScalarFieldEnum]


export const SentenceScalarFieldEnum = {
  id: 'id',
  trainingItemId: 'trainingItemId',
  text: 'text',
  translation: 'translation',
  startTime: 'startTime',
  endTime: 'endTime',
  order: 'order'
} as const

export type SentenceScalarFieldEnum = (typeof SentenceScalarFieldEnum)[keyof typeof SentenceScalarFieldEnum]


export const UserNoteScalarFieldEnum = {
  id: 'id',
  sentenceId: 'sentenceId',
  words: 'words',
  notes: 'notes',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserNoteScalarFieldEnum = (typeof UserNoteScalarFieldEnum)[keyof typeof UserNoteScalarFieldEnum]


export const VideoTrainingItemScalarFieldEnum = {
  id: 'id',
  title: 'title',
  sourceTitle: 'sourceTitle',
  plotSummary: 'plotSummary',
  tag: 'tag',
  mediaType: 'mediaType',
  mediaUrl: 'mediaUrl',
  coverUrl: 'coverUrl',
  coverPositionX: 'coverPositionX',
  coverPositionY: 'coverPositionY',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type VideoTrainingItemScalarFieldEnum = (typeof VideoTrainingItemScalarFieldEnum)[keyof typeof VideoTrainingItemScalarFieldEnum]


export const VideoCaptionScalarFieldEnum = {
  id: 'id',
  videoTrainingItemId: 'videoTrainingItemId',
  startTime: 'startTime',
  endTime: 'endTime',
  enText: 'enText',
  zhText: 'zhText',
  speaker: 'speaker',
  isKeySentence: 'isKeySentence',
  order: 'order'
} as const

export type VideoCaptionScalarFieldEnum = (typeof VideoCaptionScalarFieldEnum)[keyof typeof VideoCaptionScalarFieldEnum]


export const VideoCharacterScalarFieldEnum = {
  id: 'id',
  videoTrainingItemId: 'videoTrainingItemId',
  name: 'name',
  avatarUrl: 'avatarUrl',
  order: 'order'
} as const

export type VideoCharacterScalarFieldEnum = (typeof VideoCharacterScalarFieldEnum)[keyof typeof VideoCharacterScalarFieldEnum]


export const VideoPhraseNoteScalarFieldEnum = {
  id: 'id',
  videoTrainingItemId: 'videoTrainingItemId',
  captionId: 'captionId',
  phrase: 'phrase',
  note: 'note',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type VideoPhraseNoteScalarFieldEnum = (typeof VideoPhraseNoteScalarFieldEnum)[keyof typeof VideoPhraseNoteScalarFieldEnum]


export const VideoCaptionNoteScalarFieldEnum = {
  id: 'id',
  videoCaptionId: 'videoCaptionId',
  words: 'words',
  notes: 'notes',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type VideoCaptionNoteScalarFieldEnum = (typeof VideoCaptionNoteScalarFieldEnum)[keyof typeof VideoCaptionNoteScalarFieldEnum]


export const LearningDailyStatScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  dateKey: 'dateKey',
  studySeconds: 'studySeconds',
  audioSeconds: 'audioSeconds',
  dictationSeconds: 'dictationSeconds',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type LearningDailyStatScalarFieldEnum = (typeof LearningDailyStatScalarFieldEnum)[keyof typeof LearningDailyStatScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
}
export type GlobalOmitConfig = {
  user?: Prisma.UserOmit
  trainingItem?: Prisma.TrainingItemOmit
  sentence?: Prisma.SentenceOmit
  userNote?: Prisma.UserNoteOmit
  videoTrainingItem?: Prisma.VideoTrainingItemOmit
  videoCaption?: Prisma.VideoCaptionOmit
  videoCharacter?: Prisma.VideoCharacterOmit
  videoPhraseNote?: Prisma.VideoPhraseNoteOmit
  videoCaptionNote?: Prisma.VideoCaptionNoteOmit
  learningDailyStat?: Prisma.LearningDailyStatOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

