
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  TrainingItem: 'TrainingItem',
  Sentence: 'Sentence',
  UserNote: 'UserNote',
  VideoTrainingItem: 'VideoTrainingItem',
  VideoCaption: 'VideoCaption',
  VideoCharacter: 'VideoCharacter',
  VideoPhraseNote: 'VideoPhraseNote',
  VideoCaptionNote: 'VideoCaptionNote',
  LearningDailyStat: 'LearningDailyStat'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  avatarUrl: 'avatarUrl',
  passwordHash: 'passwordHash',
  role: 'role',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const TrainingItemScalarFieldEnum = {
  id: 'id',
  title: 'title',
  audioUrl: 'audioUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TrainingItemScalarFieldEnum = (typeof TrainingItemScalarFieldEnum)[keyof typeof TrainingItemScalarFieldEnum]


export const SentenceScalarFieldEnum = {
  id: 'id',
  trainingItemId: 'trainingItemId',
  text: 'text',
  translation: 'translation',
  startTime: 'startTime',
  endTime: 'endTime',
  order: 'order'
} as const

export type SentenceScalarFieldEnum = (typeof SentenceScalarFieldEnum)[keyof typeof SentenceScalarFieldEnum]


export const UserNoteScalarFieldEnum = {
  id: 'id',
  sentenceId: 'sentenceId',
  words: 'words',
  notes: 'notes',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserNoteScalarFieldEnum = (typeof UserNoteScalarFieldEnum)[keyof typeof UserNoteScalarFieldEnum]


export const VideoTrainingItemScalarFieldEnum = {
  id: 'id',
  title: 'title',
  sourceTitle: 'sourceTitle',
  plotSummary: 'plotSummary',
  tag: 'tag',
  mediaType: 'mediaType',
  mediaUrl: 'mediaUrl',
  coverUrl: 'coverUrl',
  coverPositionX: 'coverPositionX',
  coverPositionY: 'coverPositionY',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type VideoTrainingItemScalarFieldEnum = (typeof VideoTrainingItemScalarFieldEnum)[keyof typeof VideoTrainingItemScalarFieldEnum]


export const VideoCaptionScalarFieldEnum = {
  id: 'id',
  videoTrainingItemId: 'videoTrainingItemId',
  startTime: 'startTime',
  endTime: 'endTime',
  enText: 'enText',
  zhText: 'zhText',
  speaker: 'speaker',
  isKeySentence: 'isKeySentence',
  order: 'order'
} as const

export type VideoCaptionScalarFieldEnum = (typeof VideoCaptionScalarFieldEnum)[keyof typeof VideoCaptionScalarFieldEnum]


export const VideoCharacterScalarFieldEnum = {
  id: 'id',
  videoTrainingItemId: 'videoTrainingItemId',
  name: 'name',
  avatarUrl: 'avatarUrl',
  order: 'order'
} as const

export type VideoCharacterScalarFieldEnum = (typeof VideoCharacterScalarFieldEnum)[keyof typeof VideoCharacterScalarFieldEnum]


export const VideoPhraseNoteScalarFieldEnum = {
  id: 'id',
  videoTrainingItemId: 'videoTrainingItemId',
  captionId: 'captionId',
  phrase: 'phrase',
  note: 'note',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type VideoPhraseNoteScalarFieldEnum = (typeof VideoPhraseNoteScalarFieldEnum)[keyof typeof VideoPhraseNoteScalarFieldEnum]


export const VideoCaptionNoteScalarFieldEnum = {
  id: 'id',
  videoCaptionId: 'videoCaptionId',
  words: 'words',
  notes: 'notes',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type VideoCaptionNoteScalarFieldEnum = (typeof VideoCaptionNoteScalarFieldEnum)[keyof typeof VideoCaptionNoteScalarFieldEnum]


export const LearningDailyStatScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  dateKey: 'dateKey',
  studySeconds: 'studySeconds',
  audioSeconds: 'audioSeconds',
  dictationSeconds: 'dictationSeconds',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type LearningDailyStatScalarFieldEnum = (typeof LearningDailyStatScalarFieldEnum)[keyof typeof LearningDailyStatScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

