
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser.
 * Use it to get access to models, enums, and input types.
 *
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model TrainingItem
 *
 */
export type TrainingItem = Prisma.TrainingItemModel
/**
 * Model Sentence
 *
 */
export type Sentence = Prisma.SentenceModel
/**
 * Model UserNote
 *
 */
export type UserNote = Prisma.UserNoteModel
/**
 * Model VideoTrainingItem
 *
 */
export type VideoTrainingItem = Prisma.VideoTrainingItemModel
/**
 * Model VideoCaption
 *
 */
export type VideoCaption = Prisma.VideoCaptionModel
/**
 * Model VideoCharacter
 *
 */
export type VideoCharacter = Prisma.VideoCharacterModel
/**
 * Model VideoPhraseNote
 *
 */
export type VideoPhraseNote = Prisma.VideoPhraseNoteModel
/**
 * Model LearningDailyStat
 *
 */
export type LearningDailyStat = Prisma.LearningDailyStatModel
