
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DialogueTransition` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model DialogueTransition
 * 
 */
export type DialogueTransitionModel = runtime.Types.Result.DefaultSelection<Prisma.$DialogueTransitionPayload>

export type AggregateDialogueTransition = {
  _count: DialogueTransitionCountAggregateOutputType | null
  _avg: DialogueTransitionAvgAggregateOutputType | null
  _sum: DialogueTransitionSumAggregateOutputType | null
  _min: DialogueTransitionMinAggregateOutputType | null
  _max: DialogueTransitionMaxAggregateOutputType | null
}

export type DialogueTransitionAvgAggregateOutputType = {
  priority: number | null
}

export type DialogueTransitionSumAggregateOutputType = {
  priority: number | null
}

export type DialogueTransitionMinAggregateOutputType = {
  id: string | null
  scenarioId: string | null
  fromStageId: string | null
  outcomeKey: string | null
  label: string | null
  conditionJson: string | null
  priority: number | null
  isFallback: boolean | null
  toStageId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type DialogueTransitionMaxAggregateOutputType = {
  id: string | null
  scenarioId: string | null
  fromStageId: string | null
  outcomeKey: string | null
  label: string | null
  conditionJson: string | null
  priority: number | null
  isFallback: boolean | null
  toStageId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type DialogueTransitionCountAggregateOutputType = {
  id: number
  scenarioId: number
  fromStageId: number
  outcomeKey: number
  label: number
  conditionJson: number
  priority: number
  isFallback: number
  toStageId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type DialogueTransitionAvgAggregateInputType = {
  priority?: true
}

export type DialogueTransitionSumAggregateInputType = {
  priority?: true
}

export type DialogueTransitionMinAggregateInputType = {
  id?: true
  scenarioId?: true
  fromStageId?: true
  outcomeKey?: true
  label?: true
  conditionJson?: true
  priority?: true
  isFallback?: true
  toStageId?: true
  createdAt?: true
  updatedAt?: true
}

export type DialogueTransitionMaxAggregateInputType = {
  id?: true
  scenarioId?: true
  fromStageId?: true
  outcomeKey?: true
  label?: true
  conditionJson?: true
  priority?: true
  isFallback?: true
  toStageId?: true
  createdAt?: true
  updatedAt?: true
}

export type DialogueTransitionCountAggregateInputType = {
  id?: true
  scenarioId?: true
  fromStageId?: true
  outcomeKey?: true
  label?: true
  conditionJson?: true
  priority?: true
  isFallback?: true
  toStageId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type DialogueTransitionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DialogueTransition to aggregate.
   */
  where?: Prisma.DialogueTransitionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DialogueTransitions to fetch.
   */
  orderBy?: Prisma.DialogueTransitionOrderByWithRelationInput | Prisma.DialogueTransitionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DialogueTransitionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DialogueTransitions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DialogueTransitions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DialogueTransitions
  **/
  _count?: true | DialogueTransitionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DialogueTransitionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DialogueTransitionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DialogueTransitionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DialogueTransitionMaxAggregateInputType
}

export type GetDialogueTransitionAggregateType<T extends DialogueTransitionAggregateArgs> = {
      [P in keyof T & keyof AggregateDialogueTransition]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDialogueTransition[P]>
    : Prisma.GetScalarType<T[P], AggregateDialogueTransition[P]>
}




export type DialogueTransitionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DialogueTransitionWhereInput
  orderBy?: Prisma.DialogueTransitionOrderByWithAggregationInput | Prisma.DialogueTransitionOrderByWithAggregationInput[]
  by: Prisma.DialogueTransitionScalarFieldEnum[] | Prisma.DialogueTransitionScalarFieldEnum
  having?: Prisma.DialogueTransitionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DialogueTransitionCountAggregateInputType | true
  _avg?: DialogueTransitionAvgAggregateInputType
  _sum?: DialogueTransitionSumAggregateInputType
  _min?: DialogueTransitionMinAggregateInputType
  _max?: DialogueTransitionMaxAggregateInputType
}

export type DialogueTransitionGroupByOutputType = {
  id: string
  scenarioId: string
  fromStageId: string
  outcomeKey: string
  label: string
  conditionJson: string
  priority: number
  isFallback: boolean
  toStageId: string | null
  createdAt: Date
  updatedAt: Date
  _count: DialogueTransitionCountAggregateOutputType | null
  _avg: DialogueTransitionAvgAggregateOutputType | null
  _sum: DialogueTransitionSumAggregateOutputType | null
  _min: DialogueTransitionMinAggregateOutputType | null
  _max: DialogueTransitionMaxAggregateOutputType | null
}

type GetDialogueTransitionGroupByPayload<T extends DialogueTransitionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DialogueTransitionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DialogueTransitionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DialogueTransitionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DialogueTransitionGroupByOutputType[P]>
      }
    >
  >



export type DialogueTransitionWhereInput = {
  AND?: Prisma.DialogueTransitionWhereInput | Prisma.DialogueTransitionWhereInput[]
  OR?: Prisma.DialogueTransitionWhereInput[]
  NOT?: Prisma.DialogueTransitionWhereInput | Prisma.DialogueTransitionWhereInput[]
  id?: Prisma.StringFilter<"DialogueTransition"> | string
  scenarioId?: Prisma.StringFilter<"DialogueTransition"> | string
  fromStageId?: Prisma.StringFilter<"DialogueTransition"> | string
  outcomeKey?: Prisma.StringFilter<"DialogueTransition"> | string
  label?: Prisma.StringFilter<"DialogueTransition"> | string
  conditionJson?: Prisma.StringFilter<"DialogueTransition"> | string
  priority?: Prisma.IntFilter<"DialogueTransition"> | number
  isFallback?: Prisma.BoolFilter<"DialogueTransition"> | boolean
  toStageId?: Prisma.StringNullableFilter<"DialogueTransition"> | string | null
  createdAt?: Prisma.DateTimeFilter<"DialogueTransition"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DialogueTransition"> | Date | string
  scenario?: Prisma.XOR<Prisma.DialogueScenarioScalarRelationFilter, Prisma.DialogueScenarioWhereInput>
  fromStage?: Prisma.XOR<Prisma.DialogueStageScalarRelationFilter, Prisma.DialogueStageWhereInput>
  toStage?: Prisma.XOR<Prisma.DialogueStageNullableScalarRelationFilter, Prisma.DialogueStageWhereInput> | null
}

export type DialogueTransitionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  scenarioId?: Prisma.SortOrder
  fromStageId?: Prisma.SortOrder
  outcomeKey?: Prisma.SortOrder
  label?: Prisma.SortOrder
  conditionJson?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  isFallback?: Prisma.SortOrder
  toStageId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  scenario?: Prisma.DialogueScenarioOrderByWithRelationInput
  fromStage?: Prisma.DialogueStageOrderByWithRelationInput
  toStage?: Prisma.DialogueStageOrderByWithRelationInput
}

export type DialogueTransitionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.DialogueTransitionWhereInput | Prisma.DialogueTransitionWhereInput[]
  OR?: Prisma.DialogueTransitionWhereInput[]
  NOT?: Prisma.DialogueTransitionWhereInput | Prisma.DialogueTransitionWhereInput[]
  scenarioId?: Prisma.StringFilter<"DialogueTransition"> | string
  fromStageId?: Prisma.StringFilter<"DialogueTransition"> | string
  outcomeKey?: Prisma.StringFilter<"DialogueTransition"> | string
  label?: Prisma.StringFilter<"DialogueTransition"> | string
  conditionJson?: Prisma.StringFilter<"DialogueTransition"> | string
  priority?: Prisma.IntFilter<"DialogueTransition"> | number
  isFallback?: Prisma.BoolFilter<"DialogueTransition"> | boolean
  toStageId?: Prisma.StringNullableFilter<"DialogueTransition"> | string | null
  createdAt?: Prisma.DateTimeFilter<"DialogueTransition"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DialogueTransition"> | Date | string
  scenario?: Prisma.XOR<Prisma.DialogueScenarioScalarRelationFilter, Prisma.DialogueScenarioWhereInput>
  fromStage?: Prisma.XOR<Prisma.DialogueStageScalarRelationFilter, Prisma.DialogueStageWhereInput>
  toStage?: Prisma.XOR<Prisma.DialogueStageNullableScalarRelationFilter, Prisma.DialogueStageWhereInput> | null
}, "id">

export type DialogueTransitionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  scenarioId?: Prisma.SortOrder
  fromStageId?: Prisma.SortOrder
  outcomeKey?: Prisma.SortOrder
  label?: Prisma.SortOrder
  conditionJson?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  isFallback?: Prisma.SortOrder
  toStageId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.DialogueTransitionCountOrderByAggregateInput
  _avg?: Prisma.DialogueTransitionAvgOrderByAggregateInput
  _max?: Prisma.DialogueTransitionMaxOrderByAggregateInput
  _min?: Prisma.DialogueTransitionMinOrderByAggregateInput
  _sum?: Prisma.DialogueTransitionSumOrderByAggregateInput
}

export type DialogueTransitionScalarWhereWithAggregatesInput = {
  AND?: Prisma.DialogueTransitionScalarWhereWithAggregatesInput | Prisma.DialogueTransitionScalarWhereWithAggregatesInput[]
  OR?: Prisma.DialogueTransitionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DialogueTransitionScalarWhereWithAggregatesInput | Prisma.DialogueTransitionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"DialogueTransition"> | string
  scenarioId?: Prisma.StringWithAggregatesFilter<"DialogueTransition"> | string
  fromStageId?: Prisma.StringWithAggregatesFilter<"DialogueTransition"> | string
  outcomeKey?: Prisma.StringWithAggregatesFilter<"DialogueTransition"> | string
  label?: Prisma.StringWithAggregatesFilter<"DialogueTransition"> | string
  conditionJson?: Prisma.StringWithAggregatesFilter<"DialogueTransition"> | string
  priority?: Prisma.IntWithAggregatesFilter<"DialogueTransition"> | number
  isFallback?: Prisma.BoolWithAggregatesFilter<"DialogueTransition"> | boolean
  toStageId?: Prisma.StringNullableWithAggregatesFilter<"DialogueTransition"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"DialogueTransition"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"DialogueTransition"> | Date | string
}

export type DialogueTransitionCreateInput = {
  id?: string
  outcomeKey: string
  label?: string
  conditionJson?: string
  priority?: number
  isFallback?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  scenario: Prisma.DialogueScenarioCreateNestedOneWithoutTransitionsInput
  fromStage: Prisma.DialogueStageCreateNestedOneWithoutOutgoingTransitionsInput
  toStage?: Prisma.DialogueStageCreateNestedOneWithoutIncomingTransitionsInput
}

export type DialogueTransitionUncheckedCreateInput = {
  id?: string
  scenarioId: string
  fromStageId: string
  outcomeKey: string
  label?: string
  conditionJson?: string
  priority?: number
  isFallback?: boolean
  toStageId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DialogueTransitionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  outcomeKey?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  conditionJson?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  isFallback?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  scenario?: Prisma.DialogueScenarioUpdateOneRequiredWithoutTransitionsNestedInput
  fromStage?: Prisma.DialogueStageUpdateOneRequiredWithoutOutgoingTransitionsNestedInput
  toStage?: Prisma.DialogueStageUpdateOneWithoutIncomingTransitionsNestedInput
}

export type DialogueTransitionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scenarioId?: Prisma.StringFieldUpdateOperationsInput | string
  fromStageId?: Prisma.StringFieldUpdateOperationsInput | string
  outcomeKey?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  conditionJson?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  isFallback?: Prisma.BoolFieldUpdateOperationsInput | boolean
  toStageId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DialogueTransitionCreateManyInput = {
  id?: string
  scenarioId: string
  fromStageId: string
  outcomeKey: string
  label?: string
  conditionJson?: string
  priority?: number
  isFallback?: boolean
  toStageId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DialogueTransitionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  outcomeKey?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  conditionJson?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  isFallback?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DialogueTransitionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scenarioId?: Prisma.StringFieldUpdateOperationsInput | string
  fromStageId?: Prisma.StringFieldUpdateOperationsInput | string
  outcomeKey?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  conditionJson?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  isFallback?: Prisma.BoolFieldUpdateOperationsInput | boolean
  toStageId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DialogueTransitionListRelationFilter = {
  every?: Prisma.DialogueTransitionWhereInput
  some?: Prisma.DialogueTransitionWhereInput
  none?: Prisma.DialogueTransitionWhereInput
}

export type DialogueTransitionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DialogueTransitionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  scenarioId?: Prisma.SortOrder
  fromStageId?: Prisma.SortOrder
  outcomeKey?: Prisma.SortOrder
  label?: Prisma.SortOrder
  conditionJson?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  isFallback?: Prisma.SortOrder
  toStageId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DialogueTransitionAvgOrderByAggregateInput = {
  priority?: Prisma.SortOrder
}

export type DialogueTransitionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  scenarioId?: Prisma.SortOrder
  fromStageId?: Prisma.SortOrder
  outcomeKey?: Prisma.SortOrder
  label?: Prisma.SortOrder
  conditionJson?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  isFallback?: Prisma.SortOrder
  toStageId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DialogueTransitionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  scenarioId?: Prisma.SortOrder
  fromStageId?: Prisma.SortOrder
  outcomeKey?: Prisma.SortOrder
  label?: Prisma.SortOrder
  conditionJson?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  isFallback?: Prisma.SortOrder
  toStageId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DialogueTransitionSumOrderByAggregateInput = {
  priority?: Prisma.SortOrder
}

export type DialogueTransitionCreateNestedManyWithoutScenarioInput = {
  create?: Prisma.XOR<Prisma.DialogueTransitionCreateWithoutScenarioInput, Prisma.DialogueTransitionUncheckedCreateWithoutScenarioInput> | Prisma.DialogueTransitionCreateWithoutScenarioInput[] | Prisma.DialogueTransitionUncheckedCreateWithoutScenarioInput[]
  connectOrCreate?: Prisma.DialogueTransitionCreateOrConnectWithoutScenarioInput | Prisma.DialogueTransitionCreateOrConnectWithoutScenarioInput[]
  createMany?: Prisma.DialogueTransitionCreateManyScenarioInputEnvelope
  connect?: Prisma.DialogueTransitionWhereUniqueInput | Prisma.DialogueTransitionWhereUniqueInput[]
}

export type DialogueTransitionUncheckedCreateNestedManyWithoutScenarioInput = {
  create?: Prisma.XOR<Prisma.DialogueTransitionCreateWithoutScenarioInput, Prisma.DialogueTransitionUncheckedCreateWithoutScenarioInput> | Prisma.DialogueTransitionCreateWithoutScenarioInput[] | Prisma.DialogueTransitionUncheckedCreateWithoutScenarioInput[]
  connectOrCreate?: Prisma.DialogueTransitionCreateOrConnectWithoutScenarioInput | Prisma.DialogueTransitionCreateOrConnectWithoutScenarioInput[]
  createMany?: Prisma.DialogueTransitionCreateManyScenarioInputEnvelope
  connect?: Prisma.DialogueTransitionWhereUniqueInput | Prisma.DialogueTransitionWhereUniqueInput[]
}

export type DialogueTransitionUpdateManyWithoutScenarioNestedInput = {
  create?: Prisma.XOR<Prisma.DialogueTransitionCreateWithoutScenarioInput, Prisma.DialogueTransitionUncheckedCreateWithoutScenarioInput> | Prisma.DialogueTransitionCreateWithoutScenarioInput[] | Prisma.DialogueTransitionUncheckedCreateWithoutScenarioInput[]
  connectOrCreate?: Prisma.DialogueTransitionCreateOrConnectWithoutScenarioInput | Prisma.DialogueTransitionCreateOrConnectWithoutScenarioInput[]
  upsert?: Prisma.DialogueTransitionUpsertWithWhereUniqueWithoutScenarioInput | Prisma.DialogueTransitionUpsertWithWhereUniqueWithoutScenarioInput[]
  createMany?: Prisma.DialogueTransitionCreateManyScenarioInputEnvelope
  set?: Prisma.DialogueTransitionWhereUniqueInput | Prisma.DialogueTransitionWhereUniqueInput[]
  disconnect?: Prisma.DialogueTransitionWhereUniqueInput | Prisma.DialogueTransitionWhereUniqueInput[]
  delete?: Prisma.DialogueTransitionWhereUniqueInput | Prisma.DialogueTransitionWhereUniqueInput[]
  connect?: Prisma.DialogueTransitionWhereUniqueInput | Prisma.DialogueTransitionWhereUniqueInput[]
  update?: Prisma.DialogueTransitionUpdateWithWhereUniqueWithoutScenarioInput | Prisma.DialogueTransitionUpdateWithWhereUniqueWithoutScenarioInput[]
  updateMany?: Prisma.DialogueTransitionUpdateManyWithWhereWithoutScenarioInput | Prisma.DialogueTransitionUpdateManyWithWhereWithoutScenarioInput[]
  deleteMany?: Prisma.DialogueTransitionScalarWhereInput | Prisma.DialogueTransitionScalarWhereInput[]
}

export type DialogueTransitionUncheckedUpdateManyWithoutScenarioNestedInput = {
  create?: Prisma.XOR<Prisma.DialogueTransitionCreateWithoutScenarioInput, Prisma.DialogueTransitionUncheckedCreateWithoutScenarioInput> | Prisma.DialogueTransitionCreateWithoutScenarioInput[] | Prisma.DialogueTransitionUncheckedCreateWithoutScenarioInput[]
  connectOrCreate?: Prisma.DialogueTransitionCreateOrConnectWithoutScenarioInput | Prisma.DialogueTransitionCreateOrConnectWithoutScenarioInput[]
  upsert?: Prisma.DialogueTransitionUpsertWithWhereUniqueWithoutScenarioInput | Prisma.DialogueTransitionUpsertWithWhereUniqueWithoutScenarioInput[]
  createMany?: Prisma.DialogueTransitionCreateManyScenarioInputEnvelope
  set?: Prisma.DialogueTransitionWhereUniqueInput | Prisma.DialogueTransitionWhereUniqueInput[]
  disconnect?: Prisma.DialogueTransitionWhereUniqueInput | Prisma.DialogueTransitionWhereUniqueInput[]
  delete?: Prisma.DialogueTransitionWhereUniqueInput | Prisma.DialogueTransitionWhereUniqueInput[]
  connect?: Prisma.DialogueTransitionWhereUniqueInput | Prisma.DialogueTransitionWhereUniqueInput[]
  update?: Prisma.DialogueTransitionUpdateWithWhereUniqueWithoutScenarioInput | Prisma.DialogueTransitionUpdateWithWhereUniqueWithoutScenarioInput[]
  updateMany?: Prisma.DialogueTransitionUpdateManyWithWhereWithoutScenarioInput | Prisma.DialogueTransitionUpdateManyWithWhereWithoutScenarioInput[]
  deleteMany?: Prisma.DialogueTransitionScalarWhereInput | Prisma.DialogueTransitionScalarWhereInput[]
}

export type DialogueTransitionCreateNestedManyWithoutFromStageInput = {
  create?: Prisma.XOR<Prisma.DialogueTransitionCreateWithoutFromStageInput, Prisma.DialogueTransitionUncheckedCreateWithoutFromStageInput> | Prisma.DialogueTransitionCreateWithoutFromStageInput[] | Prisma.DialogueTransitionUncheckedCreateWithoutFromStageInput[]
  connectOrCreate?: Prisma.DialogueTransitionCreateOrConnectWithoutFromStageInput | Prisma.DialogueTransitionCreateOrConnectWithoutFromStageInput[]
  createMany?: Prisma.DialogueTransitionCreateManyFromStageInputEnvelope
  connect?: Prisma.DialogueTransitionWhereUniqueInput | Prisma.DialogueTransitionWhereUniqueInput[]
}

export type DialogueTransitionCreateNestedManyWithoutToStageInput = {
  create?: Prisma.XOR<Prisma.DialogueTransitionCreateWithoutToStageInput, Prisma.DialogueTransitionUncheckedCreateWithoutToStageInput> | Prisma.DialogueTransitionCreateWithoutToStageInput[] | Prisma.DialogueTransitionUncheckedCreateWithoutToStageInput[]
  connectOrCreate?: Prisma.DialogueTransitionCreateOrConnectWithoutToStageInput | Prisma.DialogueTransitionCreateOrConnectWithoutToStageInput[]
  createMany?: Prisma.DialogueTransitionCreateManyToStageInputEnvelope
  connect?: Prisma.DialogueTransitionWhereUniqueInput | Prisma.DialogueTransitionWhereUniqueInput[]
}

export type DialogueTransitionUncheckedCreateNestedManyWithoutFromStageInput = {
  create?: Prisma.XOR<Prisma.DialogueTransitionCreateWithoutFromStageInput, Prisma.DialogueTransitionUncheckedCreateWithoutFromStageInput> | Prisma.DialogueTransitionCreateWithoutFromStageInput[] | Prisma.DialogueTransitionUncheckedCreateWithoutFromStageInput[]
  connectOrCreate?: Prisma.DialogueTransitionCreateOrConnectWithoutFromStageInput | Prisma.DialogueTransitionCreateOrConnectWithoutFromStageInput[]
  createMany?: Prisma.DialogueTransitionCreateManyFromStageInputEnvelope
  connect?: Prisma.DialogueTransitionWhereUniqueInput | Prisma.DialogueTransitionWhereUniqueInput[]
}

export type DialogueTransitionUncheckedCreateNestedManyWithoutToStageInput = {
  create?: Prisma.XOR<Prisma.DialogueTransitionCreateWithoutToStageInput, Prisma.DialogueTransitionUncheckedCreateWithoutToStageInput> | Prisma.DialogueTransitionCreateWithoutToStageInput[] | Prisma.DialogueTransitionUncheckedCreateWithoutToStageInput[]
  connectOrCreate?: Prisma.DialogueTransitionCreateOrConnectWithoutToStageInput | Prisma.DialogueTransitionCreateOrConnectWithoutToStageInput[]
  createMany?: Prisma.DialogueTransitionCreateManyToStageInputEnvelope
  connect?: Prisma.DialogueTransitionWhereUniqueInput | Prisma.DialogueTransitionWhereUniqueInput[]
}

export type DialogueTransitionUpdateManyWithoutFromStageNestedInput = {
  create?: Prisma.XOR<Prisma.DialogueTransitionCreateWithoutFromStageInput, Prisma.DialogueTransitionUncheckedCreateWithoutFromStageInput> | Prisma.DialogueTransitionCreateWithoutFromStageInput[] | Prisma.DialogueTransitionUncheckedCreateWithoutFromStageInput[]
  connectOrCreate?: Prisma.DialogueTransitionCreateOrConnectWithoutFromStageInput | Prisma.DialogueTransitionCreateOrConnectWithoutFromStageInput[]
  upsert?: Prisma.DialogueTransitionUpsertWithWhereUniqueWithoutFromStageInput | Prisma.DialogueTransitionUpsertWithWhereUniqueWithoutFromStageInput[]
  createMany?: Prisma.DialogueTransitionCreateManyFromStageInputEnvelope
  set?: Prisma.DialogueTransitionWhereUniqueInput | Prisma.DialogueTransitionWhereUniqueInput[]
  disconnect?: Prisma.DialogueTransitionWhereUniqueInput | Prisma.DialogueTransitionWhereUniqueInput[]
  delete?: Prisma.DialogueTransitionWhereUniqueInput | Prisma.DialogueTransitionWhereUniqueInput[]
  connect?: Prisma.DialogueTransitionWhereUniqueInput | Prisma.DialogueTransitionWhereUniqueInput[]
  update?: Prisma.DialogueTransitionUpdateWithWhereUniqueWithoutFromStageInput | Prisma.DialogueTransitionUpdateWithWhereUniqueWithoutFromStageInput[]
  updateMany?: Prisma.DialogueTransitionUpdateManyWithWhereWithoutFromStageInput | Prisma.DialogueTransitionUpdateManyWithWhereWithoutFromStageInput[]
  deleteMany?: Prisma.DialogueTransitionScalarWhereInput | Prisma.DialogueTransitionScalarWhereInput[]
}

export type DialogueTransitionUpdateManyWithoutToStageNestedInput = {
  create?: Prisma.XOR<Prisma.DialogueTransitionCreateWithoutToStageInput, Prisma.DialogueTransitionUncheckedCreateWithoutToStageInput> | Prisma.DialogueTransitionCreateWithoutToStageInput[] | Prisma.DialogueTransitionUncheckedCreateWithoutToStageInput[]
  connectOrCreate?: Prisma.DialogueTransitionCreateOrConnectWithoutToStageInput | Prisma.DialogueTransitionCreateOrConnectWithoutToStageInput[]
  upsert?: Prisma.DialogueTransitionUpsertWithWhereUniqueWithoutToStageInput | Prisma.DialogueTransitionUpsertWithWhereUniqueWithoutToStageInput[]
  createMany?: Prisma.DialogueTransitionCreateManyToStageInputEnvelope
  set?: Prisma.DialogueTransitionWhereUniqueInput | Prisma.DialogueTransitionWhereUniqueInput[]
  disconnect?: Prisma.DialogueTransitionWhereUniqueInput | Prisma.DialogueTransitionWhereUniqueInput[]
  delete?: Prisma.DialogueTransitionWhereUniqueInput | Prisma.DialogueTransitionWhereUniqueInput[]
  connect?: Prisma.DialogueTransitionWhereUniqueInput | Prisma.DialogueTransitionWhereUniqueInput[]
  update?: Prisma.DialogueTransitionUpdateWithWhereUniqueWithoutToStageInput | Prisma.DialogueTransitionUpdateWithWhereUniqueWithoutToStageInput[]
  updateMany?: Prisma.DialogueTransitionUpdateManyWithWhereWithoutToStageInput | Prisma.DialogueTransitionUpdateManyWithWhereWithoutToStageInput[]
  deleteMany?: Prisma.DialogueTransitionScalarWhereInput | Prisma.DialogueTransitionScalarWhereInput[]
}

export type DialogueTransitionUncheckedUpdateManyWithoutFromStageNestedInput = {
  create?: Prisma.XOR<Prisma.DialogueTransitionCreateWithoutFromStageInput, Prisma.DialogueTransitionUncheckedCreateWithoutFromStageInput> | Prisma.DialogueTransitionCreateWithoutFromStageInput[] | Prisma.DialogueTransitionUncheckedCreateWithoutFromStageInput[]
  connectOrCreate?: Prisma.DialogueTransitionCreateOrConnectWithoutFromStageInput | Prisma.DialogueTransitionCreateOrConnectWithoutFromStageInput[]
  upsert?: Prisma.DialogueTransitionUpsertWithWhereUniqueWithoutFromStageInput | Prisma.DialogueTransitionUpsertWithWhereUniqueWithoutFromStageInput[]
  createMany?: Prisma.DialogueTransitionCreateManyFromStageInputEnvelope
  set?: Prisma.DialogueTransitionWhereUniqueInput | Prisma.DialogueTransitionWhereUniqueInput[]
  disconnect?: Prisma.DialogueTransitionWhereUniqueInput | Prisma.DialogueTransitionWhereUniqueInput[]
  delete?: Prisma.DialogueTransitionWhereUniqueInput | Prisma.DialogueTransitionWhereUniqueInput[]
  connect?: Prisma.DialogueTransitionWhereUniqueInput | Prisma.DialogueTransitionWhereUniqueInput[]
  update?: Prisma.DialogueTransitionUpdateWithWhereUniqueWithoutFromStageInput | Prisma.DialogueTransitionUpdateWithWhereUniqueWithoutFromStageInput[]
  updateMany?: Prisma.DialogueTransitionUpdateManyWithWhereWithoutFromStageInput | Prisma.DialogueTransitionUpdateManyWithWhereWithoutFromStageInput[]
  deleteMany?: Prisma.DialogueTransitionScalarWhereInput | Prisma.DialogueTransitionScalarWhereInput[]
}

export type DialogueTransitionUncheckedUpdateManyWithoutToStageNestedInput = {
  create?: Prisma.XOR<Prisma.DialogueTransitionCreateWithoutToStageInput, Prisma.DialogueTransitionUncheckedCreateWithoutToStageInput> | Prisma.DialogueTransitionCreateWithoutToStageInput[] | Prisma.DialogueTransitionUncheckedCreateWithoutToStageInput[]
  connectOrCreate?: Prisma.DialogueTransitionCreateOrConnectWithoutToStageInput | Prisma.DialogueTransitionCreateOrConnectWithoutToStageInput[]
  upsert?: Prisma.DialogueTransitionUpsertWithWhereUniqueWithoutToStageInput | Prisma.DialogueTransitionUpsertWithWhereUniqueWithoutToStageInput[]
  createMany?: Prisma.DialogueTransitionCreateManyToStageInputEnvelope
  set?: Prisma.DialogueTransitionWhereUniqueInput | Prisma.DialogueTransitionWhereUniqueInput[]
  disconnect?: Prisma.DialogueTransitionWhereUniqueInput | Prisma.DialogueTransitionWhereUniqueInput[]
  delete?: Prisma.DialogueTransitionWhereUniqueInput | Prisma.DialogueTransitionWhereUniqueInput[]
  connect?: Prisma.DialogueTransitionWhereUniqueInput | Prisma.DialogueTransitionWhereUniqueInput[]
  update?: Prisma.DialogueTransitionUpdateWithWhereUniqueWithoutToStageInput | Prisma.DialogueTransitionUpdateWithWhereUniqueWithoutToStageInput[]
  updateMany?: Prisma.DialogueTransitionUpdateManyWithWhereWithoutToStageInput | Prisma.DialogueTransitionUpdateManyWithWhereWithoutToStageInput[]
  deleteMany?: Prisma.DialogueTransitionScalarWhereInput | Prisma.DialogueTransitionScalarWhereInput[]
}

export type DialogueTransitionCreateWithoutScenarioInput = {
  id?: string
  outcomeKey: string
  label?: string
  conditionJson?: string
  priority?: number
  isFallback?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  fromStage: Prisma.DialogueStageCreateNestedOneWithoutOutgoingTransitionsInput
  toStage?: Prisma.DialogueStageCreateNestedOneWithoutIncomingTransitionsInput
}

export type DialogueTransitionUncheckedCreateWithoutScenarioInput = {
  id?: string
  fromStageId: string
  outcomeKey: string
  label?: string
  conditionJson?: string
  priority?: number
  isFallback?: boolean
  toStageId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DialogueTransitionCreateOrConnectWithoutScenarioInput = {
  where: Prisma.DialogueTransitionWhereUniqueInput
  create: Prisma.XOR<Prisma.DialogueTransitionCreateWithoutScenarioInput, Prisma.DialogueTransitionUncheckedCreateWithoutScenarioInput>
}

export type DialogueTransitionCreateManyScenarioInputEnvelope = {
  data: Prisma.DialogueTransitionCreateManyScenarioInput | Prisma.DialogueTransitionCreateManyScenarioInput[]
}

export type DialogueTransitionUpsertWithWhereUniqueWithoutScenarioInput = {
  where: Prisma.DialogueTransitionWhereUniqueInput
  update: Prisma.XOR<Prisma.DialogueTransitionUpdateWithoutScenarioInput, Prisma.DialogueTransitionUncheckedUpdateWithoutScenarioInput>
  create: Prisma.XOR<Prisma.DialogueTransitionCreateWithoutScenarioInput, Prisma.DialogueTransitionUncheckedCreateWithoutScenarioInput>
}

export type DialogueTransitionUpdateWithWhereUniqueWithoutScenarioInput = {
  where: Prisma.DialogueTransitionWhereUniqueInput
  data: Prisma.XOR<Prisma.DialogueTransitionUpdateWithoutScenarioInput, Prisma.DialogueTransitionUncheckedUpdateWithoutScenarioInput>
}

export type DialogueTransitionUpdateManyWithWhereWithoutScenarioInput = {
  where: Prisma.DialogueTransitionScalarWhereInput
  data: Prisma.XOR<Prisma.DialogueTransitionUpdateManyMutationInput, Prisma.DialogueTransitionUncheckedUpdateManyWithoutScenarioInput>
}

export type DialogueTransitionScalarWhereInput = {
  AND?: Prisma.DialogueTransitionScalarWhereInput | Prisma.DialogueTransitionScalarWhereInput[]
  OR?: Prisma.DialogueTransitionScalarWhereInput[]
  NOT?: Prisma.DialogueTransitionScalarWhereInput | Prisma.DialogueTransitionScalarWhereInput[]
  id?: Prisma.StringFilter<"DialogueTransition"> | string
  scenarioId?: Prisma.StringFilter<"DialogueTransition"> | string
  fromStageId?: Prisma.StringFilter<"DialogueTransition"> | string
  outcomeKey?: Prisma.StringFilter<"DialogueTransition"> | string
  label?: Prisma.StringFilter<"DialogueTransition"> | string
  conditionJson?: Prisma.StringFilter<"DialogueTransition"> | string
  priority?: Prisma.IntFilter<"DialogueTransition"> | number
  isFallback?: Prisma.BoolFilter<"DialogueTransition"> | boolean
  toStageId?: Prisma.StringNullableFilter<"DialogueTransition"> | string | null
  createdAt?: Prisma.DateTimeFilter<"DialogueTransition"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DialogueTransition"> | Date | string
}

export type DialogueTransitionCreateWithoutFromStageInput = {
  id?: string
  outcomeKey: string
  label?: string
  conditionJson?: string
  priority?: number
  isFallback?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  scenario: Prisma.DialogueScenarioCreateNestedOneWithoutTransitionsInput
  toStage?: Prisma.DialogueStageCreateNestedOneWithoutIncomingTransitionsInput
}

export type DialogueTransitionUncheckedCreateWithoutFromStageInput = {
  id?: string
  scenarioId: string
  outcomeKey: string
  label?: string
  conditionJson?: string
  priority?: number
  isFallback?: boolean
  toStageId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DialogueTransitionCreateOrConnectWithoutFromStageInput = {
  where: Prisma.DialogueTransitionWhereUniqueInput
  create: Prisma.XOR<Prisma.DialogueTransitionCreateWithoutFromStageInput, Prisma.DialogueTransitionUncheckedCreateWithoutFromStageInput>
}

export type DialogueTransitionCreateManyFromStageInputEnvelope = {
  data: Prisma.DialogueTransitionCreateManyFromStageInput | Prisma.DialogueTransitionCreateManyFromStageInput[]
}

export type DialogueTransitionCreateWithoutToStageInput = {
  id?: string
  outcomeKey: string
  label?: string
  conditionJson?: string
  priority?: number
  isFallback?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  scenario: Prisma.DialogueScenarioCreateNestedOneWithoutTransitionsInput
  fromStage: Prisma.DialogueStageCreateNestedOneWithoutOutgoingTransitionsInput
}

export type DialogueTransitionUncheckedCreateWithoutToStageInput = {
  id?: string
  scenarioId: string
  fromStageId: string
  outcomeKey: string
  label?: string
  conditionJson?: string
  priority?: number
  isFallback?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DialogueTransitionCreateOrConnectWithoutToStageInput = {
  where: Prisma.DialogueTransitionWhereUniqueInput
  create: Prisma.XOR<Prisma.DialogueTransitionCreateWithoutToStageInput, Prisma.DialogueTransitionUncheckedCreateWithoutToStageInput>
}

export type DialogueTransitionCreateManyToStageInputEnvelope = {
  data: Prisma.DialogueTransitionCreateManyToStageInput | Prisma.DialogueTransitionCreateManyToStageInput[]
}

export type DialogueTransitionUpsertWithWhereUniqueWithoutFromStageInput = {
  where: Prisma.DialogueTransitionWhereUniqueInput
  update: Prisma.XOR<Prisma.DialogueTransitionUpdateWithoutFromStageInput, Prisma.DialogueTransitionUncheckedUpdateWithoutFromStageInput>
  create: Prisma.XOR<Prisma.DialogueTransitionCreateWithoutFromStageInput, Prisma.DialogueTransitionUncheckedCreateWithoutFromStageInput>
}

export type DialogueTransitionUpdateWithWhereUniqueWithoutFromStageInput = {
  where: Prisma.DialogueTransitionWhereUniqueInput
  data: Prisma.XOR<Prisma.DialogueTransitionUpdateWithoutFromStageInput, Prisma.DialogueTransitionUncheckedUpdateWithoutFromStageInput>
}

export type DialogueTransitionUpdateManyWithWhereWithoutFromStageInput = {
  where: Prisma.DialogueTransitionScalarWhereInput
  data: Prisma.XOR<Prisma.DialogueTransitionUpdateManyMutationInput, Prisma.DialogueTransitionUncheckedUpdateManyWithoutFromStageInput>
}

export type DialogueTransitionUpsertWithWhereUniqueWithoutToStageInput = {
  where: Prisma.DialogueTransitionWhereUniqueInput
  update: Prisma.XOR<Prisma.DialogueTransitionUpdateWithoutToStageInput, Prisma.DialogueTransitionUncheckedUpdateWithoutToStageInput>
  create: Prisma.XOR<Prisma.DialogueTransitionCreateWithoutToStageInput, Prisma.DialogueTransitionUncheckedCreateWithoutToStageInput>
}

export type DialogueTransitionUpdateWithWhereUniqueWithoutToStageInput = {
  where: Prisma.DialogueTransitionWhereUniqueInput
  data: Prisma.XOR<Prisma.DialogueTransitionUpdateWithoutToStageInput, Prisma.DialogueTransitionUncheckedUpdateWithoutToStageInput>
}

export type DialogueTransitionUpdateManyWithWhereWithoutToStageInput = {
  where: Prisma.DialogueTransitionScalarWhereInput
  data: Prisma.XOR<Prisma.DialogueTransitionUpdateManyMutationInput, Prisma.DialogueTransitionUncheckedUpdateManyWithoutToStageInput>
}

export type DialogueTransitionCreateManyScenarioInput = {
  id?: string
  fromStageId: string
  outcomeKey: string
  label?: string
  conditionJson?: string
  priority?: number
  isFallback?: boolean
  toStageId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DialogueTransitionUpdateWithoutScenarioInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  outcomeKey?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  conditionJson?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  isFallback?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fromStage?: Prisma.DialogueStageUpdateOneRequiredWithoutOutgoingTransitionsNestedInput
  toStage?: Prisma.DialogueStageUpdateOneWithoutIncomingTransitionsNestedInput
}

export type DialogueTransitionUncheckedUpdateWithoutScenarioInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromStageId?: Prisma.StringFieldUpdateOperationsInput | string
  outcomeKey?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  conditionJson?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  isFallback?: Prisma.BoolFieldUpdateOperationsInput | boolean
  toStageId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DialogueTransitionUncheckedUpdateManyWithoutScenarioInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromStageId?: Prisma.StringFieldUpdateOperationsInput | string
  outcomeKey?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  conditionJson?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  isFallback?: Prisma.BoolFieldUpdateOperationsInput | boolean
  toStageId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DialogueTransitionCreateManyFromStageInput = {
  id?: string
  scenarioId: string
  outcomeKey: string
  label?: string
  conditionJson?: string
  priority?: number
  isFallback?: boolean
  toStageId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DialogueTransitionCreateManyToStageInput = {
  id?: string
  scenarioId: string
  fromStageId: string
  outcomeKey: string
  label?: string
  conditionJson?: string
  priority?: number
  isFallback?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DialogueTransitionUpdateWithoutFromStageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  outcomeKey?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  conditionJson?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  isFallback?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  scenario?: Prisma.DialogueScenarioUpdateOneRequiredWithoutTransitionsNestedInput
  toStage?: Prisma.DialogueStageUpdateOneWithoutIncomingTransitionsNestedInput
}

export type DialogueTransitionUncheckedUpdateWithoutFromStageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scenarioId?: Prisma.StringFieldUpdateOperationsInput | string
  outcomeKey?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  conditionJson?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  isFallback?: Prisma.BoolFieldUpdateOperationsInput | boolean
  toStageId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DialogueTransitionUncheckedUpdateManyWithoutFromStageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scenarioId?: Prisma.StringFieldUpdateOperationsInput | string
  outcomeKey?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  conditionJson?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  isFallback?: Prisma.BoolFieldUpdateOperationsInput | boolean
  toStageId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DialogueTransitionUpdateWithoutToStageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  outcomeKey?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  conditionJson?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  isFallback?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  scenario?: Prisma.DialogueScenarioUpdateOneRequiredWithoutTransitionsNestedInput
  fromStage?: Prisma.DialogueStageUpdateOneRequiredWithoutOutgoingTransitionsNestedInput
}

export type DialogueTransitionUncheckedUpdateWithoutToStageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scenarioId?: Prisma.StringFieldUpdateOperationsInput | string
  fromStageId?: Prisma.StringFieldUpdateOperationsInput | string
  outcomeKey?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  conditionJson?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  isFallback?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DialogueTransitionUncheckedUpdateManyWithoutToStageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scenarioId?: Prisma.StringFieldUpdateOperationsInput | string
  fromStageId?: Prisma.StringFieldUpdateOperationsInput | string
  outcomeKey?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  conditionJson?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  isFallback?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type DialogueTransitionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  scenarioId?: boolean
  fromStageId?: boolean
  outcomeKey?: boolean
  label?: boolean
  conditionJson?: boolean
  priority?: boolean
  isFallback?: boolean
  toStageId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  scenario?: boolean | Prisma.DialogueScenarioDefaultArgs<ExtArgs>
  fromStage?: boolean | Prisma.DialogueStageDefaultArgs<ExtArgs>
  toStage?: boolean | Prisma.DialogueTransition$toStageArgs<ExtArgs>
}, ExtArgs["result"]["dialogueTransition"]>

export type DialogueTransitionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  scenarioId?: boolean
  fromStageId?: boolean
  outcomeKey?: boolean
  label?: boolean
  conditionJson?: boolean
  priority?: boolean
  isFallback?: boolean
  toStageId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  scenario?: boolean | Prisma.DialogueScenarioDefaultArgs<ExtArgs>
  fromStage?: boolean | Prisma.DialogueStageDefaultArgs<ExtArgs>
  toStage?: boolean | Prisma.DialogueTransition$toStageArgs<ExtArgs>
}, ExtArgs["result"]["dialogueTransition"]>

export type DialogueTransitionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  scenarioId?: boolean
  fromStageId?: boolean
  outcomeKey?: boolean
  label?: boolean
  conditionJson?: boolean
  priority?: boolean
  isFallback?: boolean
  toStageId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  scenario?: boolean | Prisma.DialogueScenarioDefaultArgs<ExtArgs>
  fromStage?: boolean | Prisma.DialogueStageDefaultArgs<ExtArgs>
  toStage?: boolean | Prisma.DialogueTransition$toStageArgs<ExtArgs>
}, ExtArgs["result"]["dialogueTransition"]>

export type DialogueTransitionSelectScalar = {
  id?: boolean
  scenarioId?: boolean
  fromStageId?: boolean
  outcomeKey?: boolean
  label?: boolean
  conditionJson?: boolean
  priority?: boolean
  isFallback?: boolean
  toStageId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type DialogueTransitionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "scenarioId" | "fromStageId" | "outcomeKey" | "label" | "conditionJson" | "priority" | "isFallback" | "toStageId" | "createdAt" | "updatedAt", ExtArgs["result"]["dialogueTransition"]>
export type DialogueTransitionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  scenario?: boolean | Prisma.DialogueScenarioDefaultArgs<ExtArgs>
  fromStage?: boolean | Prisma.DialogueStageDefaultArgs<ExtArgs>
  toStage?: boolean | Prisma.DialogueTransition$toStageArgs<ExtArgs>
}
export type DialogueTransitionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  scenario?: boolean | Prisma.DialogueScenarioDefaultArgs<ExtArgs>
  fromStage?: boolean | Prisma.DialogueStageDefaultArgs<ExtArgs>
  toStage?: boolean | Prisma.DialogueTransition$toStageArgs<ExtArgs>
}
export type DialogueTransitionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  scenario?: boolean | Prisma.DialogueScenarioDefaultArgs<ExtArgs>
  fromStage?: boolean | Prisma.DialogueStageDefaultArgs<ExtArgs>
  toStage?: boolean | Prisma.DialogueTransition$toStageArgs<ExtArgs>
}

export type $DialogueTransitionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DialogueTransition"
  objects: {
    scenario: Prisma.$DialogueScenarioPayload<ExtArgs>
    fromStage: Prisma.$DialogueStagePayload<ExtArgs>
    toStage: Prisma.$DialogueStagePayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    scenarioId: string
    fromStageId: string
    outcomeKey: string
    label: string
    conditionJson: string
    priority: number
    isFallback: boolean
    toStageId: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["dialogueTransition"]>
  composites: {}
}

export type DialogueTransitionGetPayload<S extends boolean | null | undefined | DialogueTransitionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DialogueTransitionPayload, S>

export type DialogueTransitionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DialogueTransitionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DialogueTransitionCountAggregateInputType | true
  }

export interface DialogueTransitionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DialogueTransition'], meta: { name: 'DialogueTransition' } }
  /**
   * Find zero or one DialogueTransition that matches the filter.
   * @param {DialogueTransitionFindUniqueArgs} args - Arguments to find a DialogueTransition
   * @example
   * // Get one DialogueTransition
   * const dialogueTransition = await prisma.dialogueTransition.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DialogueTransitionFindUniqueArgs>(args: Prisma.SelectSubset<T, DialogueTransitionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DialogueTransitionClient<runtime.Types.Result.GetResult<Prisma.$DialogueTransitionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DialogueTransition that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DialogueTransitionFindUniqueOrThrowArgs} args - Arguments to find a DialogueTransition
   * @example
   * // Get one DialogueTransition
   * const dialogueTransition = await prisma.dialogueTransition.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DialogueTransitionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DialogueTransitionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DialogueTransitionClient<runtime.Types.Result.GetResult<Prisma.$DialogueTransitionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DialogueTransition that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DialogueTransitionFindFirstArgs} args - Arguments to find a DialogueTransition
   * @example
   * // Get one DialogueTransition
   * const dialogueTransition = await prisma.dialogueTransition.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DialogueTransitionFindFirstArgs>(args?: Prisma.SelectSubset<T, DialogueTransitionFindFirstArgs<ExtArgs>>): Prisma.Prisma__DialogueTransitionClient<runtime.Types.Result.GetResult<Prisma.$DialogueTransitionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DialogueTransition that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DialogueTransitionFindFirstOrThrowArgs} args - Arguments to find a DialogueTransition
   * @example
   * // Get one DialogueTransition
   * const dialogueTransition = await prisma.dialogueTransition.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DialogueTransitionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DialogueTransitionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DialogueTransitionClient<runtime.Types.Result.GetResult<Prisma.$DialogueTransitionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DialogueTransitions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DialogueTransitionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DialogueTransitions
   * const dialogueTransitions = await prisma.dialogueTransition.findMany()
   * 
   * // Get first 10 DialogueTransitions
   * const dialogueTransitions = await prisma.dialogueTransition.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const dialogueTransitionWithIdOnly = await prisma.dialogueTransition.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DialogueTransitionFindManyArgs>(args?: Prisma.SelectSubset<T, DialogueTransitionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DialogueTransitionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DialogueTransition.
   * @param {DialogueTransitionCreateArgs} args - Arguments to create a DialogueTransition.
   * @example
   * // Create one DialogueTransition
   * const DialogueTransition = await prisma.dialogueTransition.create({
   *   data: {
   *     // ... data to create a DialogueTransition
   *   }
   * })
   * 
   */
  create<T extends DialogueTransitionCreateArgs>(args: Prisma.SelectSubset<T, DialogueTransitionCreateArgs<ExtArgs>>): Prisma.Prisma__DialogueTransitionClient<runtime.Types.Result.GetResult<Prisma.$DialogueTransitionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DialogueTransitions.
   * @param {DialogueTransitionCreateManyArgs} args - Arguments to create many DialogueTransitions.
   * @example
   * // Create many DialogueTransitions
   * const dialogueTransition = await prisma.dialogueTransition.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DialogueTransitionCreateManyArgs>(args?: Prisma.SelectSubset<T, DialogueTransitionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DialogueTransitions and returns the data saved in the database.
   * @param {DialogueTransitionCreateManyAndReturnArgs} args - Arguments to create many DialogueTransitions.
   * @example
   * // Create many DialogueTransitions
   * const dialogueTransition = await prisma.dialogueTransition.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DialogueTransitions and only return the `id`
   * const dialogueTransitionWithIdOnly = await prisma.dialogueTransition.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DialogueTransitionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DialogueTransitionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DialogueTransitionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DialogueTransition.
   * @param {DialogueTransitionDeleteArgs} args - Arguments to delete one DialogueTransition.
   * @example
   * // Delete one DialogueTransition
   * const DialogueTransition = await prisma.dialogueTransition.delete({
   *   where: {
   *     // ... filter to delete one DialogueTransition
   *   }
   * })
   * 
   */
  delete<T extends DialogueTransitionDeleteArgs>(args: Prisma.SelectSubset<T, DialogueTransitionDeleteArgs<ExtArgs>>): Prisma.Prisma__DialogueTransitionClient<runtime.Types.Result.GetResult<Prisma.$DialogueTransitionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DialogueTransition.
   * @param {DialogueTransitionUpdateArgs} args - Arguments to update one DialogueTransition.
   * @example
   * // Update one DialogueTransition
   * const dialogueTransition = await prisma.dialogueTransition.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DialogueTransitionUpdateArgs>(args: Prisma.SelectSubset<T, DialogueTransitionUpdateArgs<ExtArgs>>): Prisma.Prisma__DialogueTransitionClient<runtime.Types.Result.GetResult<Prisma.$DialogueTransitionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DialogueTransitions.
   * @param {DialogueTransitionDeleteManyArgs} args - Arguments to filter DialogueTransitions to delete.
   * @example
   * // Delete a few DialogueTransitions
   * const { count } = await prisma.dialogueTransition.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DialogueTransitionDeleteManyArgs>(args?: Prisma.SelectSubset<T, DialogueTransitionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DialogueTransitions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DialogueTransitionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DialogueTransitions
   * const dialogueTransition = await prisma.dialogueTransition.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DialogueTransitionUpdateManyArgs>(args: Prisma.SelectSubset<T, DialogueTransitionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DialogueTransitions and returns the data updated in the database.
   * @param {DialogueTransitionUpdateManyAndReturnArgs} args - Arguments to update many DialogueTransitions.
   * @example
   * // Update many DialogueTransitions
   * const dialogueTransition = await prisma.dialogueTransition.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DialogueTransitions and only return the `id`
   * const dialogueTransitionWithIdOnly = await prisma.dialogueTransition.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DialogueTransitionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DialogueTransitionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DialogueTransitionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DialogueTransition.
   * @param {DialogueTransitionUpsertArgs} args - Arguments to update or create a DialogueTransition.
   * @example
   * // Update or create a DialogueTransition
   * const dialogueTransition = await prisma.dialogueTransition.upsert({
   *   create: {
   *     // ... data to create a DialogueTransition
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DialogueTransition we want to update
   *   }
   * })
   */
  upsert<T extends DialogueTransitionUpsertArgs>(args: Prisma.SelectSubset<T, DialogueTransitionUpsertArgs<ExtArgs>>): Prisma.Prisma__DialogueTransitionClient<runtime.Types.Result.GetResult<Prisma.$DialogueTransitionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DialogueTransitions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DialogueTransitionCountArgs} args - Arguments to filter DialogueTransitions to count.
   * @example
   * // Count the number of DialogueTransitions
   * const count = await prisma.dialogueTransition.count({
   *   where: {
   *     // ... the filter for the DialogueTransitions we want to count
   *   }
   * })
  **/
  count<T extends DialogueTransitionCountArgs>(
    args?: Prisma.Subset<T, DialogueTransitionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DialogueTransitionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DialogueTransition.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DialogueTransitionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DialogueTransitionAggregateArgs>(args: Prisma.Subset<T, DialogueTransitionAggregateArgs>): Prisma.PrismaPromise<GetDialogueTransitionAggregateType<T>>

  /**
   * Group by DialogueTransition.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DialogueTransitionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DialogueTransitionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DialogueTransitionGroupByArgs['orderBy'] }
      : { orderBy?: DialogueTransitionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DialogueTransitionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDialogueTransitionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DialogueTransition model
 */
readonly fields: DialogueTransitionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DialogueTransition.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DialogueTransitionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  scenario<T extends Prisma.DialogueScenarioDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DialogueScenarioDefaultArgs<ExtArgs>>): Prisma.Prisma__DialogueScenarioClient<runtime.Types.Result.GetResult<Prisma.$DialogueScenarioPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  fromStage<T extends Prisma.DialogueStageDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DialogueStageDefaultArgs<ExtArgs>>): Prisma.Prisma__DialogueStageClient<runtime.Types.Result.GetResult<Prisma.$DialogueStagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  toStage<T extends Prisma.DialogueTransition$toStageArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DialogueTransition$toStageArgs<ExtArgs>>): Prisma.Prisma__DialogueStageClient<runtime.Types.Result.GetResult<Prisma.$DialogueStagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DialogueTransition model
 */
export interface DialogueTransitionFieldRefs {
  readonly id: Prisma.FieldRef<"DialogueTransition", 'String'>
  readonly scenarioId: Prisma.FieldRef<"DialogueTransition", 'String'>
  readonly fromStageId: Prisma.FieldRef<"DialogueTransition", 'String'>
  readonly outcomeKey: Prisma.FieldRef<"DialogueTransition", 'String'>
  readonly label: Prisma.FieldRef<"DialogueTransition", 'String'>
  readonly conditionJson: Prisma.FieldRef<"DialogueTransition", 'String'>
  readonly priority: Prisma.FieldRef<"DialogueTransition", 'Int'>
  readonly isFallback: Prisma.FieldRef<"DialogueTransition", 'Boolean'>
  readonly toStageId: Prisma.FieldRef<"DialogueTransition", 'String'>
  readonly createdAt: Prisma.FieldRef<"DialogueTransition", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"DialogueTransition", 'DateTime'>
}
    

// Custom InputTypes
/**
 * DialogueTransition findUnique
 */
export type DialogueTransitionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueTransition
   */
  select?: Prisma.DialogueTransitionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueTransition
   */
  omit?: Prisma.DialogueTransitionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueTransitionInclude<ExtArgs> | null
  /**
   * Filter, which DialogueTransition to fetch.
   */
  where: Prisma.DialogueTransitionWhereUniqueInput
}

/**
 * DialogueTransition findUniqueOrThrow
 */
export type DialogueTransitionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueTransition
   */
  select?: Prisma.DialogueTransitionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueTransition
   */
  omit?: Prisma.DialogueTransitionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueTransitionInclude<ExtArgs> | null
  /**
   * Filter, which DialogueTransition to fetch.
   */
  where: Prisma.DialogueTransitionWhereUniqueInput
}

/**
 * DialogueTransition findFirst
 */
export type DialogueTransitionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueTransition
   */
  select?: Prisma.DialogueTransitionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueTransition
   */
  omit?: Prisma.DialogueTransitionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueTransitionInclude<ExtArgs> | null
  /**
   * Filter, which DialogueTransition to fetch.
   */
  where?: Prisma.DialogueTransitionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DialogueTransitions to fetch.
   */
  orderBy?: Prisma.DialogueTransitionOrderByWithRelationInput | Prisma.DialogueTransitionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DialogueTransitions.
   */
  cursor?: Prisma.DialogueTransitionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DialogueTransitions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DialogueTransitions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DialogueTransitions.
   */
  distinct?: Prisma.DialogueTransitionScalarFieldEnum | Prisma.DialogueTransitionScalarFieldEnum[]
}

/**
 * DialogueTransition findFirstOrThrow
 */
export type DialogueTransitionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueTransition
   */
  select?: Prisma.DialogueTransitionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueTransition
   */
  omit?: Prisma.DialogueTransitionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueTransitionInclude<ExtArgs> | null
  /**
   * Filter, which DialogueTransition to fetch.
   */
  where?: Prisma.DialogueTransitionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DialogueTransitions to fetch.
   */
  orderBy?: Prisma.DialogueTransitionOrderByWithRelationInput | Prisma.DialogueTransitionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DialogueTransitions.
   */
  cursor?: Prisma.DialogueTransitionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DialogueTransitions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DialogueTransitions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DialogueTransitions.
   */
  distinct?: Prisma.DialogueTransitionScalarFieldEnum | Prisma.DialogueTransitionScalarFieldEnum[]
}

/**
 * DialogueTransition findMany
 */
export type DialogueTransitionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueTransition
   */
  select?: Prisma.DialogueTransitionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueTransition
   */
  omit?: Prisma.DialogueTransitionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueTransitionInclude<ExtArgs> | null
  /**
   * Filter, which DialogueTransitions to fetch.
   */
  where?: Prisma.DialogueTransitionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DialogueTransitions to fetch.
   */
  orderBy?: Prisma.DialogueTransitionOrderByWithRelationInput | Prisma.DialogueTransitionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DialogueTransitions.
   */
  cursor?: Prisma.DialogueTransitionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DialogueTransitions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DialogueTransitions.
   */
  skip?: number
  distinct?: Prisma.DialogueTransitionScalarFieldEnum | Prisma.DialogueTransitionScalarFieldEnum[]
}

/**
 * DialogueTransition create
 */
export type DialogueTransitionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueTransition
   */
  select?: Prisma.DialogueTransitionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueTransition
   */
  omit?: Prisma.DialogueTransitionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueTransitionInclude<ExtArgs> | null
  /**
   * The data needed to create a DialogueTransition.
   */
  data: Prisma.XOR<Prisma.DialogueTransitionCreateInput, Prisma.DialogueTransitionUncheckedCreateInput>
}

/**
 * DialogueTransition createMany
 */
export type DialogueTransitionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DialogueTransitions.
   */
  data: Prisma.DialogueTransitionCreateManyInput | Prisma.DialogueTransitionCreateManyInput[]
}

/**
 * DialogueTransition createManyAndReturn
 */
export type DialogueTransitionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueTransition
   */
  select?: Prisma.DialogueTransitionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueTransition
   */
  omit?: Prisma.DialogueTransitionOmit<ExtArgs> | null
  /**
   * The data used to create many DialogueTransitions.
   */
  data: Prisma.DialogueTransitionCreateManyInput | Prisma.DialogueTransitionCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueTransitionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * DialogueTransition update
 */
export type DialogueTransitionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueTransition
   */
  select?: Prisma.DialogueTransitionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueTransition
   */
  omit?: Prisma.DialogueTransitionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueTransitionInclude<ExtArgs> | null
  /**
   * The data needed to update a DialogueTransition.
   */
  data: Prisma.XOR<Prisma.DialogueTransitionUpdateInput, Prisma.DialogueTransitionUncheckedUpdateInput>
  /**
   * Choose, which DialogueTransition to update.
   */
  where: Prisma.DialogueTransitionWhereUniqueInput
}

/**
 * DialogueTransition updateMany
 */
export type DialogueTransitionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DialogueTransitions.
   */
  data: Prisma.XOR<Prisma.DialogueTransitionUpdateManyMutationInput, Prisma.DialogueTransitionUncheckedUpdateManyInput>
  /**
   * Filter which DialogueTransitions to update
   */
  where?: Prisma.DialogueTransitionWhereInput
  /**
   * Limit how many DialogueTransitions to update.
   */
  limit?: number
}

/**
 * DialogueTransition updateManyAndReturn
 */
export type DialogueTransitionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueTransition
   */
  select?: Prisma.DialogueTransitionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueTransition
   */
  omit?: Prisma.DialogueTransitionOmit<ExtArgs> | null
  /**
   * The data used to update DialogueTransitions.
   */
  data: Prisma.XOR<Prisma.DialogueTransitionUpdateManyMutationInput, Prisma.DialogueTransitionUncheckedUpdateManyInput>
  /**
   * Filter which DialogueTransitions to update
   */
  where?: Prisma.DialogueTransitionWhereInput
  /**
   * Limit how many DialogueTransitions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueTransitionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * DialogueTransition upsert
 */
export type DialogueTransitionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueTransition
   */
  select?: Prisma.DialogueTransitionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueTransition
   */
  omit?: Prisma.DialogueTransitionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueTransitionInclude<ExtArgs> | null
  /**
   * The filter to search for the DialogueTransition to update in case it exists.
   */
  where: Prisma.DialogueTransitionWhereUniqueInput
  /**
   * In case the DialogueTransition found by the `where` argument doesn't exist, create a new DialogueTransition with this data.
   */
  create: Prisma.XOR<Prisma.DialogueTransitionCreateInput, Prisma.DialogueTransitionUncheckedCreateInput>
  /**
   * In case the DialogueTransition was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DialogueTransitionUpdateInput, Prisma.DialogueTransitionUncheckedUpdateInput>
}

/**
 * DialogueTransition delete
 */
export type DialogueTransitionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueTransition
   */
  select?: Prisma.DialogueTransitionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueTransition
   */
  omit?: Prisma.DialogueTransitionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueTransitionInclude<ExtArgs> | null
  /**
   * Filter which DialogueTransition to delete.
   */
  where: Prisma.DialogueTransitionWhereUniqueInput
}

/**
 * DialogueTransition deleteMany
 */
export type DialogueTransitionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DialogueTransitions to delete
   */
  where?: Prisma.DialogueTransitionWhereInput
  /**
   * Limit how many DialogueTransitions to delete.
   */
  limit?: number
}

/**
 * DialogueTransition.toStage
 */
export type DialogueTransition$toStageArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueStage
   */
  select?: Prisma.DialogueStageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueStage
   */
  omit?: Prisma.DialogueStageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueStageInclude<ExtArgs> | null
  where?: Prisma.DialogueStageWhereInput
}

/**
 * DialogueTransition without action
 */
export type DialogueTransitionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueTransition
   */
  select?: Prisma.DialogueTransitionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueTransition
   */
  omit?: Prisma.DialogueTransitionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueTransitionInclude<ExtArgs> | null
}
