
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `LearningDailyStat` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model LearningDailyStat
 * 
 */
export type LearningDailyStatModel = runtime.Types.Result.DefaultSelection<Prisma.$LearningDailyStatPayload>

export type AggregateLearningDailyStat = {
  _count: LearningDailyStatCountAggregateOutputType | null
  _avg: LearningDailyStatAvgAggregateOutputType | null
  _sum: LearningDailyStatSumAggregateOutputType | null
  _min: LearningDailyStatMinAggregateOutputType | null
  _max: LearningDailyStatMaxAggregateOutputType | null
}

export type LearningDailyStatAvgAggregateOutputType = {
  studySeconds: number | null
  audioSeconds: number | null
  dictationSeconds: number | null
}

export type LearningDailyStatSumAggregateOutputType = {
  studySeconds: number | null
  audioSeconds: number | null
  dictationSeconds: number | null
}

export type LearningDailyStatMinAggregateOutputType = {
  id: string | null
  userId: string | null
  dateKey: string | null
  studySeconds: number | null
  audioSeconds: number | null
  dictationSeconds: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type LearningDailyStatMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  dateKey: string | null
  studySeconds: number | null
  audioSeconds: number | null
  dictationSeconds: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type LearningDailyStatCountAggregateOutputType = {
  id: number
  userId: number
  dateKey: number
  studySeconds: number
  audioSeconds: number
  dictationSeconds: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type LearningDailyStatAvgAggregateInputType = {
  studySeconds?: true
  audioSeconds?: true
  dictationSeconds?: true
}

export type LearningDailyStatSumAggregateInputType = {
  studySeconds?: true
  audioSeconds?: true
  dictationSeconds?: true
}

export type LearningDailyStatMinAggregateInputType = {
  id?: true
  userId?: true
  dateKey?: true
  studySeconds?: true
  audioSeconds?: true
  dictationSeconds?: true
  createdAt?: true
  updatedAt?: true
}

export type LearningDailyStatMaxAggregateInputType = {
  id?: true
  userId?: true
  dateKey?: true
  studySeconds?: true
  audioSeconds?: true
  dictationSeconds?: true
  createdAt?: true
  updatedAt?: true
}

export type LearningDailyStatCountAggregateInputType = {
  id?: true
  userId?: true
  dateKey?: true
  studySeconds?: true
  audioSeconds?: true
  dictationSeconds?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type LearningDailyStatAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LearningDailyStat to aggregate.
   */
  where?: Prisma.LearningDailyStatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LearningDailyStats to fetch.
   */
  orderBy?: Prisma.LearningDailyStatOrderByWithRelationInput | Prisma.LearningDailyStatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LearningDailyStatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LearningDailyStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LearningDailyStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned LearningDailyStats
  **/
  _count?: true | LearningDailyStatCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: LearningDailyStatAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: LearningDailyStatSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LearningDailyStatMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LearningDailyStatMaxAggregateInputType
}

export type GetLearningDailyStatAggregateType<T extends LearningDailyStatAggregateArgs> = {
      [P in keyof T & keyof AggregateLearningDailyStat]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLearningDailyStat[P]>
    : Prisma.GetScalarType<T[P], AggregateLearningDailyStat[P]>
}




export type LearningDailyStatGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LearningDailyStatWhereInput
  orderBy?: Prisma.LearningDailyStatOrderByWithAggregationInput | Prisma.LearningDailyStatOrderByWithAggregationInput[]
  by: Prisma.LearningDailyStatScalarFieldEnum[] | Prisma.LearningDailyStatScalarFieldEnum
  having?: Prisma.LearningDailyStatScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LearningDailyStatCountAggregateInputType | true
  _avg?: LearningDailyStatAvgAggregateInputType
  _sum?: LearningDailyStatSumAggregateInputType
  _min?: LearningDailyStatMinAggregateInputType
  _max?: LearningDailyStatMaxAggregateInputType
}

export type LearningDailyStatGroupByOutputType = {
  id: string
  userId: string
  dateKey: string
  studySeconds: number
  audioSeconds: number
  dictationSeconds: number
  createdAt: Date
  updatedAt: Date
  _count: LearningDailyStatCountAggregateOutputType | null
  _avg: LearningDailyStatAvgAggregateOutputType | null
  _sum: LearningDailyStatSumAggregateOutputType | null
  _min: LearningDailyStatMinAggregateOutputType | null
  _max: LearningDailyStatMaxAggregateOutputType | null
}

type GetLearningDailyStatGroupByPayload<T extends LearningDailyStatGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LearningDailyStatGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LearningDailyStatGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LearningDailyStatGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LearningDailyStatGroupByOutputType[P]>
      }
    >
  >



export type LearningDailyStatWhereInput = {
  AND?: Prisma.LearningDailyStatWhereInput | Prisma.LearningDailyStatWhereInput[]
  OR?: Prisma.LearningDailyStatWhereInput[]
  NOT?: Prisma.LearningDailyStatWhereInput | Prisma.LearningDailyStatWhereInput[]
  id?: Prisma.StringFilter<"LearningDailyStat"> | string
  userId?: Prisma.StringFilter<"LearningDailyStat"> | string
  dateKey?: Prisma.StringFilter<"LearningDailyStat"> | string
  studySeconds?: Prisma.IntFilter<"LearningDailyStat"> | number
  audioSeconds?: Prisma.IntFilter<"LearningDailyStat"> | number
  dictationSeconds?: Prisma.IntFilter<"LearningDailyStat"> | number
  createdAt?: Prisma.DateTimeFilter<"LearningDailyStat"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"LearningDailyStat"> | Date | string
}

export type LearningDailyStatOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  dateKey?: Prisma.SortOrder
  studySeconds?: Prisma.SortOrder
  audioSeconds?: Prisma.SortOrder
  dictationSeconds?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LearningDailyStatWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId_dateKey?: Prisma.LearningDailyStatUserIdDateKeyCompoundUniqueInput
  AND?: Prisma.LearningDailyStatWhereInput | Prisma.LearningDailyStatWhereInput[]
  OR?: Prisma.LearningDailyStatWhereInput[]
  NOT?: Prisma.LearningDailyStatWhereInput | Prisma.LearningDailyStatWhereInput[]
  userId?: Prisma.StringFilter<"LearningDailyStat"> | string
  dateKey?: Prisma.StringFilter<"LearningDailyStat"> | string
  studySeconds?: Prisma.IntFilter<"LearningDailyStat"> | number
  audioSeconds?: Prisma.IntFilter<"LearningDailyStat"> | number
  dictationSeconds?: Prisma.IntFilter<"LearningDailyStat"> | number
  createdAt?: Prisma.DateTimeFilter<"LearningDailyStat"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"LearningDailyStat"> | Date | string
}, "id" | "userId_dateKey">

export type LearningDailyStatOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  dateKey?: Prisma.SortOrder
  studySeconds?: Prisma.SortOrder
  audioSeconds?: Prisma.SortOrder
  dictationSeconds?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.LearningDailyStatCountOrderByAggregateInput
  _avg?: Prisma.LearningDailyStatAvgOrderByAggregateInput
  _max?: Prisma.LearningDailyStatMaxOrderByAggregateInput
  _min?: Prisma.LearningDailyStatMinOrderByAggregateInput
  _sum?: Prisma.LearningDailyStatSumOrderByAggregateInput
}

export type LearningDailyStatScalarWhereWithAggregatesInput = {
  AND?: Prisma.LearningDailyStatScalarWhereWithAggregatesInput | Prisma.LearningDailyStatScalarWhereWithAggregatesInput[]
  OR?: Prisma.LearningDailyStatScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LearningDailyStatScalarWhereWithAggregatesInput | Prisma.LearningDailyStatScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"LearningDailyStat"> | string
  userId?: Prisma.StringWithAggregatesFilter<"LearningDailyStat"> | string
  dateKey?: Prisma.StringWithAggregatesFilter<"LearningDailyStat"> | string
  studySeconds?: Prisma.IntWithAggregatesFilter<"LearningDailyStat"> | number
  audioSeconds?: Prisma.IntWithAggregatesFilter<"LearningDailyStat"> | number
  dictationSeconds?: Prisma.IntWithAggregatesFilter<"LearningDailyStat"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"LearningDailyStat"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"LearningDailyStat"> | Date | string
}

export type LearningDailyStatCreateInput = {
  id?: string
  userId?: string
  dateKey: string
  studySeconds?: number
  audioSeconds?: number
  dictationSeconds?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LearningDailyStatUncheckedCreateInput = {
  id?: string
  userId?: string
  dateKey: string
  studySeconds?: number
  audioSeconds?: number
  dictationSeconds?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LearningDailyStatUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  dateKey?: Prisma.StringFieldUpdateOperationsInput | string
  studySeconds?: Prisma.IntFieldUpdateOperationsInput | number
  audioSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  dictationSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LearningDailyStatUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  dateKey?: Prisma.StringFieldUpdateOperationsInput | string
  studySeconds?: Prisma.IntFieldUpdateOperationsInput | number
  audioSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  dictationSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LearningDailyStatCreateManyInput = {
  id?: string
  userId?: string
  dateKey: string
  studySeconds?: number
  audioSeconds?: number
  dictationSeconds?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LearningDailyStatUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  dateKey?: Prisma.StringFieldUpdateOperationsInput | string
  studySeconds?: Prisma.IntFieldUpdateOperationsInput | number
  audioSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  dictationSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LearningDailyStatUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  dateKey?: Prisma.StringFieldUpdateOperationsInput | string
  studySeconds?: Prisma.IntFieldUpdateOperationsInput | number
  audioSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  dictationSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LearningDailyStatUserIdDateKeyCompoundUniqueInput = {
  userId: string
  dateKey: string
}

export type LearningDailyStatCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  dateKey?: Prisma.SortOrder
  studySeconds?: Prisma.SortOrder
  audioSeconds?: Prisma.SortOrder
  dictationSeconds?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LearningDailyStatAvgOrderByAggregateInput = {
  studySeconds?: Prisma.SortOrder
  audioSeconds?: Prisma.SortOrder
  dictationSeconds?: Prisma.SortOrder
}

export type LearningDailyStatMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  dateKey?: Prisma.SortOrder
  studySeconds?: Prisma.SortOrder
  audioSeconds?: Prisma.SortOrder
  dictationSeconds?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LearningDailyStatMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  dateKey?: Prisma.SortOrder
  studySeconds?: Prisma.SortOrder
  audioSeconds?: Prisma.SortOrder
  dictationSeconds?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LearningDailyStatSumOrderByAggregateInput = {
  studySeconds?: Prisma.SortOrder
  audioSeconds?: Prisma.SortOrder
  dictationSeconds?: Prisma.SortOrder
}



export type LearningDailyStatSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  dateKey?: boolean
  studySeconds?: boolean
  audioSeconds?: boolean
  dictationSeconds?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["learningDailyStat"]>

export type LearningDailyStatSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  dateKey?: boolean
  studySeconds?: boolean
  audioSeconds?: boolean
  dictationSeconds?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["learningDailyStat"]>

export type LearningDailyStatSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  dateKey?: boolean
  studySeconds?: boolean
  audioSeconds?: boolean
  dictationSeconds?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["learningDailyStat"]>

export type LearningDailyStatSelectScalar = {
  id?: boolean
  userId?: boolean
  dateKey?: boolean
  studySeconds?: boolean
  audioSeconds?: boolean
  dictationSeconds?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type LearningDailyStatOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "dateKey" | "studySeconds" | "audioSeconds" | "dictationSeconds" | "createdAt" | "updatedAt", ExtArgs["result"]["learningDailyStat"]>

export type $LearningDailyStatPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "LearningDailyStat"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    dateKey: string
    studySeconds: number
    audioSeconds: number
    dictationSeconds: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["learningDailyStat"]>
  composites: {}
}

export type LearningDailyStatGetPayload<S extends boolean | null | undefined | LearningDailyStatDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LearningDailyStatPayload, S>

export type LearningDailyStatCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LearningDailyStatFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LearningDailyStatCountAggregateInputType | true
  }

export interface LearningDailyStatDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['LearningDailyStat'], meta: { name: 'LearningDailyStat' } }
  /**
   * Find zero or one LearningDailyStat that matches the filter.
   * @param {LearningDailyStatFindUniqueArgs} args - Arguments to find a LearningDailyStat
   * @example
   * // Get one LearningDailyStat
   * const learningDailyStat = await prisma.learningDailyStat.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LearningDailyStatFindUniqueArgs>(args: Prisma.SelectSubset<T, LearningDailyStatFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LearningDailyStatClient<runtime.Types.Result.GetResult<Prisma.$LearningDailyStatPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one LearningDailyStat that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LearningDailyStatFindUniqueOrThrowArgs} args - Arguments to find a LearningDailyStat
   * @example
   * // Get one LearningDailyStat
   * const learningDailyStat = await prisma.learningDailyStat.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LearningDailyStatFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LearningDailyStatFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LearningDailyStatClient<runtime.Types.Result.GetResult<Prisma.$LearningDailyStatPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LearningDailyStat that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LearningDailyStatFindFirstArgs} args - Arguments to find a LearningDailyStat
   * @example
   * // Get one LearningDailyStat
   * const learningDailyStat = await prisma.learningDailyStat.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LearningDailyStatFindFirstArgs>(args?: Prisma.SelectSubset<T, LearningDailyStatFindFirstArgs<ExtArgs>>): Prisma.Prisma__LearningDailyStatClient<runtime.Types.Result.GetResult<Prisma.$LearningDailyStatPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LearningDailyStat that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LearningDailyStatFindFirstOrThrowArgs} args - Arguments to find a LearningDailyStat
   * @example
   * // Get one LearningDailyStat
   * const learningDailyStat = await prisma.learningDailyStat.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LearningDailyStatFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LearningDailyStatFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LearningDailyStatClient<runtime.Types.Result.GetResult<Prisma.$LearningDailyStatPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more LearningDailyStats that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LearningDailyStatFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all LearningDailyStats
   * const learningDailyStats = await prisma.learningDailyStat.findMany()
   * 
   * // Get first 10 LearningDailyStats
   * const learningDailyStats = await prisma.learningDailyStat.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const learningDailyStatWithIdOnly = await prisma.learningDailyStat.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LearningDailyStatFindManyArgs>(args?: Prisma.SelectSubset<T, LearningDailyStatFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LearningDailyStatPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a LearningDailyStat.
   * @param {LearningDailyStatCreateArgs} args - Arguments to create a LearningDailyStat.
   * @example
   * // Create one LearningDailyStat
   * const LearningDailyStat = await prisma.learningDailyStat.create({
   *   data: {
   *     // ... data to create a LearningDailyStat
   *   }
   * })
   * 
   */
  create<T extends LearningDailyStatCreateArgs>(args: Prisma.SelectSubset<T, LearningDailyStatCreateArgs<ExtArgs>>): Prisma.Prisma__LearningDailyStatClient<runtime.Types.Result.GetResult<Prisma.$LearningDailyStatPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many LearningDailyStats.
   * @param {LearningDailyStatCreateManyArgs} args - Arguments to create many LearningDailyStats.
   * @example
   * // Create many LearningDailyStats
   * const learningDailyStat = await prisma.learningDailyStat.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LearningDailyStatCreateManyArgs>(args?: Prisma.SelectSubset<T, LearningDailyStatCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many LearningDailyStats and returns the data saved in the database.
   * @param {LearningDailyStatCreateManyAndReturnArgs} args - Arguments to create many LearningDailyStats.
   * @example
   * // Create many LearningDailyStats
   * const learningDailyStat = await prisma.learningDailyStat.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many LearningDailyStats and only return the `id`
   * const learningDailyStatWithIdOnly = await prisma.learningDailyStat.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LearningDailyStatCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LearningDailyStatCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LearningDailyStatPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a LearningDailyStat.
   * @param {LearningDailyStatDeleteArgs} args - Arguments to delete one LearningDailyStat.
   * @example
   * // Delete one LearningDailyStat
   * const LearningDailyStat = await prisma.learningDailyStat.delete({
   *   where: {
   *     // ... filter to delete one LearningDailyStat
   *   }
   * })
   * 
   */
  delete<T extends LearningDailyStatDeleteArgs>(args: Prisma.SelectSubset<T, LearningDailyStatDeleteArgs<ExtArgs>>): Prisma.Prisma__LearningDailyStatClient<runtime.Types.Result.GetResult<Prisma.$LearningDailyStatPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one LearningDailyStat.
   * @param {LearningDailyStatUpdateArgs} args - Arguments to update one LearningDailyStat.
   * @example
   * // Update one LearningDailyStat
   * const learningDailyStat = await prisma.learningDailyStat.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LearningDailyStatUpdateArgs>(args: Prisma.SelectSubset<T, LearningDailyStatUpdateArgs<ExtArgs>>): Prisma.Prisma__LearningDailyStatClient<runtime.Types.Result.GetResult<Prisma.$LearningDailyStatPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more LearningDailyStats.
   * @param {LearningDailyStatDeleteManyArgs} args - Arguments to filter LearningDailyStats to delete.
   * @example
   * // Delete a few LearningDailyStats
   * const { count } = await prisma.learningDailyStat.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LearningDailyStatDeleteManyArgs>(args?: Prisma.SelectSubset<T, LearningDailyStatDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LearningDailyStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LearningDailyStatUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many LearningDailyStats
   * const learningDailyStat = await prisma.learningDailyStat.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LearningDailyStatUpdateManyArgs>(args: Prisma.SelectSubset<T, LearningDailyStatUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LearningDailyStats and returns the data updated in the database.
   * @param {LearningDailyStatUpdateManyAndReturnArgs} args - Arguments to update many LearningDailyStats.
   * @example
   * // Update many LearningDailyStats
   * const learningDailyStat = await prisma.learningDailyStat.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more LearningDailyStats and only return the `id`
   * const learningDailyStatWithIdOnly = await prisma.learningDailyStat.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LearningDailyStatUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LearningDailyStatUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LearningDailyStatPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one LearningDailyStat.
   * @param {LearningDailyStatUpsertArgs} args - Arguments to update or create a LearningDailyStat.
   * @example
   * // Update or create a LearningDailyStat
   * const learningDailyStat = await prisma.learningDailyStat.upsert({
   *   create: {
   *     // ... data to create a LearningDailyStat
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the LearningDailyStat we want to update
   *   }
   * })
   */
  upsert<T extends LearningDailyStatUpsertArgs>(args: Prisma.SelectSubset<T, LearningDailyStatUpsertArgs<ExtArgs>>): Prisma.Prisma__LearningDailyStatClient<runtime.Types.Result.GetResult<Prisma.$LearningDailyStatPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of LearningDailyStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LearningDailyStatCountArgs} args - Arguments to filter LearningDailyStats to count.
   * @example
   * // Count the number of LearningDailyStats
   * const count = await prisma.learningDailyStat.count({
   *   where: {
   *     // ... the filter for the LearningDailyStats we want to count
   *   }
   * })
  **/
  count<T extends LearningDailyStatCountArgs>(
    args?: Prisma.Subset<T, LearningDailyStatCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LearningDailyStatCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a LearningDailyStat.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LearningDailyStatAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LearningDailyStatAggregateArgs>(args: Prisma.Subset<T, LearningDailyStatAggregateArgs>): Prisma.PrismaPromise<GetLearningDailyStatAggregateType<T>>

  /**
   * Group by LearningDailyStat.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LearningDailyStatGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LearningDailyStatGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LearningDailyStatGroupByArgs['orderBy'] }
      : { orderBy?: LearningDailyStatGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LearningDailyStatGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLearningDailyStatGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the LearningDailyStat model
 */
readonly fields: LearningDailyStatFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for LearningDailyStat.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LearningDailyStatClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the LearningDailyStat model
 */
export interface LearningDailyStatFieldRefs {
  readonly id: Prisma.FieldRef<"LearningDailyStat", 'String'>
  readonly userId: Prisma.FieldRef<"LearningDailyStat", 'String'>
  readonly dateKey: Prisma.FieldRef<"LearningDailyStat", 'String'>
  readonly studySeconds: Prisma.FieldRef<"LearningDailyStat", 'Int'>
  readonly audioSeconds: Prisma.FieldRef<"LearningDailyStat", 'Int'>
  readonly dictationSeconds: Prisma.FieldRef<"LearningDailyStat", 'Int'>
  readonly createdAt: Prisma.FieldRef<"LearningDailyStat", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"LearningDailyStat", 'DateTime'>
}
    

// Custom InputTypes
/**
 * LearningDailyStat findUnique
 */
export type LearningDailyStatFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LearningDailyStat
   */
  select?: Prisma.LearningDailyStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LearningDailyStat
   */
  omit?: Prisma.LearningDailyStatOmit<ExtArgs> | null
  /**
   * Filter, which LearningDailyStat to fetch.
   */
  where: Prisma.LearningDailyStatWhereUniqueInput
}

/**
 * LearningDailyStat findUniqueOrThrow
 */
export type LearningDailyStatFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LearningDailyStat
   */
  select?: Prisma.LearningDailyStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LearningDailyStat
   */
  omit?: Prisma.LearningDailyStatOmit<ExtArgs> | null
  /**
   * Filter, which LearningDailyStat to fetch.
   */
  where: Prisma.LearningDailyStatWhereUniqueInput
}

/**
 * LearningDailyStat findFirst
 */
export type LearningDailyStatFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LearningDailyStat
   */
  select?: Prisma.LearningDailyStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LearningDailyStat
   */
  omit?: Prisma.LearningDailyStatOmit<ExtArgs> | null
  /**
   * Filter, which LearningDailyStat to fetch.
   */
  where?: Prisma.LearningDailyStatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LearningDailyStats to fetch.
   */
  orderBy?: Prisma.LearningDailyStatOrderByWithRelationInput | Prisma.LearningDailyStatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LearningDailyStats.
   */
  cursor?: Prisma.LearningDailyStatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LearningDailyStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LearningDailyStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LearningDailyStats.
   */
  distinct?: Prisma.LearningDailyStatScalarFieldEnum | Prisma.LearningDailyStatScalarFieldEnum[]
}

/**
 * LearningDailyStat findFirstOrThrow
 */
export type LearningDailyStatFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LearningDailyStat
   */
  select?: Prisma.LearningDailyStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LearningDailyStat
   */
  omit?: Prisma.LearningDailyStatOmit<ExtArgs> | null
  /**
   * Filter, which LearningDailyStat to fetch.
   */
  where?: Prisma.LearningDailyStatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LearningDailyStats to fetch.
   */
  orderBy?: Prisma.LearningDailyStatOrderByWithRelationInput | Prisma.LearningDailyStatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LearningDailyStats.
   */
  cursor?: Prisma.LearningDailyStatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LearningDailyStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LearningDailyStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LearningDailyStats.
   */
  distinct?: Prisma.LearningDailyStatScalarFieldEnum | Prisma.LearningDailyStatScalarFieldEnum[]
}

/**
 * LearningDailyStat findMany
 */
export type LearningDailyStatFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LearningDailyStat
   */
  select?: Prisma.LearningDailyStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LearningDailyStat
   */
  omit?: Prisma.LearningDailyStatOmit<ExtArgs> | null
  /**
   * Filter, which LearningDailyStats to fetch.
   */
  where?: Prisma.LearningDailyStatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LearningDailyStats to fetch.
   */
  orderBy?: Prisma.LearningDailyStatOrderByWithRelationInput | Prisma.LearningDailyStatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing LearningDailyStats.
   */
  cursor?: Prisma.LearningDailyStatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LearningDailyStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LearningDailyStats.
   */
  skip?: number
  distinct?: Prisma.LearningDailyStatScalarFieldEnum | Prisma.LearningDailyStatScalarFieldEnum[]
}

/**
 * LearningDailyStat create
 */
export type LearningDailyStatCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LearningDailyStat
   */
  select?: Prisma.LearningDailyStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LearningDailyStat
   */
  omit?: Prisma.LearningDailyStatOmit<ExtArgs> | null
  /**
   * The data needed to create a LearningDailyStat.
   */
  data: Prisma.XOR<Prisma.LearningDailyStatCreateInput, Prisma.LearningDailyStatUncheckedCreateInput>
}

/**
 * LearningDailyStat createMany
 */
export type LearningDailyStatCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many LearningDailyStats.
   */
  data: Prisma.LearningDailyStatCreateManyInput | Prisma.LearningDailyStatCreateManyInput[]
}

/**
 * LearningDailyStat createManyAndReturn
 */
export type LearningDailyStatCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LearningDailyStat
   */
  select?: Prisma.LearningDailyStatSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LearningDailyStat
   */
  omit?: Prisma.LearningDailyStatOmit<ExtArgs> | null
  /**
   * The data used to create many LearningDailyStats.
   */
  data: Prisma.LearningDailyStatCreateManyInput | Prisma.LearningDailyStatCreateManyInput[]
}

/**
 * LearningDailyStat update
 */
export type LearningDailyStatUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LearningDailyStat
   */
  select?: Prisma.LearningDailyStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LearningDailyStat
   */
  omit?: Prisma.LearningDailyStatOmit<ExtArgs> | null
  /**
   * The data needed to update a LearningDailyStat.
   */
  data: Prisma.XOR<Prisma.LearningDailyStatUpdateInput, Prisma.LearningDailyStatUncheckedUpdateInput>
  /**
   * Choose, which LearningDailyStat to update.
   */
  where: Prisma.LearningDailyStatWhereUniqueInput
}

/**
 * LearningDailyStat updateMany
 */
export type LearningDailyStatUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update LearningDailyStats.
   */
  data: Prisma.XOR<Prisma.LearningDailyStatUpdateManyMutationInput, Prisma.LearningDailyStatUncheckedUpdateManyInput>
  /**
   * Filter which LearningDailyStats to update
   */
  where?: Prisma.LearningDailyStatWhereInput
  /**
   * Limit how many LearningDailyStats to update.
   */
  limit?: number
}

/**
 * LearningDailyStat updateManyAndReturn
 */
export type LearningDailyStatUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LearningDailyStat
   */
  select?: Prisma.LearningDailyStatSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LearningDailyStat
   */
  omit?: Prisma.LearningDailyStatOmit<ExtArgs> | null
  /**
   * The data used to update LearningDailyStats.
   */
  data: Prisma.XOR<Prisma.LearningDailyStatUpdateManyMutationInput, Prisma.LearningDailyStatUncheckedUpdateManyInput>
  /**
   * Filter which LearningDailyStats to update
   */
  where?: Prisma.LearningDailyStatWhereInput
  /**
   * Limit how many LearningDailyStats to update.
   */
  limit?: number
}

/**
 * LearningDailyStat upsert
 */
export type LearningDailyStatUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LearningDailyStat
   */
  select?: Prisma.LearningDailyStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LearningDailyStat
   */
  omit?: Prisma.LearningDailyStatOmit<ExtArgs> | null
  /**
   * The filter to search for the LearningDailyStat to update in case it exists.
   */
  where: Prisma.LearningDailyStatWhereUniqueInput
  /**
   * In case the LearningDailyStat found by the `where` argument doesn't exist, create a new LearningDailyStat with this data.
   */
  create: Prisma.XOR<Prisma.LearningDailyStatCreateInput, Prisma.LearningDailyStatUncheckedCreateInput>
  /**
   * In case the LearningDailyStat was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LearningDailyStatUpdateInput, Prisma.LearningDailyStatUncheckedUpdateInput>
}

/**
 * LearningDailyStat delete
 */
export type LearningDailyStatDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LearningDailyStat
   */
  select?: Prisma.LearningDailyStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LearningDailyStat
   */
  omit?: Prisma.LearningDailyStatOmit<ExtArgs> | null
  /**
   * Filter which LearningDailyStat to delete.
   */
  where: Prisma.LearningDailyStatWhereUniqueInput
}

/**
 * LearningDailyStat deleteMany
 */
export type LearningDailyStatDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LearningDailyStats to delete
   */
  where?: Prisma.LearningDailyStatWhereInput
  /**
   * Limit how many LearningDailyStats to delete.
   */
  limit?: number
}

/**
 * LearningDailyStat without action
 */
export type LearningDailyStatDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LearningDailyStat
   */
  select?: Prisma.LearningDailyStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LearningDailyStat
   */
  omit?: Prisma.LearningDailyStatOmit<ExtArgs> | null
}
