
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `VideoTrainingItem` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model VideoTrainingItem
 * 
 */
export type VideoTrainingItemModel = runtime.Types.Result.DefaultSelection<Prisma.$VideoTrainingItemPayload>

export type AggregateVideoTrainingItem = {
  _count: VideoTrainingItemCountAggregateOutputType | null
  _min: VideoTrainingItemMinAggregateOutputType | null
  _max: VideoTrainingItemMaxAggregateOutputType | null
}

export type VideoTrainingItemMinAggregateOutputType = {
  id: string | null
  title: string | null
  sourceTitle: string | null
  plotSummary: string | null
  tag: string | null
  mediaType: string | null
  mediaUrl: string | null
  coverUrl: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type VideoTrainingItemMaxAggregateOutputType = {
  id: string | null
  title: string | null
  sourceTitle: string | null
  plotSummary: string | null
  tag: string | null
  mediaType: string | null
  mediaUrl: string | null
  coverUrl: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type VideoTrainingItemCountAggregateOutputType = {
  id: number
  title: number
  sourceTitle: number
  plotSummary: number
  tag: number
  mediaType: number
  mediaUrl: number
  coverUrl: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type VideoTrainingItemMinAggregateInputType = {
  id?: true
  title?: true
  sourceTitle?: true
  plotSummary?: true
  tag?: true
  mediaType?: true
  mediaUrl?: true
  coverUrl?: true
  createdAt?: true
  updatedAt?: true
}

export type VideoTrainingItemMaxAggregateInputType = {
  id?: true
  title?: true
  sourceTitle?: true
  plotSummary?: true
  tag?: true
  mediaType?: true
  mediaUrl?: true
  coverUrl?: true
  createdAt?: true
  updatedAt?: true
}

export type VideoTrainingItemCountAggregateInputType = {
  id?: true
  title?: true
  sourceTitle?: true
  plotSummary?: true
  tag?: true
  mediaType?: true
  mediaUrl?: true
  coverUrl?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type VideoTrainingItemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VideoTrainingItem to aggregate.
   */
  where?: Prisma.VideoTrainingItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VideoTrainingItems to fetch.
   */
  orderBy?: Prisma.VideoTrainingItemOrderByWithRelationInput | Prisma.VideoTrainingItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.VideoTrainingItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VideoTrainingItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VideoTrainingItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned VideoTrainingItems
  **/
  _count?: true | VideoTrainingItemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: VideoTrainingItemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: VideoTrainingItemMaxAggregateInputType
}

export type GetVideoTrainingItemAggregateType<T extends VideoTrainingItemAggregateArgs> = {
      [P in keyof T & keyof AggregateVideoTrainingItem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateVideoTrainingItem[P]>
    : Prisma.GetScalarType<T[P], AggregateVideoTrainingItem[P]>
}




export type VideoTrainingItemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VideoTrainingItemWhereInput
  orderBy?: Prisma.VideoTrainingItemOrderByWithAggregationInput | Prisma.VideoTrainingItemOrderByWithAggregationInput[]
  by: Prisma.VideoTrainingItemScalarFieldEnum[] | Prisma.VideoTrainingItemScalarFieldEnum
  having?: Prisma.VideoTrainingItemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: VideoTrainingItemCountAggregateInputType | true
  _min?: VideoTrainingItemMinAggregateInputType
  _max?: VideoTrainingItemMaxAggregateInputType
}

export type VideoTrainingItemGroupByOutputType = {
  id: string
  title: string
  sourceTitle: string
  plotSummary: string
  tag: string
  mediaType: string
  mediaUrl: string
  coverUrl: string | null
  createdAt: Date
  updatedAt: Date
  _count: VideoTrainingItemCountAggregateOutputType | null
  _min: VideoTrainingItemMinAggregateOutputType | null
  _max: VideoTrainingItemMaxAggregateOutputType | null
}

type GetVideoTrainingItemGroupByPayload<T extends VideoTrainingItemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<VideoTrainingItemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof VideoTrainingItemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], VideoTrainingItemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], VideoTrainingItemGroupByOutputType[P]>
      }
    >
  >



export type VideoTrainingItemWhereInput = {
  AND?: Prisma.VideoTrainingItemWhereInput | Prisma.VideoTrainingItemWhereInput[]
  OR?: Prisma.VideoTrainingItemWhereInput[]
  NOT?: Prisma.VideoTrainingItemWhereInput | Prisma.VideoTrainingItemWhereInput[]
  id?: Prisma.StringFilter<"VideoTrainingItem"> | string
  title?: Prisma.StringFilter<"VideoTrainingItem"> | string
  sourceTitle?: Prisma.StringFilter<"VideoTrainingItem"> | string
  plotSummary?: Prisma.StringFilter<"VideoTrainingItem"> | string
  tag?: Prisma.StringFilter<"VideoTrainingItem"> | string
  mediaType?: Prisma.StringFilter<"VideoTrainingItem"> | string
  mediaUrl?: Prisma.StringFilter<"VideoTrainingItem"> | string
  coverUrl?: Prisma.StringNullableFilter<"VideoTrainingItem"> | string | null
  createdAt?: Prisma.DateTimeFilter<"VideoTrainingItem"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"VideoTrainingItem"> | Date | string
  captions?: Prisma.VideoCaptionListRelationFilter
  characters?: Prisma.VideoCharacterListRelationFilter
  phraseNotes?: Prisma.VideoPhraseNoteListRelationFilter
}

export type VideoTrainingItemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  sourceTitle?: Prisma.SortOrder
  plotSummary?: Prisma.SortOrder
  tag?: Prisma.SortOrder
  mediaType?: Prisma.SortOrder
  mediaUrl?: Prisma.SortOrder
  coverUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  captions?: Prisma.VideoCaptionOrderByRelationAggregateInput
  characters?: Prisma.VideoCharacterOrderByRelationAggregateInput
  phraseNotes?: Prisma.VideoPhraseNoteOrderByRelationAggregateInput
}

export type VideoTrainingItemWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.VideoTrainingItemWhereInput | Prisma.VideoTrainingItemWhereInput[]
  OR?: Prisma.VideoTrainingItemWhereInput[]
  NOT?: Prisma.VideoTrainingItemWhereInput | Prisma.VideoTrainingItemWhereInput[]
  title?: Prisma.StringFilter<"VideoTrainingItem"> | string
  sourceTitle?: Prisma.StringFilter<"VideoTrainingItem"> | string
  plotSummary?: Prisma.StringFilter<"VideoTrainingItem"> | string
  tag?: Prisma.StringFilter<"VideoTrainingItem"> | string
  mediaType?: Prisma.StringFilter<"VideoTrainingItem"> | string
  mediaUrl?: Prisma.StringFilter<"VideoTrainingItem"> | string
  coverUrl?: Prisma.StringNullableFilter<"VideoTrainingItem"> | string | null
  createdAt?: Prisma.DateTimeFilter<"VideoTrainingItem"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"VideoTrainingItem"> | Date | string
  captions?: Prisma.VideoCaptionListRelationFilter
  characters?: Prisma.VideoCharacterListRelationFilter
  phraseNotes?: Prisma.VideoPhraseNoteListRelationFilter
}, "id">

export type VideoTrainingItemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  sourceTitle?: Prisma.SortOrder
  plotSummary?: Prisma.SortOrder
  tag?: Prisma.SortOrder
  mediaType?: Prisma.SortOrder
  mediaUrl?: Prisma.SortOrder
  coverUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.VideoTrainingItemCountOrderByAggregateInput
  _max?: Prisma.VideoTrainingItemMaxOrderByAggregateInput
  _min?: Prisma.VideoTrainingItemMinOrderByAggregateInput
}

export type VideoTrainingItemScalarWhereWithAggregatesInput = {
  AND?: Prisma.VideoTrainingItemScalarWhereWithAggregatesInput | Prisma.VideoTrainingItemScalarWhereWithAggregatesInput[]
  OR?: Prisma.VideoTrainingItemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.VideoTrainingItemScalarWhereWithAggregatesInput | Prisma.VideoTrainingItemScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"VideoTrainingItem"> | string
  title?: Prisma.StringWithAggregatesFilter<"VideoTrainingItem"> | string
  sourceTitle?: Prisma.StringWithAggregatesFilter<"VideoTrainingItem"> | string
  plotSummary?: Prisma.StringWithAggregatesFilter<"VideoTrainingItem"> | string
  tag?: Prisma.StringWithAggregatesFilter<"VideoTrainingItem"> | string
  mediaType?: Prisma.StringWithAggregatesFilter<"VideoTrainingItem"> | string
  mediaUrl?: Prisma.StringWithAggregatesFilter<"VideoTrainingItem"> | string
  coverUrl?: Prisma.StringNullableWithAggregatesFilter<"VideoTrainingItem"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"VideoTrainingItem"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"VideoTrainingItem"> | Date | string
}

export type VideoTrainingItemCreateInput = {
  id?: string
  title: string
  sourceTitle?: string
  plotSummary?: string
  tag: string
  mediaType?: string
  mediaUrl: string
  coverUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  captions?: Prisma.VideoCaptionCreateNestedManyWithoutVideoTrainingItemInput
  characters?: Prisma.VideoCharacterCreateNestedManyWithoutVideoTrainingItemInput
  phraseNotes?: Prisma.VideoPhraseNoteCreateNestedManyWithoutVideoTrainingItemInput
}

export type VideoTrainingItemUncheckedCreateInput = {
  id?: string
  title: string
  sourceTitle?: string
  plotSummary?: string
  tag: string
  mediaType?: string
  mediaUrl: string
  coverUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  captions?: Prisma.VideoCaptionUncheckedCreateNestedManyWithoutVideoTrainingItemInput
  characters?: Prisma.VideoCharacterUncheckedCreateNestedManyWithoutVideoTrainingItemInput
  phraseNotes?: Prisma.VideoPhraseNoteUncheckedCreateNestedManyWithoutVideoTrainingItemInput
}

export type VideoTrainingItemUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  sourceTitle?: Prisma.StringFieldUpdateOperationsInput | string
  plotSummary?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.StringFieldUpdateOperationsInput | string
  mediaType?: Prisma.StringFieldUpdateOperationsInput | string
  mediaUrl?: Prisma.StringFieldUpdateOperationsInput | string
  coverUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  captions?: Prisma.VideoCaptionUpdateManyWithoutVideoTrainingItemNestedInput
  characters?: Prisma.VideoCharacterUpdateManyWithoutVideoTrainingItemNestedInput
  phraseNotes?: Prisma.VideoPhraseNoteUpdateManyWithoutVideoTrainingItemNestedInput
}

export type VideoTrainingItemUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  sourceTitle?: Prisma.StringFieldUpdateOperationsInput | string
  plotSummary?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.StringFieldUpdateOperationsInput | string
  mediaType?: Prisma.StringFieldUpdateOperationsInput | string
  mediaUrl?: Prisma.StringFieldUpdateOperationsInput | string
  coverUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  captions?: Prisma.VideoCaptionUncheckedUpdateManyWithoutVideoTrainingItemNestedInput
  characters?: Prisma.VideoCharacterUncheckedUpdateManyWithoutVideoTrainingItemNestedInput
  phraseNotes?: Prisma.VideoPhraseNoteUncheckedUpdateManyWithoutVideoTrainingItemNestedInput
}

export type VideoTrainingItemCreateManyInput = {
  id?: string
  title: string
  sourceTitle?: string
  plotSummary?: string
  tag: string
  mediaType?: string
  mediaUrl: string
  coverUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type VideoTrainingItemUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  sourceTitle?: Prisma.StringFieldUpdateOperationsInput | string
  plotSummary?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.StringFieldUpdateOperationsInput | string
  mediaType?: Prisma.StringFieldUpdateOperationsInput | string
  mediaUrl?: Prisma.StringFieldUpdateOperationsInput | string
  coverUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VideoTrainingItemUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  sourceTitle?: Prisma.StringFieldUpdateOperationsInput | string
  plotSummary?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.StringFieldUpdateOperationsInput | string
  mediaType?: Prisma.StringFieldUpdateOperationsInput | string
  mediaUrl?: Prisma.StringFieldUpdateOperationsInput | string
  coverUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VideoTrainingItemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  sourceTitle?: Prisma.SortOrder
  plotSummary?: Prisma.SortOrder
  tag?: Prisma.SortOrder
  mediaType?: Prisma.SortOrder
  mediaUrl?: Prisma.SortOrder
  coverUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type VideoTrainingItemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  sourceTitle?: Prisma.SortOrder
  plotSummary?: Prisma.SortOrder
  tag?: Prisma.SortOrder
  mediaType?: Prisma.SortOrder
  mediaUrl?: Prisma.SortOrder
  coverUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type VideoTrainingItemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  sourceTitle?: Prisma.SortOrder
  plotSummary?: Prisma.SortOrder
  tag?: Prisma.SortOrder
  mediaType?: Prisma.SortOrder
  mediaUrl?: Prisma.SortOrder
  coverUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type VideoTrainingItemScalarRelationFilter = {
  is?: Prisma.VideoTrainingItemWhereInput
  isNot?: Prisma.VideoTrainingItemWhereInput
}

export type VideoTrainingItemCreateNestedOneWithoutCaptionsInput = {
  create?: Prisma.XOR<Prisma.VideoTrainingItemCreateWithoutCaptionsInput, Prisma.VideoTrainingItemUncheckedCreateWithoutCaptionsInput>
  connectOrCreate?: Prisma.VideoTrainingItemCreateOrConnectWithoutCaptionsInput
  connect?: Prisma.VideoTrainingItemWhereUniqueInput
}

export type VideoTrainingItemUpdateOneRequiredWithoutCaptionsNestedInput = {
  create?: Prisma.XOR<Prisma.VideoTrainingItemCreateWithoutCaptionsInput, Prisma.VideoTrainingItemUncheckedCreateWithoutCaptionsInput>
  connectOrCreate?: Prisma.VideoTrainingItemCreateOrConnectWithoutCaptionsInput
  upsert?: Prisma.VideoTrainingItemUpsertWithoutCaptionsInput
  connect?: Prisma.VideoTrainingItemWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.VideoTrainingItemUpdateToOneWithWhereWithoutCaptionsInput, Prisma.VideoTrainingItemUpdateWithoutCaptionsInput>, Prisma.VideoTrainingItemUncheckedUpdateWithoutCaptionsInput>
}

export type VideoTrainingItemCreateNestedOneWithoutCharactersInput = {
  create?: Prisma.XOR<Prisma.VideoTrainingItemCreateWithoutCharactersInput, Prisma.VideoTrainingItemUncheckedCreateWithoutCharactersInput>
  connectOrCreate?: Prisma.VideoTrainingItemCreateOrConnectWithoutCharactersInput
  connect?: Prisma.VideoTrainingItemWhereUniqueInput
}

export type VideoTrainingItemUpdateOneRequiredWithoutCharactersNestedInput = {
  create?: Prisma.XOR<Prisma.VideoTrainingItemCreateWithoutCharactersInput, Prisma.VideoTrainingItemUncheckedCreateWithoutCharactersInput>
  connectOrCreate?: Prisma.VideoTrainingItemCreateOrConnectWithoutCharactersInput
  upsert?: Prisma.VideoTrainingItemUpsertWithoutCharactersInput
  connect?: Prisma.VideoTrainingItemWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.VideoTrainingItemUpdateToOneWithWhereWithoutCharactersInput, Prisma.VideoTrainingItemUpdateWithoutCharactersInput>, Prisma.VideoTrainingItemUncheckedUpdateWithoutCharactersInput>
}

export type VideoTrainingItemCreateNestedOneWithoutPhraseNotesInput = {
  create?: Prisma.XOR<Prisma.VideoTrainingItemCreateWithoutPhraseNotesInput, Prisma.VideoTrainingItemUncheckedCreateWithoutPhraseNotesInput>
  connectOrCreate?: Prisma.VideoTrainingItemCreateOrConnectWithoutPhraseNotesInput
  connect?: Prisma.VideoTrainingItemWhereUniqueInput
}

export type VideoTrainingItemUpdateOneRequiredWithoutPhraseNotesNestedInput = {
  create?: Prisma.XOR<Prisma.VideoTrainingItemCreateWithoutPhraseNotesInput, Prisma.VideoTrainingItemUncheckedCreateWithoutPhraseNotesInput>
  connectOrCreate?: Prisma.VideoTrainingItemCreateOrConnectWithoutPhraseNotesInput
  upsert?: Prisma.VideoTrainingItemUpsertWithoutPhraseNotesInput
  connect?: Prisma.VideoTrainingItemWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.VideoTrainingItemUpdateToOneWithWhereWithoutPhraseNotesInput, Prisma.VideoTrainingItemUpdateWithoutPhraseNotesInput>, Prisma.VideoTrainingItemUncheckedUpdateWithoutPhraseNotesInput>
}

export type VideoTrainingItemCreateWithoutCaptionsInput = {
  id?: string
  title: string
  sourceTitle?: string
  plotSummary?: string
  tag: string
  mediaType?: string
  mediaUrl: string
  coverUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  characters?: Prisma.VideoCharacterCreateNestedManyWithoutVideoTrainingItemInput
  phraseNotes?: Prisma.VideoPhraseNoteCreateNestedManyWithoutVideoTrainingItemInput
}

export type VideoTrainingItemUncheckedCreateWithoutCaptionsInput = {
  id?: string
  title: string
  sourceTitle?: string
  plotSummary?: string
  tag: string
  mediaType?: string
  mediaUrl: string
  coverUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  characters?: Prisma.VideoCharacterUncheckedCreateNestedManyWithoutVideoTrainingItemInput
  phraseNotes?: Prisma.VideoPhraseNoteUncheckedCreateNestedManyWithoutVideoTrainingItemInput
}

export type VideoTrainingItemCreateOrConnectWithoutCaptionsInput = {
  where: Prisma.VideoTrainingItemWhereUniqueInput
  create: Prisma.XOR<Prisma.VideoTrainingItemCreateWithoutCaptionsInput, Prisma.VideoTrainingItemUncheckedCreateWithoutCaptionsInput>
}

export type VideoTrainingItemUpsertWithoutCaptionsInput = {
  update: Prisma.XOR<Prisma.VideoTrainingItemUpdateWithoutCaptionsInput, Prisma.VideoTrainingItemUncheckedUpdateWithoutCaptionsInput>
  create: Prisma.XOR<Prisma.VideoTrainingItemCreateWithoutCaptionsInput, Prisma.VideoTrainingItemUncheckedCreateWithoutCaptionsInput>
  where?: Prisma.VideoTrainingItemWhereInput
}

export type VideoTrainingItemUpdateToOneWithWhereWithoutCaptionsInput = {
  where?: Prisma.VideoTrainingItemWhereInput
  data: Prisma.XOR<Prisma.VideoTrainingItemUpdateWithoutCaptionsInput, Prisma.VideoTrainingItemUncheckedUpdateWithoutCaptionsInput>
}

export type VideoTrainingItemUpdateWithoutCaptionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  sourceTitle?: Prisma.StringFieldUpdateOperationsInput | string
  plotSummary?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.StringFieldUpdateOperationsInput | string
  mediaType?: Prisma.StringFieldUpdateOperationsInput | string
  mediaUrl?: Prisma.StringFieldUpdateOperationsInput | string
  coverUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  characters?: Prisma.VideoCharacterUpdateManyWithoutVideoTrainingItemNestedInput
  phraseNotes?: Prisma.VideoPhraseNoteUpdateManyWithoutVideoTrainingItemNestedInput
}

export type VideoTrainingItemUncheckedUpdateWithoutCaptionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  sourceTitle?: Prisma.StringFieldUpdateOperationsInput | string
  plotSummary?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.StringFieldUpdateOperationsInput | string
  mediaType?: Prisma.StringFieldUpdateOperationsInput | string
  mediaUrl?: Prisma.StringFieldUpdateOperationsInput | string
  coverUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  characters?: Prisma.VideoCharacterUncheckedUpdateManyWithoutVideoTrainingItemNestedInput
  phraseNotes?: Prisma.VideoPhraseNoteUncheckedUpdateManyWithoutVideoTrainingItemNestedInput
}

export type VideoTrainingItemCreateWithoutCharactersInput = {
  id?: string
  title: string
  sourceTitle?: string
  plotSummary?: string
  tag: string
  mediaType?: string
  mediaUrl: string
  coverUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  captions?: Prisma.VideoCaptionCreateNestedManyWithoutVideoTrainingItemInput
  phraseNotes?: Prisma.VideoPhraseNoteCreateNestedManyWithoutVideoTrainingItemInput
}

export type VideoTrainingItemUncheckedCreateWithoutCharactersInput = {
  id?: string
  title: string
  sourceTitle?: string
  plotSummary?: string
  tag: string
  mediaType?: string
  mediaUrl: string
  coverUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  captions?: Prisma.VideoCaptionUncheckedCreateNestedManyWithoutVideoTrainingItemInput
  phraseNotes?: Prisma.VideoPhraseNoteUncheckedCreateNestedManyWithoutVideoTrainingItemInput
}

export type VideoTrainingItemCreateOrConnectWithoutCharactersInput = {
  where: Prisma.VideoTrainingItemWhereUniqueInput
  create: Prisma.XOR<Prisma.VideoTrainingItemCreateWithoutCharactersInput, Prisma.VideoTrainingItemUncheckedCreateWithoutCharactersInput>
}

export type VideoTrainingItemUpsertWithoutCharactersInput = {
  update: Prisma.XOR<Prisma.VideoTrainingItemUpdateWithoutCharactersInput, Prisma.VideoTrainingItemUncheckedUpdateWithoutCharactersInput>
  create: Prisma.XOR<Prisma.VideoTrainingItemCreateWithoutCharactersInput, Prisma.VideoTrainingItemUncheckedCreateWithoutCharactersInput>
  where?: Prisma.VideoTrainingItemWhereInput
}

export type VideoTrainingItemUpdateToOneWithWhereWithoutCharactersInput = {
  where?: Prisma.VideoTrainingItemWhereInput
  data: Prisma.XOR<Prisma.VideoTrainingItemUpdateWithoutCharactersInput, Prisma.VideoTrainingItemUncheckedUpdateWithoutCharactersInput>
}

export type VideoTrainingItemUpdateWithoutCharactersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  sourceTitle?: Prisma.StringFieldUpdateOperationsInput | string
  plotSummary?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.StringFieldUpdateOperationsInput | string
  mediaType?: Prisma.StringFieldUpdateOperationsInput | string
  mediaUrl?: Prisma.StringFieldUpdateOperationsInput | string
  coverUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  captions?: Prisma.VideoCaptionUpdateManyWithoutVideoTrainingItemNestedInput
  phraseNotes?: Prisma.VideoPhraseNoteUpdateManyWithoutVideoTrainingItemNestedInput
}

export type VideoTrainingItemUncheckedUpdateWithoutCharactersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  sourceTitle?: Prisma.StringFieldUpdateOperationsInput | string
  plotSummary?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.StringFieldUpdateOperationsInput | string
  mediaType?: Prisma.StringFieldUpdateOperationsInput | string
  mediaUrl?: Prisma.StringFieldUpdateOperationsInput | string
  coverUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  captions?: Prisma.VideoCaptionUncheckedUpdateManyWithoutVideoTrainingItemNestedInput
  phraseNotes?: Prisma.VideoPhraseNoteUncheckedUpdateManyWithoutVideoTrainingItemNestedInput
}

export type VideoTrainingItemCreateWithoutPhraseNotesInput = {
  id?: string
  title: string
  sourceTitle?: string
  plotSummary?: string
  tag: string
  mediaType?: string
  mediaUrl: string
  coverUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  captions?: Prisma.VideoCaptionCreateNestedManyWithoutVideoTrainingItemInput
  characters?: Prisma.VideoCharacterCreateNestedManyWithoutVideoTrainingItemInput
}

export type VideoTrainingItemUncheckedCreateWithoutPhraseNotesInput = {
  id?: string
  title: string
  sourceTitle?: string
  plotSummary?: string
  tag: string
  mediaType?: string
  mediaUrl: string
  coverUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  captions?: Prisma.VideoCaptionUncheckedCreateNestedManyWithoutVideoTrainingItemInput
  characters?: Prisma.VideoCharacterUncheckedCreateNestedManyWithoutVideoTrainingItemInput
}

export type VideoTrainingItemCreateOrConnectWithoutPhraseNotesInput = {
  where: Prisma.VideoTrainingItemWhereUniqueInput
  create: Prisma.XOR<Prisma.VideoTrainingItemCreateWithoutPhraseNotesInput, Prisma.VideoTrainingItemUncheckedCreateWithoutPhraseNotesInput>
}

export type VideoTrainingItemUpsertWithoutPhraseNotesInput = {
  update: Prisma.XOR<Prisma.VideoTrainingItemUpdateWithoutPhraseNotesInput, Prisma.VideoTrainingItemUncheckedUpdateWithoutPhraseNotesInput>
  create: Prisma.XOR<Prisma.VideoTrainingItemCreateWithoutPhraseNotesInput, Prisma.VideoTrainingItemUncheckedCreateWithoutPhraseNotesInput>
  where?: Prisma.VideoTrainingItemWhereInput
}

export type VideoTrainingItemUpdateToOneWithWhereWithoutPhraseNotesInput = {
  where?: Prisma.VideoTrainingItemWhereInput
  data: Prisma.XOR<Prisma.VideoTrainingItemUpdateWithoutPhraseNotesInput, Prisma.VideoTrainingItemUncheckedUpdateWithoutPhraseNotesInput>
}

export type VideoTrainingItemUpdateWithoutPhraseNotesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  sourceTitle?: Prisma.StringFieldUpdateOperationsInput | string
  plotSummary?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.StringFieldUpdateOperationsInput | string
  mediaType?: Prisma.StringFieldUpdateOperationsInput | string
  mediaUrl?: Prisma.StringFieldUpdateOperationsInput | string
  coverUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  captions?: Prisma.VideoCaptionUpdateManyWithoutVideoTrainingItemNestedInput
  characters?: Prisma.VideoCharacterUpdateManyWithoutVideoTrainingItemNestedInput
}

export type VideoTrainingItemUncheckedUpdateWithoutPhraseNotesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  sourceTitle?: Prisma.StringFieldUpdateOperationsInput | string
  plotSummary?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.StringFieldUpdateOperationsInput | string
  mediaType?: Prisma.StringFieldUpdateOperationsInput | string
  mediaUrl?: Prisma.StringFieldUpdateOperationsInput | string
  coverUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  captions?: Prisma.VideoCaptionUncheckedUpdateManyWithoutVideoTrainingItemNestedInput
  characters?: Prisma.VideoCharacterUncheckedUpdateManyWithoutVideoTrainingItemNestedInput
}


/**
 * Count Type VideoTrainingItemCountOutputType
 */

export type VideoTrainingItemCountOutputType = {
  captions: number
  characters: number
  phraseNotes: number
}

export type VideoTrainingItemCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  captions?: boolean | VideoTrainingItemCountOutputTypeCountCaptionsArgs
  characters?: boolean | VideoTrainingItemCountOutputTypeCountCharactersArgs
  phraseNotes?: boolean | VideoTrainingItemCountOutputTypeCountPhraseNotesArgs
}

/**
 * VideoTrainingItemCountOutputType without action
 */
export type VideoTrainingItemCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoTrainingItemCountOutputType
   */
  select?: Prisma.VideoTrainingItemCountOutputTypeSelect<ExtArgs> | null
}

/**
 * VideoTrainingItemCountOutputType without action
 */
export type VideoTrainingItemCountOutputTypeCountCaptionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VideoCaptionWhereInput
}

/**
 * VideoTrainingItemCountOutputType without action
 */
export type VideoTrainingItemCountOutputTypeCountCharactersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VideoCharacterWhereInput
}

/**
 * VideoTrainingItemCountOutputType without action
 */
export type VideoTrainingItemCountOutputTypeCountPhraseNotesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VideoPhraseNoteWhereInput
}


export type VideoTrainingItemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  sourceTitle?: boolean
  plotSummary?: boolean
  tag?: boolean
  mediaType?: boolean
  mediaUrl?: boolean
  coverUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  captions?: boolean | Prisma.VideoTrainingItem$captionsArgs<ExtArgs>
  characters?: boolean | Prisma.VideoTrainingItem$charactersArgs<ExtArgs>
  phraseNotes?: boolean | Prisma.VideoTrainingItem$phraseNotesArgs<ExtArgs>
  _count?: boolean | Prisma.VideoTrainingItemCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["videoTrainingItem"]>

export type VideoTrainingItemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  sourceTitle?: boolean
  plotSummary?: boolean
  tag?: boolean
  mediaType?: boolean
  mediaUrl?: boolean
  coverUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["videoTrainingItem"]>

export type VideoTrainingItemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  sourceTitle?: boolean
  plotSummary?: boolean
  tag?: boolean
  mediaType?: boolean
  mediaUrl?: boolean
  coverUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["videoTrainingItem"]>

export type VideoTrainingItemSelectScalar = {
  id?: boolean
  title?: boolean
  sourceTitle?: boolean
  plotSummary?: boolean
  tag?: boolean
  mediaType?: boolean
  mediaUrl?: boolean
  coverUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type VideoTrainingItemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "sourceTitle" | "plotSummary" | "tag" | "mediaType" | "mediaUrl" | "coverUrl" | "createdAt" | "updatedAt", ExtArgs["result"]["videoTrainingItem"]>
export type VideoTrainingItemInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  captions?: boolean | Prisma.VideoTrainingItem$captionsArgs<ExtArgs>
  characters?: boolean | Prisma.VideoTrainingItem$charactersArgs<ExtArgs>
  phraseNotes?: boolean | Prisma.VideoTrainingItem$phraseNotesArgs<ExtArgs>
  _count?: boolean | Prisma.VideoTrainingItemCountOutputTypeDefaultArgs<ExtArgs>
}
export type VideoTrainingItemIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type VideoTrainingItemIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $VideoTrainingItemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "VideoTrainingItem"
  objects: {
    captions: Prisma.$VideoCaptionPayload<ExtArgs>[]
    characters: Prisma.$VideoCharacterPayload<ExtArgs>[]
    phraseNotes: Prisma.$VideoPhraseNotePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    sourceTitle: string
    plotSummary: string
    tag: string
    mediaType: string
    mediaUrl: string
    coverUrl: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["videoTrainingItem"]>
  composites: {}
}

export type VideoTrainingItemGetPayload<S extends boolean | null | undefined | VideoTrainingItemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$VideoTrainingItemPayload, S>

export type VideoTrainingItemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<VideoTrainingItemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: VideoTrainingItemCountAggregateInputType | true
  }

export interface VideoTrainingItemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['VideoTrainingItem'], meta: { name: 'VideoTrainingItem' } }
  /**
   * Find zero or one VideoTrainingItem that matches the filter.
   * @param {VideoTrainingItemFindUniqueArgs} args - Arguments to find a VideoTrainingItem
   * @example
   * // Get one VideoTrainingItem
   * const videoTrainingItem = await prisma.videoTrainingItem.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends VideoTrainingItemFindUniqueArgs>(args: Prisma.SelectSubset<T, VideoTrainingItemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__VideoTrainingItemClient<runtime.Types.Result.GetResult<Prisma.$VideoTrainingItemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one VideoTrainingItem that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {VideoTrainingItemFindUniqueOrThrowArgs} args - Arguments to find a VideoTrainingItem
   * @example
   * // Get one VideoTrainingItem
   * const videoTrainingItem = await prisma.videoTrainingItem.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends VideoTrainingItemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, VideoTrainingItemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__VideoTrainingItemClient<runtime.Types.Result.GetResult<Prisma.$VideoTrainingItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VideoTrainingItem that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoTrainingItemFindFirstArgs} args - Arguments to find a VideoTrainingItem
   * @example
   * // Get one VideoTrainingItem
   * const videoTrainingItem = await prisma.videoTrainingItem.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends VideoTrainingItemFindFirstArgs>(args?: Prisma.SelectSubset<T, VideoTrainingItemFindFirstArgs<ExtArgs>>): Prisma.Prisma__VideoTrainingItemClient<runtime.Types.Result.GetResult<Prisma.$VideoTrainingItemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VideoTrainingItem that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoTrainingItemFindFirstOrThrowArgs} args - Arguments to find a VideoTrainingItem
   * @example
   * // Get one VideoTrainingItem
   * const videoTrainingItem = await prisma.videoTrainingItem.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends VideoTrainingItemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, VideoTrainingItemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__VideoTrainingItemClient<runtime.Types.Result.GetResult<Prisma.$VideoTrainingItemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more VideoTrainingItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoTrainingItemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all VideoTrainingItems
   * const videoTrainingItems = await prisma.videoTrainingItem.findMany()
   * 
   * // Get first 10 VideoTrainingItems
   * const videoTrainingItems = await prisma.videoTrainingItem.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const videoTrainingItemWithIdOnly = await prisma.videoTrainingItem.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends VideoTrainingItemFindManyArgs>(args?: Prisma.SelectSubset<T, VideoTrainingItemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VideoTrainingItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a VideoTrainingItem.
   * @param {VideoTrainingItemCreateArgs} args - Arguments to create a VideoTrainingItem.
   * @example
   * // Create one VideoTrainingItem
   * const VideoTrainingItem = await prisma.videoTrainingItem.create({
   *   data: {
   *     // ... data to create a VideoTrainingItem
   *   }
   * })
   * 
   */
  create<T extends VideoTrainingItemCreateArgs>(args: Prisma.SelectSubset<T, VideoTrainingItemCreateArgs<ExtArgs>>): Prisma.Prisma__VideoTrainingItemClient<runtime.Types.Result.GetResult<Prisma.$VideoTrainingItemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many VideoTrainingItems.
   * @param {VideoTrainingItemCreateManyArgs} args - Arguments to create many VideoTrainingItems.
   * @example
   * // Create many VideoTrainingItems
   * const videoTrainingItem = await prisma.videoTrainingItem.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends VideoTrainingItemCreateManyArgs>(args?: Prisma.SelectSubset<T, VideoTrainingItemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many VideoTrainingItems and returns the data saved in the database.
   * @param {VideoTrainingItemCreateManyAndReturnArgs} args - Arguments to create many VideoTrainingItems.
   * @example
   * // Create many VideoTrainingItems
   * const videoTrainingItem = await prisma.videoTrainingItem.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many VideoTrainingItems and only return the `id`
   * const videoTrainingItemWithIdOnly = await prisma.videoTrainingItem.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends VideoTrainingItemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, VideoTrainingItemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VideoTrainingItemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a VideoTrainingItem.
   * @param {VideoTrainingItemDeleteArgs} args - Arguments to delete one VideoTrainingItem.
   * @example
   * // Delete one VideoTrainingItem
   * const VideoTrainingItem = await prisma.videoTrainingItem.delete({
   *   where: {
   *     // ... filter to delete one VideoTrainingItem
   *   }
   * })
   * 
   */
  delete<T extends VideoTrainingItemDeleteArgs>(args: Prisma.SelectSubset<T, VideoTrainingItemDeleteArgs<ExtArgs>>): Prisma.Prisma__VideoTrainingItemClient<runtime.Types.Result.GetResult<Prisma.$VideoTrainingItemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one VideoTrainingItem.
   * @param {VideoTrainingItemUpdateArgs} args - Arguments to update one VideoTrainingItem.
   * @example
   * // Update one VideoTrainingItem
   * const videoTrainingItem = await prisma.videoTrainingItem.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends VideoTrainingItemUpdateArgs>(args: Prisma.SelectSubset<T, VideoTrainingItemUpdateArgs<ExtArgs>>): Prisma.Prisma__VideoTrainingItemClient<runtime.Types.Result.GetResult<Prisma.$VideoTrainingItemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more VideoTrainingItems.
   * @param {VideoTrainingItemDeleteManyArgs} args - Arguments to filter VideoTrainingItems to delete.
   * @example
   * // Delete a few VideoTrainingItems
   * const { count } = await prisma.videoTrainingItem.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends VideoTrainingItemDeleteManyArgs>(args?: Prisma.SelectSubset<T, VideoTrainingItemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VideoTrainingItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoTrainingItemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many VideoTrainingItems
   * const videoTrainingItem = await prisma.videoTrainingItem.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends VideoTrainingItemUpdateManyArgs>(args: Prisma.SelectSubset<T, VideoTrainingItemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VideoTrainingItems and returns the data updated in the database.
   * @param {VideoTrainingItemUpdateManyAndReturnArgs} args - Arguments to update many VideoTrainingItems.
   * @example
   * // Update many VideoTrainingItems
   * const videoTrainingItem = await prisma.videoTrainingItem.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more VideoTrainingItems and only return the `id`
   * const videoTrainingItemWithIdOnly = await prisma.videoTrainingItem.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends VideoTrainingItemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, VideoTrainingItemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VideoTrainingItemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one VideoTrainingItem.
   * @param {VideoTrainingItemUpsertArgs} args - Arguments to update or create a VideoTrainingItem.
   * @example
   * // Update or create a VideoTrainingItem
   * const videoTrainingItem = await prisma.videoTrainingItem.upsert({
   *   create: {
   *     // ... data to create a VideoTrainingItem
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the VideoTrainingItem we want to update
   *   }
   * })
   */
  upsert<T extends VideoTrainingItemUpsertArgs>(args: Prisma.SelectSubset<T, VideoTrainingItemUpsertArgs<ExtArgs>>): Prisma.Prisma__VideoTrainingItemClient<runtime.Types.Result.GetResult<Prisma.$VideoTrainingItemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of VideoTrainingItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoTrainingItemCountArgs} args - Arguments to filter VideoTrainingItems to count.
   * @example
   * // Count the number of VideoTrainingItems
   * const count = await prisma.videoTrainingItem.count({
   *   where: {
   *     // ... the filter for the VideoTrainingItems we want to count
   *   }
   * })
  **/
  count<T extends VideoTrainingItemCountArgs>(
    args?: Prisma.Subset<T, VideoTrainingItemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], VideoTrainingItemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a VideoTrainingItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoTrainingItemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends VideoTrainingItemAggregateArgs>(args: Prisma.Subset<T, VideoTrainingItemAggregateArgs>): Prisma.PrismaPromise<GetVideoTrainingItemAggregateType<T>>

  /**
   * Group by VideoTrainingItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoTrainingItemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends VideoTrainingItemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: VideoTrainingItemGroupByArgs['orderBy'] }
      : { orderBy?: VideoTrainingItemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, VideoTrainingItemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetVideoTrainingItemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the VideoTrainingItem model
 */
readonly fields: VideoTrainingItemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for VideoTrainingItem.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__VideoTrainingItemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  captions<T extends Prisma.VideoTrainingItem$captionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.VideoTrainingItem$captionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VideoCaptionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  characters<T extends Prisma.VideoTrainingItem$charactersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.VideoTrainingItem$charactersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VideoCharacterPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  phraseNotes<T extends Prisma.VideoTrainingItem$phraseNotesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.VideoTrainingItem$phraseNotesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VideoPhraseNotePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the VideoTrainingItem model
 */
export interface VideoTrainingItemFieldRefs {
  readonly id: Prisma.FieldRef<"VideoTrainingItem", 'String'>
  readonly title: Prisma.FieldRef<"VideoTrainingItem", 'String'>
  readonly sourceTitle: Prisma.FieldRef<"VideoTrainingItem", 'String'>
  readonly plotSummary: Prisma.FieldRef<"VideoTrainingItem", 'String'>
  readonly tag: Prisma.FieldRef<"VideoTrainingItem", 'String'>
  readonly mediaType: Prisma.FieldRef<"VideoTrainingItem", 'String'>
  readonly mediaUrl: Prisma.FieldRef<"VideoTrainingItem", 'String'>
  readonly coverUrl: Prisma.FieldRef<"VideoTrainingItem", 'String'>
  readonly createdAt: Prisma.FieldRef<"VideoTrainingItem", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"VideoTrainingItem", 'DateTime'>
}
    

// Custom InputTypes
/**
 * VideoTrainingItem findUnique
 */
export type VideoTrainingItemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoTrainingItem
   */
  select?: Prisma.VideoTrainingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoTrainingItem
   */
  omit?: Prisma.VideoTrainingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoTrainingItemInclude<ExtArgs> | null
  /**
   * Filter, which VideoTrainingItem to fetch.
   */
  where: Prisma.VideoTrainingItemWhereUniqueInput
}

/**
 * VideoTrainingItem findUniqueOrThrow
 */
export type VideoTrainingItemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoTrainingItem
   */
  select?: Prisma.VideoTrainingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoTrainingItem
   */
  omit?: Prisma.VideoTrainingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoTrainingItemInclude<ExtArgs> | null
  /**
   * Filter, which VideoTrainingItem to fetch.
   */
  where: Prisma.VideoTrainingItemWhereUniqueInput
}

/**
 * VideoTrainingItem findFirst
 */
export type VideoTrainingItemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoTrainingItem
   */
  select?: Prisma.VideoTrainingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoTrainingItem
   */
  omit?: Prisma.VideoTrainingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoTrainingItemInclude<ExtArgs> | null
  /**
   * Filter, which VideoTrainingItem to fetch.
   */
  where?: Prisma.VideoTrainingItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VideoTrainingItems to fetch.
   */
  orderBy?: Prisma.VideoTrainingItemOrderByWithRelationInput | Prisma.VideoTrainingItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VideoTrainingItems.
   */
  cursor?: Prisma.VideoTrainingItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VideoTrainingItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VideoTrainingItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VideoTrainingItems.
   */
  distinct?: Prisma.VideoTrainingItemScalarFieldEnum | Prisma.VideoTrainingItemScalarFieldEnum[]
}

/**
 * VideoTrainingItem findFirstOrThrow
 */
export type VideoTrainingItemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoTrainingItem
   */
  select?: Prisma.VideoTrainingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoTrainingItem
   */
  omit?: Prisma.VideoTrainingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoTrainingItemInclude<ExtArgs> | null
  /**
   * Filter, which VideoTrainingItem to fetch.
   */
  where?: Prisma.VideoTrainingItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VideoTrainingItems to fetch.
   */
  orderBy?: Prisma.VideoTrainingItemOrderByWithRelationInput | Prisma.VideoTrainingItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VideoTrainingItems.
   */
  cursor?: Prisma.VideoTrainingItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VideoTrainingItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VideoTrainingItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VideoTrainingItems.
   */
  distinct?: Prisma.VideoTrainingItemScalarFieldEnum | Prisma.VideoTrainingItemScalarFieldEnum[]
}

/**
 * VideoTrainingItem findMany
 */
export type VideoTrainingItemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoTrainingItem
   */
  select?: Prisma.VideoTrainingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoTrainingItem
   */
  omit?: Prisma.VideoTrainingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoTrainingItemInclude<ExtArgs> | null
  /**
   * Filter, which VideoTrainingItems to fetch.
   */
  where?: Prisma.VideoTrainingItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VideoTrainingItems to fetch.
   */
  orderBy?: Prisma.VideoTrainingItemOrderByWithRelationInput | Prisma.VideoTrainingItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing VideoTrainingItems.
   */
  cursor?: Prisma.VideoTrainingItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VideoTrainingItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VideoTrainingItems.
   */
  skip?: number
  distinct?: Prisma.VideoTrainingItemScalarFieldEnum | Prisma.VideoTrainingItemScalarFieldEnum[]
}

/**
 * VideoTrainingItem create
 */
export type VideoTrainingItemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoTrainingItem
   */
  select?: Prisma.VideoTrainingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoTrainingItem
   */
  omit?: Prisma.VideoTrainingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoTrainingItemInclude<ExtArgs> | null
  /**
   * The data needed to create a VideoTrainingItem.
   */
  data: Prisma.XOR<Prisma.VideoTrainingItemCreateInput, Prisma.VideoTrainingItemUncheckedCreateInput>
}

/**
 * VideoTrainingItem createMany
 */
export type VideoTrainingItemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many VideoTrainingItems.
   */
  data: Prisma.VideoTrainingItemCreateManyInput | Prisma.VideoTrainingItemCreateManyInput[]
}

/**
 * VideoTrainingItem createManyAndReturn
 */
export type VideoTrainingItemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoTrainingItem
   */
  select?: Prisma.VideoTrainingItemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the VideoTrainingItem
   */
  omit?: Prisma.VideoTrainingItemOmit<ExtArgs> | null
  /**
   * The data used to create many VideoTrainingItems.
   */
  data: Prisma.VideoTrainingItemCreateManyInput | Prisma.VideoTrainingItemCreateManyInput[]
}

/**
 * VideoTrainingItem update
 */
export type VideoTrainingItemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoTrainingItem
   */
  select?: Prisma.VideoTrainingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoTrainingItem
   */
  omit?: Prisma.VideoTrainingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoTrainingItemInclude<ExtArgs> | null
  /**
   * The data needed to update a VideoTrainingItem.
   */
  data: Prisma.XOR<Prisma.VideoTrainingItemUpdateInput, Prisma.VideoTrainingItemUncheckedUpdateInput>
  /**
   * Choose, which VideoTrainingItem to update.
   */
  where: Prisma.VideoTrainingItemWhereUniqueInput
}

/**
 * VideoTrainingItem updateMany
 */
export type VideoTrainingItemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update VideoTrainingItems.
   */
  data: Prisma.XOR<Prisma.VideoTrainingItemUpdateManyMutationInput, Prisma.VideoTrainingItemUncheckedUpdateManyInput>
  /**
   * Filter which VideoTrainingItems to update
   */
  where?: Prisma.VideoTrainingItemWhereInput
  /**
   * Limit how many VideoTrainingItems to update.
   */
  limit?: number
}

/**
 * VideoTrainingItem updateManyAndReturn
 */
export type VideoTrainingItemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoTrainingItem
   */
  select?: Prisma.VideoTrainingItemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the VideoTrainingItem
   */
  omit?: Prisma.VideoTrainingItemOmit<ExtArgs> | null
  /**
   * The data used to update VideoTrainingItems.
   */
  data: Prisma.XOR<Prisma.VideoTrainingItemUpdateManyMutationInput, Prisma.VideoTrainingItemUncheckedUpdateManyInput>
  /**
   * Filter which VideoTrainingItems to update
   */
  where?: Prisma.VideoTrainingItemWhereInput
  /**
   * Limit how many VideoTrainingItems to update.
   */
  limit?: number
}

/**
 * VideoTrainingItem upsert
 */
export type VideoTrainingItemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoTrainingItem
   */
  select?: Prisma.VideoTrainingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoTrainingItem
   */
  omit?: Prisma.VideoTrainingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoTrainingItemInclude<ExtArgs> | null
  /**
   * The filter to search for the VideoTrainingItem to update in case it exists.
   */
  where: Prisma.VideoTrainingItemWhereUniqueInput
  /**
   * In case the VideoTrainingItem found by the `where` argument doesn't exist, create a new VideoTrainingItem with this data.
   */
  create: Prisma.XOR<Prisma.VideoTrainingItemCreateInput, Prisma.VideoTrainingItemUncheckedCreateInput>
  /**
   * In case the VideoTrainingItem was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.VideoTrainingItemUpdateInput, Prisma.VideoTrainingItemUncheckedUpdateInput>
}

/**
 * VideoTrainingItem delete
 */
export type VideoTrainingItemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoTrainingItem
   */
  select?: Prisma.VideoTrainingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoTrainingItem
   */
  omit?: Prisma.VideoTrainingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoTrainingItemInclude<ExtArgs> | null
  /**
   * Filter which VideoTrainingItem to delete.
   */
  where: Prisma.VideoTrainingItemWhereUniqueInput
}

/**
 * VideoTrainingItem deleteMany
 */
export type VideoTrainingItemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VideoTrainingItems to delete
   */
  where?: Prisma.VideoTrainingItemWhereInput
  /**
   * Limit how many VideoTrainingItems to delete.
   */
  limit?: number
}

/**
 * VideoTrainingItem.captions
 */
export type VideoTrainingItem$captionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoCaption
   */
  select?: Prisma.VideoCaptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoCaption
   */
  omit?: Prisma.VideoCaptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoCaptionInclude<ExtArgs> | null
  where?: Prisma.VideoCaptionWhereInput
  orderBy?: Prisma.VideoCaptionOrderByWithRelationInput | Prisma.VideoCaptionOrderByWithRelationInput[]
  cursor?: Prisma.VideoCaptionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.VideoCaptionScalarFieldEnum | Prisma.VideoCaptionScalarFieldEnum[]
}

/**
 * VideoTrainingItem.characters
 */
export type VideoTrainingItem$charactersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoCharacter
   */
  select?: Prisma.VideoCharacterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoCharacter
   */
  omit?: Prisma.VideoCharacterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoCharacterInclude<ExtArgs> | null
  where?: Prisma.VideoCharacterWhereInput
  orderBy?: Prisma.VideoCharacterOrderByWithRelationInput | Prisma.VideoCharacterOrderByWithRelationInput[]
  cursor?: Prisma.VideoCharacterWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.VideoCharacterScalarFieldEnum | Prisma.VideoCharacterScalarFieldEnum[]
}

/**
 * VideoTrainingItem.phraseNotes
 */
export type VideoTrainingItem$phraseNotesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoPhraseNote
   */
  select?: Prisma.VideoPhraseNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoPhraseNote
   */
  omit?: Prisma.VideoPhraseNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoPhraseNoteInclude<ExtArgs> | null
  where?: Prisma.VideoPhraseNoteWhereInput
  orderBy?: Prisma.VideoPhraseNoteOrderByWithRelationInput | Prisma.VideoPhraseNoteOrderByWithRelationInput[]
  cursor?: Prisma.VideoPhraseNoteWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.VideoPhraseNoteScalarFieldEnum | Prisma.VideoPhraseNoteScalarFieldEnum[]
}

/**
 * VideoTrainingItem without action
 */
export type VideoTrainingItemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoTrainingItem
   */
  select?: Prisma.VideoTrainingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoTrainingItem
   */
  omit?: Prisma.VideoTrainingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoTrainingItemInclude<ExtArgs> | null
}
