
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `VideoCaptionNote` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model VideoCaptionNote
 * 
 */
export type VideoCaptionNoteModel = runtime.Types.Result.DefaultSelection<Prisma.$VideoCaptionNotePayload>

export type AggregateVideoCaptionNote = {
  _count: VideoCaptionNoteCountAggregateOutputType | null
  _min: VideoCaptionNoteMinAggregateOutputType | null
  _max: VideoCaptionNoteMaxAggregateOutputType | null
}

export type VideoCaptionNoteMinAggregateOutputType = {
  id: string | null
  videoCaptionId: string | null
  words: string | null
  notes: string | null
  userId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type VideoCaptionNoteMaxAggregateOutputType = {
  id: string | null
  videoCaptionId: string | null
  words: string | null
  notes: string | null
  userId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type VideoCaptionNoteCountAggregateOutputType = {
  id: number
  videoCaptionId: number
  words: number
  notes: number
  userId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type VideoCaptionNoteMinAggregateInputType = {
  id?: true
  videoCaptionId?: true
  words?: true
  notes?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
}

export type VideoCaptionNoteMaxAggregateInputType = {
  id?: true
  videoCaptionId?: true
  words?: true
  notes?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
}

export type VideoCaptionNoteCountAggregateInputType = {
  id?: true
  videoCaptionId?: true
  words?: true
  notes?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type VideoCaptionNoteAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VideoCaptionNote to aggregate.
   */
  where?: Prisma.VideoCaptionNoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VideoCaptionNotes to fetch.
   */
  orderBy?: Prisma.VideoCaptionNoteOrderByWithRelationInput | Prisma.VideoCaptionNoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.VideoCaptionNoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VideoCaptionNotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VideoCaptionNotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned VideoCaptionNotes
  **/
  _count?: true | VideoCaptionNoteCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: VideoCaptionNoteMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: VideoCaptionNoteMaxAggregateInputType
}

export type GetVideoCaptionNoteAggregateType<T extends VideoCaptionNoteAggregateArgs> = {
      [P in keyof T & keyof AggregateVideoCaptionNote]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateVideoCaptionNote[P]>
    : Prisma.GetScalarType<T[P], AggregateVideoCaptionNote[P]>
}




export type VideoCaptionNoteGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VideoCaptionNoteWhereInput
  orderBy?: Prisma.VideoCaptionNoteOrderByWithAggregationInput | Prisma.VideoCaptionNoteOrderByWithAggregationInput[]
  by: Prisma.VideoCaptionNoteScalarFieldEnum[] | Prisma.VideoCaptionNoteScalarFieldEnum
  having?: Prisma.VideoCaptionNoteScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: VideoCaptionNoteCountAggregateInputType | true
  _min?: VideoCaptionNoteMinAggregateInputType
  _max?: VideoCaptionNoteMaxAggregateInputType
}

export type VideoCaptionNoteGroupByOutputType = {
  id: string
  videoCaptionId: string
  words: string
  notes: string
  userId: string
  createdAt: Date
  updatedAt: Date
  _count: VideoCaptionNoteCountAggregateOutputType | null
  _min: VideoCaptionNoteMinAggregateOutputType | null
  _max: VideoCaptionNoteMaxAggregateOutputType | null
}

type GetVideoCaptionNoteGroupByPayload<T extends VideoCaptionNoteGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<VideoCaptionNoteGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof VideoCaptionNoteGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], VideoCaptionNoteGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], VideoCaptionNoteGroupByOutputType[P]>
      }
    >
  >



export type VideoCaptionNoteWhereInput = {
  AND?: Prisma.VideoCaptionNoteWhereInput | Prisma.VideoCaptionNoteWhereInput[]
  OR?: Prisma.VideoCaptionNoteWhereInput[]
  NOT?: Prisma.VideoCaptionNoteWhereInput | Prisma.VideoCaptionNoteWhereInput[]
  id?: Prisma.StringFilter<"VideoCaptionNote"> | string
  videoCaptionId?: Prisma.StringFilter<"VideoCaptionNote"> | string
  words?: Prisma.StringFilter<"VideoCaptionNote"> | string
  notes?: Prisma.StringFilter<"VideoCaptionNote"> | string
  userId?: Prisma.StringFilter<"VideoCaptionNote"> | string
  createdAt?: Prisma.DateTimeFilter<"VideoCaptionNote"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"VideoCaptionNote"> | Date | string
  caption?: Prisma.XOR<Prisma.VideoCaptionScalarRelationFilter, Prisma.VideoCaptionWhereInput>
}

export type VideoCaptionNoteOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  videoCaptionId?: Prisma.SortOrder
  words?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  caption?: Prisma.VideoCaptionOrderByWithRelationInput
}

export type VideoCaptionNoteWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  videoCaptionId_userId?: Prisma.VideoCaptionNoteVideoCaptionIdUserIdCompoundUniqueInput
  AND?: Prisma.VideoCaptionNoteWhereInput | Prisma.VideoCaptionNoteWhereInput[]
  OR?: Prisma.VideoCaptionNoteWhereInput[]
  NOT?: Prisma.VideoCaptionNoteWhereInput | Prisma.VideoCaptionNoteWhereInput[]
  videoCaptionId?: Prisma.StringFilter<"VideoCaptionNote"> | string
  words?: Prisma.StringFilter<"VideoCaptionNote"> | string
  notes?: Prisma.StringFilter<"VideoCaptionNote"> | string
  userId?: Prisma.StringFilter<"VideoCaptionNote"> | string
  createdAt?: Prisma.DateTimeFilter<"VideoCaptionNote"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"VideoCaptionNote"> | Date | string
  caption?: Prisma.XOR<Prisma.VideoCaptionScalarRelationFilter, Prisma.VideoCaptionWhereInput>
}, "id" | "videoCaptionId_userId">

export type VideoCaptionNoteOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  videoCaptionId?: Prisma.SortOrder
  words?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.VideoCaptionNoteCountOrderByAggregateInput
  _max?: Prisma.VideoCaptionNoteMaxOrderByAggregateInput
  _min?: Prisma.VideoCaptionNoteMinOrderByAggregateInput
}

export type VideoCaptionNoteScalarWhereWithAggregatesInput = {
  AND?: Prisma.VideoCaptionNoteScalarWhereWithAggregatesInput | Prisma.VideoCaptionNoteScalarWhereWithAggregatesInput[]
  OR?: Prisma.VideoCaptionNoteScalarWhereWithAggregatesInput[]
  NOT?: Prisma.VideoCaptionNoteScalarWhereWithAggregatesInput | Prisma.VideoCaptionNoteScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"VideoCaptionNote"> | string
  videoCaptionId?: Prisma.StringWithAggregatesFilter<"VideoCaptionNote"> | string
  words?: Prisma.StringWithAggregatesFilter<"VideoCaptionNote"> | string
  notes?: Prisma.StringWithAggregatesFilter<"VideoCaptionNote"> | string
  userId?: Prisma.StringWithAggregatesFilter<"VideoCaptionNote"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"VideoCaptionNote"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"VideoCaptionNote"> | Date | string
}

export type VideoCaptionNoteCreateInput = {
  id?: string
  words?: string
  notes?: string
  userId?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  caption: Prisma.VideoCaptionCreateNestedOneWithoutCaptionNotesInput
}

export type VideoCaptionNoteUncheckedCreateInput = {
  id?: string
  videoCaptionId: string
  words?: string
  notes?: string
  userId?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type VideoCaptionNoteUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  words?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  caption?: Prisma.VideoCaptionUpdateOneRequiredWithoutCaptionNotesNestedInput
}

export type VideoCaptionNoteUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  videoCaptionId?: Prisma.StringFieldUpdateOperationsInput | string
  words?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VideoCaptionNoteCreateManyInput = {
  id?: string
  videoCaptionId: string
  words?: string
  notes?: string
  userId?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type VideoCaptionNoteUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  words?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VideoCaptionNoteUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  videoCaptionId?: Prisma.StringFieldUpdateOperationsInput | string
  words?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VideoCaptionNoteListRelationFilter = {
  every?: Prisma.VideoCaptionNoteWhereInput
  some?: Prisma.VideoCaptionNoteWhereInput
  none?: Prisma.VideoCaptionNoteWhereInput
}

export type VideoCaptionNoteOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type VideoCaptionNoteVideoCaptionIdUserIdCompoundUniqueInput = {
  videoCaptionId: string
  userId: string
}

export type VideoCaptionNoteCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  videoCaptionId?: Prisma.SortOrder
  words?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type VideoCaptionNoteMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  videoCaptionId?: Prisma.SortOrder
  words?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type VideoCaptionNoteMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  videoCaptionId?: Prisma.SortOrder
  words?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type VideoCaptionNoteCreateNestedManyWithoutCaptionInput = {
  create?: Prisma.XOR<Prisma.VideoCaptionNoteCreateWithoutCaptionInput, Prisma.VideoCaptionNoteUncheckedCreateWithoutCaptionInput> | Prisma.VideoCaptionNoteCreateWithoutCaptionInput[] | Prisma.VideoCaptionNoteUncheckedCreateWithoutCaptionInput[]
  connectOrCreate?: Prisma.VideoCaptionNoteCreateOrConnectWithoutCaptionInput | Prisma.VideoCaptionNoteCreateOrConnectWithoutCaptionInput[]
  createMany?: Prisma.VideoCaptionNoteCreateManyCaptionInputEnvelope
  connect?: Prisma.VideoCaptionNoteWhereUniqueInput | Prisma.VideoCaptionNoteWhereUniqueInput[]
}

export type VideoCaptionNoteUncheckedCreateNestedManyWithoutCaptionInput = {
  create?: Prisma.XOR<Prisma.VideoCaptionNoteCreateWithoutCaptionInput, Prisma.VideoCaptionNoteUncheckedCreateWithoutCaptionInput> | Prisma.VideoCaptionNoteCreateWithoutCaptionInput[] | Prisma.VideoCaptionNoteUncheckedCreateWithoutCaptionInput[]
  connectOrCreate?: Prisma.VideoCaptionNoteCreateOrConnectWithoutCaptionInput | Prisma.VideoCaptionNoteCreateOrConnectWithoutCaptionInput[]
  createMany?: Prisma.VideoCaptionNoteCreateManyCaptionInputEnvelope
  connect?: Prisma.VideoCaptionNoteWhereUniqueInput | Prisma.VideoCaptionNoteWhereUniqueInput[]
}

export type VideoCaptionNoteUpdateManyWithoutCaptionNestedInput = {
  create?: Prisma.XOR<Prisma.VideoCaptionNoteCreateWithoutCaptionInput, Prisma.VideoCaptionNoteUncheckedCreateWithoutCaptionInput> | Prisma.VideoCaptionNoteCreateWithoutCaptionInput[] | Prisma.VideoCaptionNoteUncheckedCreateWithoutCaptionInput[]
  connectOrCreate?: Prisma.VideoCaptionNoteCreateOrConnectWithoutCaptionInput | Prisma.VideoCaptionNoteCreateOrConnectWithoutCaptionInput[]
  upsert?: Prisma.VideoCaptionNoteUpsertWithWhereUniqueWithoutCaptionInput | Prisma.VideoCaptionNoteUpsertWithWhereUniqueWithoutCaptionInput[]
  createMany?: Prisma.VideoCaptionNoteCreateManyCaptionInputEnvelope
  set?: Prisma.VideoCaptionNoteWhereUniqueInput | Prisma.VideoCaptionNoteWhereUniqueInput[]
  disconnect?: Prisma.VideoCaptionNoteWhereUniqueInput | Prisma.VideoCaptionNoteWhereUniqueInput[]
  delete?: Prisma.VideoCaptionNoteWhereUniqueInput | Prisma.VideoCaptionNoteWhereUniqueInput[]
  connect?: Prisma.VideoCaptionNoteWhereUniqueInput | Prisma.VideoCaptionNoteWhereUniqueInput[]
  update?: Prisma.VideoCaptionNoteUpdateWithWhereUniqueWithoutCaptionInput | Prisma.VideoCaptionNoteUpdateWithWhereUniqueWithoutCaptionInput[]
  updateMany?: Prisma.VideoCaptionNoteUpdateManyWithWhereWithoutCaptionInput | Prisma.VideoCaptionNoteUpdateManyWithWhereWithoutCaptionInput[]
  deleteMany?: Prisma.VideoCaptionNoteScalarWhereInput | Prisma.VideoCaptionNoteScalarWhereInput[]
}

export type VideoCaptionNoteUncheckedUpdateManyWithoutCaptionNestedInput = {
  create?: Prisma.XOR<Prisma.VideoCaptionNoteCreateWithoutCaptionInput, Prisma.VideoCaptionNoteUncheckedCreateWithoutCaptionInput> | Prisma.VideoCaptionNoteCreateWithoutCaptionInput[] | Prisma.VideoCaptionNoteUncheckedCreateWithoutCaptionInput[]
  connectOrCreate?: Prisma.VideoCaptionNoteCreateOrConnectWithoutCaptionInput | Prisma.VideoCaptionNoteCreateOrConnectWithoutCaptionInput[]
  upsert?: Prisma.VideoCaptionNoteUpsertWithWhereUniqueWithoutCaptionInput | Prisma.VideoCaptionNoteUpsertWithWhereUniqueWithoutCaptionInput[]
  createMany?: Prisma.VideoCaptionNoteCreateManyCaptionInputEnvelope
  set?: Prisma.VideoCaptionNoteWhereUniqueInput | Prisma.VideoCaptionNoteWhereUniqueInput[]
  disconnect?: Prisma.VideoCaptionNoteWhereUniqueInput | Prisma.VideoCaptionNoteWhereUniqueInput[]
  delete?: Prisma.VideoCaptionNoteWhereUniqueInput | Prisma.VideoCaptionNoteWhereUniqueInput[]
  connect?: Prisma.VideoCaptionNoteWhereUniqueInput | Prisma.VideoCaptionNoteWhereUniqueInput[]
  update?: Prisma.VideoCaptionNoteUpdateWithWhereUniqueWithoutCaptionInput | Prisma.VideoCaptionNoteUpdateWithWhereUniqueWithoutCaptionInput[]
  updateMany?: Prisma.VideoCaptionNoteUpdateManyWithWhereWithoutCaptionInput | Prisma.VideoCaptionNoteUpdateManyWithWhereWithoutCaptionInput[]
  deleteMany?: Prisma.VideoCaptionNoteScalarWhereInput | Prisma.VideoCaptionNoteScalarWhereInput[]
}

export type VideoCaptionNoteCreateWithoutCaptionInput = {
  id?: string
  words?: string
  notes?: string
  userId?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type VideoCaptionNoteUncheckedCreateWithoutCaptionInput = {
  id?: string
  words?: string
  notes?: string
  userId?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type VideoCaptionNoteCreateOrConnectWithoutCaptionInput = {
  where: Prisma.VideoCaptionNoteWhereUniqueInput
  create: Prisma.XOR<Prisma.VideoCaptionNoteCreateWithoutCaptionInput, Prisma.VideoCaptionNoteUncheckedCreateWithoutCaptionInput>
}

export type VideoCaptionNoteCreateManyCaptionInputEnvelope = {
  data: Prisma.VideoCaptionNoteCreateManyCaptionInput | Prisma.VideoCaptionNoteCreateManyCaptionInput[]
}

export type VideoCaptionNoteUpsertWithWhereUniqueWithoutCaptionInput = {
  where: Prisma.VideoCaptionNoteWhereUniqueInput
  update: Prisma.XOR<Prisma.VideoCaptionNoteUpdateWithoutCaptionInput, Prisma.VideoCaptionNoteUncheckedUpdateWithoutCaptionInput>
  create: Prisma.XOR<Prisma.VideoCaptionNoteCreateWithoutCaptionInput, Prisma.VideoCaptionNoteUncheckedCreateWithoutCaptionInput>
}

export type VideoCaptionNoteUpdateWithWhereUniqueWithoutCaptionInput = {
  where: Prisma.VideoCaptionNoteWhereUniqueInput
  data: Prisma.XOR<Prisma.VideoCaptionNoteUpdateWithoutCaptionInput, Prisma.VideoCaptionNoteUncheckedUpdateWithoutCaptionInput>
}

export type VideoCaptionNoteUpdateManyWithWhereWithoutCaptionInput = {
  where: Prisma.VideoCaptionNoteScalarWhereInput
  data: Prisma.XOR<Prisma.VideoCaptionNoteUpdateManyMutationInput, Prisma.VideoCaptionNoteUncheckedUpdateManyWithoutCaptionInput>
}

export type VideoCaptionNoteScalarWhereInput = {
  AND?: Prisma.VideoCaptionNoteScalarWhereInput | Prisma.VideoCaptionNoteScalarWhereInput[]
  OR?: Prisma.VideoCaptionNoteScalarWhereInput[]
  NOT?: Prisma.VideoCaptionNoteScalarWhereInput | Prisma.VideoCaptionNoteScalarWhereInput[]
  id?: Prisma.StringFilter<"VideoCaptionNote"> | string
  videoCaptionId?: Prisma.StringFilter<"VideoCaptionNote"> | string
  words?: Prisma.StringFilter<"VideoCaptionNote"> | string
  notes?: Prisma.StringFilter<"VideoCaptionNote"> | string
  userId?: Prisma.StringFilter<"VideoCaptionNote"> | string
  createdAt?: Prisma.DateTimeFilter<"VideoCaptionNote"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"VideoCaptionNote"> | Date | string
}

export type VideoCaptionNoteCreateManyCaptionInput = {
  id?: string
  words?: string
  notes?: string
  userId?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type VideoCaptionNoteUpdateWithoutCaptionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  words?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VideoCaptionNoteUncheckedUpdateWithoutCaptionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  words?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VideoCaptionNoteUncheckedUpdateManyWithoutCaptionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  words?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type VideoCaptionNoteSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  videoCaptionId?: boolean
  words?: boolean
  notes?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  caption?: boolean | Prisma.VideoCaptionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["videoCaptionNote"]>

export type VideoCaptionNoteSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  videoCaptionId?: boolean
  words?: boolean
  notes?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  caption?: boolean | Prisma.VideoCaptionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["videoCaptionNote"]>

export type VideoCaptionNoteSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  videoCaptionId?: boolean
  words?: boolean
  notes?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  caption?: boolean | Prisma.VideoCaptionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["videoCaptionNote"]>

export type VideoCaptionNoteSelectScalar = {
  id?: boolean
  videoCaptionId?: boolean
  words?: boolean
  notes?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type VideoCaptionNoteOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "videoCaptionId" | "words" | "notes" | "userId" | "createdAt" | "updatedAt", ExtArgs["result"]["videoCaptionNote"]>
export type VideoCaptionNoteInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  caption?: boolean | Prisma.VideoCaptionDefaultArgs<ExtArgs>
}
export type VideoCaptionNoteIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  caption?: boolean | Prisma.VideoCaptionDefaultArgs<ExtArgs>
}
export type VideoCaptionNoteIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  caption?: boolean | Prisma.VideoCaptionDefaultArgs<ExtArgs>
}

export type $VideoCaptionNotePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "VideoCaptionNote"
  objects: {
    caption: Prisma.$VideoCaptionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    videoCaptionId: string
    words: string
    notes: string
    userId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["videoCaptionNote"]>
  composites: {}
}

export type VideoCaptionNoteGetPayload<S extends boolean | null | undefined | VideoCaptionNoteDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$VideoCaptionNotePayload, S>

export type VideoCaptionNoteCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<VideoCaptionNoteFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: VideoCaptionNoteCountAggregateInputType | true
  }

export interface VideoCaptionNoteDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['VideoCaptionNote'], meta: { name: 'VideoCaptionNote' } }
  /**
   * Find zero or one VideoCaptionNote that matches the filter.
   * @param {VideoCaptionNoteFindUniqueArgs} args - Arguments to find a VideoCaptionNote
   * @example
   * // Get one VideoCaptionNote
   * const videoCaptionNote = await prisma.videoCaptionNote.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends VideoCaptionNoteFindUniqueArgs>(args: Prisma.SelectSubset<T, VideoCaptionNoteFindUniqueArgs<ExtArgs>>): Prisma.Prisma__VideoCaptionNoteClient<runtime.Types.Result.GetResult<Prisma.$VideoCaptionNotePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one VideoCaptionNote that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {VideoCaptionNoteFindUniqueOrThrowArgs} args - Arguments to find a VideoCaptionNote
   * @example
   * // Get one VideoCaptionNote
   * const videoCaptionNote = await prisma.videoCaptionNote.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends VideoCaptionNoteFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, VideoCaptionNoteFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__VideoCaptionNoteClient<runtime.Types.Result.GetResult<Prisma.$VideoCaptionNotePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VideoCaptionNote that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoCaptionNoteFindFirstArgs} args - Arguments to find a VideoCaptionNote
   * @example
   * // Get one VideoCaptionNote
   * const videoCaptionNote = await prisma.videoCaptionNote.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends VideoCaptionNoteFindFirstArgs>(args?: Prisma.SelectSubset<T, VideoCaptionNoteFindFirstArgs<ExtArgs>>): Prisma.Prisma__VideoCaptionNoteClient<runtime.Types.Result.GetResult<Prisma.$VideoCaptionNotePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VideoCaptionNote that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoCaptionNoteFindFirstOrThrowArgs} args - Arguments to find a VideoCaptionNote
   * @example
   * // Get one VideoCaptionNote
   * const videoCaptionNote = await prisma.videoCaptionNote.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends VideoCaptionNoteFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, VideoCaptionNoteFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__VideoCaptionNoteClient<runtime.Types.Result.GetResult<Prisma.$VideoCaptionNotePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more VideoCaptionNotes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoCaptionNoteFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all VideoCaptionNotes
   * const videoCaptionNotes = await prisma.videoCaptionNote.findMany()
   * 
   * // Get first 10 VideoCaptionNotes
   * const videoCaptionNotes = await prisma.videoCaptionNote.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const videoCaptionNoteWithIdOnly = await prisma.videoCaptionNote.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends VideoCaptionNoteFindManyArgs>(args?: Prisma.SelectSubset<T, VideoCaptionNoteFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VideoCaptionNotePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a VideoCaptionNote.
   * @param {VideoCaptionNoteCreateArgs} args - Arguments to create a VideoCaptionNote.
   * @example
   * // Create one VideoCaptionNote
   * const VideoCaptionNote = await prisma.videoCaptionNote.create({
   *   data: {
   *     // ... data to create a VideoCaptionNote
   *   }
   * })
   * 
   */
  create<T extends VideoCaptionNoteCreateArgs>(args: Prisma.SelectSubset<T, VideoCaptionNoteCreateArgs<ExtArgs>>): Prisma.Prisma__VideoCaptionNoteClient<runtime.Types.Result.GetResult<Prisma.$VideoCaptionNotePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many VideoCaptionNotes.
   * @param {VideoCaptionNoteCreateManyArgs} args - Arguments to create many VideoCaptionNotes.
   * @example
   * // Create many VideoCaptionNotes
   * const videoCaptionNote = await prisma.videoCaptionNote.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends VideoCaptionNoteCreateManyArgs>(args?: Prisma.SelectSubset<T, VideoCaptionNoteCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many VideoCaptionNotes and returns the data saved in the database.
   * @param {VideoCaptionNoteCreateManyAndReturnArgs} args - Arguments to create many VideoCaptionNotes.
   * @example
   * // Create many VideoCaptionNotes
   * const videoCaptionNote = await prisma.videoCaptionNote.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many VideoCaptionNotes and only return the `id`
   * const videoCaptionNoteWithIdOnly = await prisma.videoCaptionNote.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends VideoCaptionNoteCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, VideoCaptionNoteCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VideoCaptionNotePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a VideoCaptionNote.
   * @param {VideoCaptionNoteDeleteArgs} args - Arguments to delete one VideoCaptionNote.
   * @example
   * // Delete one VideoCaptionNote
   * const VideoCaptionNote = await prisma.videoCaptionNote.delete({
   *   where: {
   *     // ... filter to delete one VideoCaptionNote
   *   }
   * })
   * 
   */
  delete<T extends VideoCaptionNoteDeleteArgs>(args: Prisma.SelectSubset<T, VideoCaptionNoteDeleteArgs<ExtArgs>>): Prisma.Prisma__VideoCaptionNoteClient<runtime.Types.Result.GetResult<Prisma.$VideoCaptionNotePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one VideoCaptionNote.
   * @param {VideoCaptionNoteUpdateArgs} args - Arguments to update one VideoCaptionNote.
   * @example
   * // Update one VideoCaptionNote
   * const videoCaptionNote = await prisma.videoCaptionNote.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends VideoCaptionNoteUpdateArgs>(args: Prisma.SelectSubset<T, VideoCaptionNoteUpdateArgs<ExtArgs>>): Prisma.Prisma__VideoCaptionNoteClient<runtime.Types.Result.GetResult<Prisma.$VideoCaptionNotePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more VideoCaptionNotes.
   * @param {VideoCaptionNoteDeleteManyArgs} args - Arguments to filter VideoCaptionNotes to delete.
   * @example
   * // Delete a few VideoCaptionNotes
   * const { count } = await prisma.videoCaptionNote.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends VideoCaptionNoteDeleteManyArgs>(args?: Prisma.SelectSubset<T, VideoCaptionNoteDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VideoCaptionNotes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoCaptionNoteUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many VideoCaptionNotes
   * const videoCaptionNote = await prisma.videoCaptionNote.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends VideoCaptionNoteUpdateManyArgs>(args: Prisma.SelectSubset<T, VideoCaptionNoteUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VideoCaptionNotes and returns the data updated in the database.
   * @param {VideoCaptionNoteUpdateManyAndReturnArgs} args - Arguments to update many VideoCaptionNotes.
   * @example
   * // Update many VideoCaptionNotes
   * const videoCaptionNote = await prisma.videoCaptionNote.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more VideoCaptionNotes and only return the `id`
   * const videoCaptionNoteWithIdOnly = await prisma.videoCaptionNote.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends VideoCaptionNoteUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, VideoCaptionNoteUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VideoCaptionNotePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one VideoCaptionNote.
   * @param {VideoCaptionNoteUpsertArgs} args - Arguments to update or create a VideoCaptionNote.
   * @example
   * // Update or create a VideoCaptionNote
   * const videoCaptionNote = await prisma.videoCaptionNote.upsert({
   *   create: {
   *     // ... data to create a VideoCaptionNote
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the VideoCaptionNote we want to update
   *   }
   * })
   */
  upsert<T extends VideoCaptionNoteUpsertArgs>(args: Prisma.SelectSubset<T, VideoCaptionNoteUpsertArgs<ExtArgs>>): Prisma.Prisma__VideoCaptionNoteClient<runtime.Types.Result.GetResult<Prisma.$VideoCaptionNotePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of VideoCaptionNotes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoCaptionNoteCountArgs} args - Arguments to filter VideoCaptionNotes to count.
   * @example
   * // Count the number of VideoCaptionNotes
   * const count = await prisma.videoCaptionNote.count({
   *   where: {
   *     // ... the filter for the VideoCaptionNotes we want to count
   *   }
   * })
  **/
  count<T extends VideoCaptionNoteCountArgs>(
    args?: Prisma.Subset<T, VideoCaptionNoteCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], VideoCaptionNoteCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a VideoCaptionNote.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoCaptionNoteAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends VideoCaptionNoteAggregateArgs>(args: Prisma.Subset<T, VideoCaptionNoteAggregateArgs>): Prisma.PrismaPromise<GetVideoCaptionNoteAggregateType<T>>

  /**
   * Group by VideoCaptionNote.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoCaptionNoteGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends VideoCaptionNoteGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: VideoCaptionNoteGroupByArgs['orderBy'] }
      : { orderBy?: VideoCaptionNoteGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, VideoCaptionNoteGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetVideoCaptionNoteGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the VideoCaptionNote model
 */
readonly fields: VideoCaptionNoteFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for VideoCaptionNote.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__VideoCaptionNoteClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  caption<T extends Prisma.VideoCaptionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.VideoCaptionDefaultArgs<ExtArgs>>): Prisma.Prisma__VideoCaptionClient<runtime.Types.Result.GetResult<Prisma.$VideoCaptionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the VideoCaptionNote model
 */
export interface VideoCaptionNoteFieldRefs {
  readonly id: Prisma.FieldRef<"VideoCaptionNote", 'String'>
  readonly videoCaptionId: Prisma.FieldRef<"VideoCaptionNote", 'String'>
  readonly words: Prisma.FieldRef<"VideoCaptionNote", 'String'>
  readonly notes: Prisma.FieldRef<"VideoCaptionNote", 'String'>
  readonly userId: Prisma.FieldRef<"VideoCaptionNote", 'String'>
  readonly createdAt: Prisma.FieldRef<"VideoCaptionNote", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"VideoCaptionNote", 'DateTime'>
}
    

// Custom InputTypes
/**
 * VideoCaptionNote findUnique
 */
export type VideoCaptionNoteFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoCaptionNote
   */
  select?: Prisma.VideoCaptionNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoCaptionNote
   */
  omit?: Prisma.VideoCaptionNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoCaptionNoteInclude<ExtArgs> | null
  /**
   * Filter, which VideoCaptionNote to fetch.
   */
  where: Prisma.VideoCaptionNoteWhereUniqueInput
}

/**
 * VideoCaptionNote findUniqueOrThrow
 */
export type VideoCaptionNoteFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoCaptionNote
   */
  select?: Prisma.VideoCaptionNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoCaptionNote
   */
  omit?: Prisma.VideoCaptionNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoCaptionNoteInclude<ExtArgs> | null
  /**
   * Filter, which VideoCaptionNote to fetch.
   */
  where: Prisma.VideoCaptionNoteWhereUniqueInput
}

/**
 * VideoCaptionNote findFirst
 */
export type VideoCaptionNoteFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoCaptionNote
   */
  select?: Prisma.VideoCaptionNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoCaptionNote
   */
  omit?: Prisma.VideoCaptionNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoCaptionNoteInclude<ExtArgs> | null
  /**
   * Filter, which VideoCaptionNote to fetch.
   */
  where?: Prisma.VideoCaptionNoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VideoCaptionNotes to fetch.
   */
  orderBy?: Prisma.VideoCaptionNoteOrderByWithRelationInput | Prisma.VideoCaptionNoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VideoCaptionNotes.
   */
  cursor?: Prisma.VideoCaptionNoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VideoCaptionNotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VideoCaptionNotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VideoCaptionNotes.
   */
  distinct?: Prisma.VideoCaptionNoteScalarFieldEnum | Prisma.VideoCaptionNoteScalarFieldEnum[]
}

/**
 * VideoCaptionNote findFirstOrThrow
 */
export type VideoCaptionNoteFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoCaptionNote
   */
  select?: Prisma.VideoCaptionNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoCaptionNote
   */
  omit?: Prisma.VideoCaptionNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoCaptionNoteInclude<ExtArgs> | null
  /**
   * Filter, which VideoCaptionNote to fetch.
   */
  where?: Prisma.VideoCaptionNoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VideoCaptionNotes to fetch.
   */
  orderBy?: Prisma.VideoCaptionNoteOrderByWithRelationInput | Prisma.VideoCaptionNoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VideoCaptionNotes.
   */
  cursor?: Prisma.VideoCaptionNoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VideoCaptionNotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VideoCaptionNotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VideoCaptionNotes.
   */
  distinct?: Prisma.VideoCaptionNoteScalarFieldEnum | Prisma.VideoCaptionNoteScalarFieldEnum[]
}

/**
 * VideoCaptionNote findMany
 */
export type VideoCaptionNoteFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoCaptionNote
   */
  select?: Prisma.VideoCaptionNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoCaptionNote
   */
  omit?: Prisma.VideoCaptionNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoCaptionNoteInclude<ExtArgs> | null
  /**
   * Filter, which VideoCaptionNotes to fetch.
   */
  where?: Prisma.VideoCaptionNoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VideoCaptionNotes to fetch.
   */
  orderBy?: Prisma.VideoCaptionNoteOrderByWithRelationInput | Prisma.VideoCaptionNoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing VideoCaptionNotes.
   */
  cursor?: Prisma.VideoCaptionNoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VideoCaptionNotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VideoCaptionNotes.
   */
  skip?: number
  distinct?: Prisma.VideoCaptionNoteScalarFieldEnum | Prisma.VideoCaptionNoteScalarFieldEnum[]
}

/**
 * VideoCaptionNote create
 */
export type VideoCaptionNoteCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoCaptionNote
   */
  select?: Prisma.VideoCaptionNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoCaptionNote
   */
  omit?: Prisma.VideoCaptionNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoCaptionNoteInclude<ExtArgs> | null
  /**
   * The data needed to create a VideoCaptionNote.
   */
  data: Prisma.XOR<Prisma.VideoCaptionNoteCreateInput, Prisma.VideoCaptionNoteUncheckedCreateInput>
}

/**
 * VideoCaptionNote createMany
 */
export type VideoCaptionNoteCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many VideoCaptionNotes.
   */
  data: Prisma.VideoCaptionNoteCreateManyInput | Prisma.VideoCaptionNoteCreateManyInput[]
}

/**
 * VideoCaptionNote createManyAndReturn
 */
export type VideoCaptionNoteCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoCaptionNote
   */
  select?: Prisma.VideoCaptionNoteSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the VideoCaptionNote
   */
  omit?: Prisma.VideoCaptionNoteOmit<ExtArgs> | null
  /**
   * The data used to create many VideoCaptionNotes.
   */
  data: Prisma.VideoCaptionNoteCreateManyInput | Prisma.VideoCaptionNoteCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoCaptionNoteIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * VideoCaptionNote update
 */
export type VideoCaptionNoteUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoCaptionNote
   */
  select?: Prisma.VideoCaptionNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoCaptionNote
   */
  omit?: Prisma.VideoCaptionNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoCaptionNoteInclude<ExtArgs> | null
  /**
   * The data needed to update a VideoCaptionNote.
   */
  data: Prisma.XOR<Prisma.VideoCaptionNoteUpdateInput, Prisma.VideoCaptionNoteUncheckedUpdateInput>
  /**
   * Choose, which VideoCaptionNote to update.
   */
  where: Prisma.VideoCaptionNoteWhereUniqueInput
}

/**
 * VideoCaptionNote updateMany
 */
export type VideoCaptionNoteUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update VideoCaptionNotes.
   */
  data: Prisma.XOR<Prisma.VideoCaptionNoteUpdateManyMutationInput, Prisma.VideoCaptionNoteUncheckedUpdateManyInput>
  /**
   * Filter which VideoCaptionNotes to update
   */
  where?: Prisma.VideoCaptionNoteWhereInput
  /**
   * Limit how many VideoCaptionNotes to update.
   */
  limit?: number
}

/**
 * VideoCaptionNote updateManyAndReturn
 */
export type VideoCaptionNoteUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoCaptionNote
   */
  select?: Prisma.VideoCaptionNoteSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the VideoCaptionNote
   */
  omit?: Prisma.VideoCaptionNoteOmit<ExtArgs> | null
  /**
   * The data used to update VideoCaptionNotes.
   */
  data: Prisma.XOR<Prisma.VideoCaptionNoteUpdateManyMutationInput, Prisma.VideoCaptionNoteUncheckedUpdateManyInput>
  /**
   * Filter which VideoCaptionNotes to update
   */
  where?: Prisma.VideoCaptionNoteWhereInput
  /**
   * Limit how many VideoCaptionNotes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoCaptionNoteIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * VideoCaptionNote upsert
 */
export type VideoCaptionNoteUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoCaptionNote
   */
  select?: Prisma.VideoCaptionNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoCaptionNote
   */
  omit?: Prisma.VideoCaptionNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoCaptionNoteInclude<ExtArgs> | null
  /**
   * The filter to search for the VideoCaptionNote to update in case it exists.
   */
  where: Prisma.VideoCaptionNoteWhereUniqueInput
  /**
   * In case the VideoCaptionNote found by the `where` argument doesn't exist, create a new VideoCaptionNote with this data.
   */
  create: Prisma.XOR<Prisma.VideoCaptionNoteCreateInput, Prisma.VideoCaptionNoteUncheckedCreateInput>
  /**
   * In case the VideoCaptionNote was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.VideoCaptionNoteUpdateInput, Prisma.VideoCaptionNoteUncheckedUpdateInput>
}

/**
 * VideoCaptionNote delete
 */
export type VideoCaptionNoteDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoCaptionNote
   */
  select?: Prisma.VideoCaptionNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoCaptionNote
   */
  omit?: Prisma.VideoCaptionNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoCaptionNoteInclude<ExtArgs> | null
  /**
   * Filter which VideoCaptionNote to delete.
   */
  where: Prisma.VideoCaptionNoteWhereUniqueInput
}

/**
 * VideoCaptionNote deleteMany
 */
export type VideoCaptionNoteDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VideoCaptionNotes to delete
   */
  where?: Prisma.VideoCaptionNoteWhereInput
  /**
   * Limit how many VideoCaptionNotes to delete.
   */
  limit?: number
}

/**
 * VideoCaptionNote without action
 */
export type VideoCaptionNoteDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoCaptionNote
   */
  select?: Prisma.VideoCaptionNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoCaptionNote
   */
  omit?: Prisma.VideoCaptionNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoCaptionNoteInclude<ExtArgs> | null
}
