
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `VideoPhraseNote` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model VideoPhraseNote
 * 
 */
export type VideoPhraseNoteModel = runtime.Types.Result.DefaultSelection<Prisma.$VideoPhraseNotePayload>

export type AggregateVideoPhraseNote = {
  _count: VideoPhraseNoteCountAggregateOutputType | null
  _min: VideoPhraseNoteMinAggregateOutputType | null
  _max: VideoPhraseNoteMaxAggregateOutputType | null
}

export type VideoPhraseNoteMinAggregateOutputType = {
  id: string | null
  videoTrainingItemId: string | null
  captionId: string | null
  phrase: string | null
  note: string | null
  userId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type VideoPhraseNoteMaxAggregateOutputType = {
  id: string | null
  videoTrainingItemId: string | null
  captionId: string | null
  phrase: string | null
  note: string | null
  userId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type VideoPhraseNoteCountAggregateOutputType = {
  id: number
  videoTrainingItemId: number
  captionId: number
  phrase: number
  note: number
  userId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type VideoPhraseNoteMinAggregateInputType = {
  id?: true
  videoTrainingItemId?: true
  captionId?: true
  phrase?: true
  note?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
}

export type VideoPhraseNoteMaxAggregateInputType = {
  id?: true
  videoTrainingItemId?: true
  captionId?: true
  phrase?: true
  note?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
}

export type VideoPhraseNoteCountAggregateInputType = {
  id?: true
  videoTrainingItemId?: true
  captionId?: true
  phrase?: true
  note?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type VideoPhraseNoteAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VideoPhraseNote to aggregate.
   */
  where?: Prisma.VideoPhraseNoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VideoPhraseNotes to fetch.
   */
  orderBy?: Prisma.VideoPhraseNoteOrderByWithRelationInput | Prisma.VideoPhraseNoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.VideoPhraseNoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VideoPhraseNotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VideoPhraseNotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned VideoPhraseNotes
  **/
  _count?: true | VideoPhraseNoteCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: VideoPhraseNoteMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: VideoPhraseNoteMaxAggregateInputType
}

export type GetVideoPhraseNoteAggregateType<T extends VideoPhraseNoteAggregateArgs> = {
      [P in keyof T & keyof AggregateVideoPhraseNote]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateVideoPhraseNote[P]>
    : Prisma.GetScalarType<T[P], AggregateVideoPhraseNote[P]>
}




export type VideoPhraseNoteGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VideoPhraseNoteWhereInput
  orderBy?: Prisma.VideoPhraseNoteOrderByWithAggregationInput | Prisma.VideoPhraseNoteOrderByWithAggregationInput[]
  by: Prisma.VideoPhraseNoteScalarFieldEnum[] | Prisma.VideoPhraseNoteScalarFieldEnum
  having?: Prisma.VideoPhraseNoteScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: VideoPhraseNoteCountAggregateInputType | true
  _min?: VideoPhraseNoteMinAggregateInputType
  _max?: VideoPhraseNoteMaxAggregateInputType
}

export type VideoPhraseNoteGroupByOutputType = {
  id: string
  videoTrainingItemId: string
  captionId: string | null
  phrase: string
  note: string
  userId: string
  createdAt: Date
  updatedAt: Date
  _count: VideoPhraseNoteCountAggregateOutputType | null
  _min: VideoPhraseNoteMinAggregateOutputType | null
  _max: VideoPhraseNoteMaxAggregateOutputType | null
}

type GetVideoPhraseNoteGroupByPayload<T extends VideoPhraseNoteGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<VideoPhraseNoteGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof VideoPhraseNoteGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], VideoPhraseNoteGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], VideoPhraseNoteGroupByOutputType[P]>
      }
    >
  >



export type VideoPhraseNoteWhereInput = {
  AND?: Prisma.VideoPhraseNoteWhereInput | Prisma.VideoPhraseNoteWhereInput[]
  OR?: Prisma.VideoPhraseNoteWhereInput[]
  NOT?: Prisma.VideoPhraseNoteWhereInput | Prisma.VideoPhraseNoteWhereInput[]
  id?: Prisma.StringFilter<"VideoPhraseNote"> | string
  videoTrainingItemId?: Prisma.StringFilter<"VideoPhraseNote"> | string
  captionId?: Prisma.StringNullableFilter<"VideoPhraseNote"> | string | null
  phrase?: Prisma.StringFilter<"VideoPhraseNote"> | string
  note?: Prisma.StringFilter<"VideoPhraseNote"> | string
  userId?: Prisma.StringFilter<"VideoPhraseNote"> | string
  createdAt?: Prisma.DateTimeFilter<"VideoPhraseNote"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"VideoPhraseNote"> | Date | string
  videoTrainingItem?: Prisma.XOR<Prisma.VideoTrainingItemScalarRelationFilter, Prisma.VideoTrainingItemWhereInput>
  caption?: Prisma.XOR<Prisma.VideoCaptionNullableScalarRelationFilter, Prisma.VideoCaptionWhereInput> | null
}

export type VideoPhraseNoteOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  videoTrainingItemId?: Prisma.SortOrder
  captionId?: Prisma.SortOrderInput | Prisma.SortOrder
  phrase?: Prisma.SortOrder
  note?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  videoTrainingItem?: Prisma.VideoTrainingItemOrderByWithRelationInput
  caption?: Prisma.VideoCaptionOrderByWithRelationInput
}

export type VideoPhraseNoteWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.VideoPhraseNoteWhereInput | Prisma.VideoPhraseNoteWhereInput[]
  OR?: Prisma.VideoPhraseNoteWhereInput[]
  NOT?: Prisma.VideoPhraseNoteWhereInput | Prisma.VideoPhraseNoteWhereInput[]
  videoTrainingItemId?: Prisma.StringFilter<"VideoPhraseNote"> | string
  captionId?: Prisma.StringNullableFilter<"VideoPhraseNote"> | string | null
  phrase?: Prisma.StringFilter<"VideoPhraseNote"> | string
  note?: Prisma.StringFilter<"VideoPhraseNote"> | string
  userId?: Prisma.StringFilter<"VideoPhraseNote"> | string
  createdAt?: Prisma.DateTimeFilter<"VideoPhraseNote"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"VideoPhraseNote"> | Date | string
  videoTrainingItem?: Prisma.XOR<Prisma.VideoTrainingItemScalarRelationFilter, Prisma.VideoTrainingItemWhereInput>
  caption?: Prisma.XOR<Prisma.VideoCaptionNullableScalarRelationFilter, Prisma.VideoCaptionWhereInput> | null
}, "id">

export type VideoPhraseNoteOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  videoTrainingItemId?: Prisma.SortOrder
  captionId?: Prisma.SortOrderInput | Prisma.SortOrder
  phrase?: Prisma.SortOrder
  note?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.VideoPhraseNoteCountOrderByAggregateInput
  _max?: Prisma.VideoPhraseNoteMaxOrderByAggregateInput
  _min?: Prisma.VideoPhraseNoteMinOrderByAggregateInput
}

export type VideoPhraseNoteScalarWhereWithAggregatesInput = {
  AND?: Prisma.VideoPhraseNoteScalarWhereWithAggregatesInput | Prisma.VideoPhraseNoteScalarWhereWithAggregatesInput[]
  OR?: Prisma.VideoPhraseNoteScalarWhereWithAggregatesInput[]
  NOT?: Prisma.VideoPhraseNoteScalarWhereWithAggregatesInput | Prisma.VideoPhraseNoteScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"VideoPhraseNote"> | string
  videoTrainingItemId?: Prisma.StringWithAggregatesFilter<"VideoPhraseNote"> | string
  captionId?: Prisma.StringNullableWithAggregatesFilter<"VideoPhraseNote"> | string | null
  phrase?: Prisma.StringWithAggregatesFilter<"VideoPhraseNote"> | string
  note?: Prisma.StringWithAggregatesFilter<"VideoPhraseNote"> | string
  userId?: Prisma.StringWithAggregatesFilter<"VideoPhraseNote"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"VideoPhraseNote"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"VideoPhraseNote"> | Date | string
}

export type VideoPhraseNoteCreateInput = {
  id?: string
  phrase: string
  note?: string
  userId?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  videoTrainingItem: Prisma.VideoTrainingItemCreateNestedOneWithoutPhraseNotesInput
  caption?: Prisma.VideoCaptionCreateNestedOneWithoutPhraseNotesInput
}

export type VideoPhraseNoteUncheckedCreateInput = {
  id?: string
  videoTrainingItemId: string
  captionId?: string | null
  phrase: string
  note?: string
  userId?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type VideoPhraseNoteUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  phrase?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  videoTrainingItem?: Prisma.VideoTrainingItemUpdateOneRequiredWithoutPhraseNotesNestedInput
  caption?: Prisma.VideoCaptionUpdateOneWithoutPhraseNotesNestedInput
}

export type VideoPhraseNoteUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  videoTrainingItemId?: Prisma.StringFieldUpdateOperationsInput | string
  captionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phrase?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VideoPhraseNoteCreateManyInput = {
  id?: string
  videoTrainingItemId: string
  captionId?: string | null
  phrase: string
  note?: string
  userId?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type VideoPhraseNoteUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  phrase?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VideoPhraseNoteUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  videoTrainingItemId?: Prisma.StringFieldUpdateOperationsInput | string
  captionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phrase?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VideoPhraseNoteListRelationFilter = {
  every?: Prisma.VideoPhraseNoteWhereInput
  some?: Prisma.VideoPhraseNoteWhereInput
  none?: Prisma.VideoPhraseNoteWhereInput
}

export type VideoPhraseNoteOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type VideoPhraseNoteCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  videoTrainingItemId?: Prisma.SortOrder
  captionId?: Prisma.SortOrder
  phrase?: Prisma.SortOrder
  note?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type VideoPhraseNoteMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  videoTrainingItemId?: Prisma.SortOrder
  captionId?: Prisma.SortOrder
  phrase?: Prisma.SortOrder
  note?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type VideoPhraseNoteMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  videoTrainingItemId?: Prisma.SortOrder
  captionId?: Prisma.SortOrder
  phrase?: Prisma.SortOrder
  note?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type VideoPhraseNoteCreateNestedManyWithoutVideoTrainingItemInput = {
  create?: Prisma.XOR<Prisma.VideoPhraseNoteCreateWithoutVideoTrainingItemInput, Prisma.VideoPhraseNoteUncheckedCreateWithoutVideoTrainingItemInput> | Prisma.VideoPhraseNoteCreateWithoutVideoTrainingItemInput[] | Prisma.VideoPhraseNoteUncheckedCreateWithoutVideoTrainingItemInput[]
  connectOrCreate?: Prisma.VideoPhraseNoteCreateOrConnectWithoutVideoTrainingItemInput | Prisma.VideoPhraseNoteCreateOrConnectWithoutVideoTrainingItemInput[]
  createMany?: Prisma.VideoPhraseNoteCreateManyVideoTrainingItemInputEnvelope
  connect?: Prisma.VideoPhraseNoteWhereUniqueInput | Prisma.VideoPhraseNoteWhereUniqueInput[]
}

export type VideoPhraseNoteUncheckedCreateNestedManyWithoutVideoTrainingItemInput = {
  create?: Prisma.XOR<Prisma.VideoPhraseNoteCreateWithoutVideoTrainingItemInput, Prisma.VideoPhraseNoteUncheckedCreateWithoutVideoTrainingItemInput> | Prisma.VideoPhraseNoteCreateWithoutVideoTrainingItemInput[] | Prisma.VideoPhraseNoteUncheckedCreateWithoutVideoTrainingItemInput[]
  connectOrCreate?: Prisma.VideoPhraseNoteCreateOrConnectWithoutVideoTrainingItemInput | Prisma.VideoPhraseNoteCreateOrConnectWithoutVideoTrainingItemInput[]
  createMany?: Prisma.VideoPhraseNoteCreateManyVideoTrainingItemInputEnvelope
  connect?: Prisma.VideoPhraseNoteWhereUniqueInput | Prisma.VideoPhraseNoteWhereUniqueInput[]
}

export type VideoPhraseNoteUpdateManyWithoutVideoTrainingItemNestedInput = {
  create?: Prisma.XOR<Prisma.VideoPhraseNoteCreateWithoutVideoTrainingItemInput, Prisma.VideoPhraseNoteUncheckedCreateWithoutVideoTrainingItemInput> | Prisma.VideoPhraseNoteCreateWithoutVideoTrainingItemInput[] | Prisma.VideoPhraseNoteUncheckedCreateWithoutVideoTrainingItemInput[]
  connectOrCreate?: Prisma.VideoPhraseNoteCreateOrConnectWithoutVideoTrainingItemInput | Prisma.VideoPhraseNoteCreateOrConnectWithoutVideoTrainingItemInput[]
  upsert?: Prisma.VideoPhraseNoteUpsertWithWhereUniqueWithoutVideoTrainingItemInput | Prisma.VideoPhraseNoteUpsertWithWhereUniqueWithoutVideoTrainingItemInput[]
  createMany?: Prisma.VideoPhraseNoteCreateManyVideoTrainingItemInputEnvelope
  set?: Prisma.VideoPhraseNoteWhereUniqueInput | Prisma.VideoPhraseNoteWhereUniqueInput[]
  disconnect?: Prisma.VideoPhraseNoteWhereUniqueInput | Prisma.VideoPhraseNoteWhereUniqueInput[]
  delete?: Prisma.VideoPhraseNoteWhereUniqueInput | Prisma.VideoPhraseNoteWhereUniqueInput[]
  connect?: Prisma.VideoPhraseNoteWhereUniqueInput | Prisma.VideoPhraseNoteWhereUniqueInput[]
  update?: Prisma.VideoPhraseNoteUpdateWithWhereUniqueWithoutVideoTrainingItemInput | Prisma.VideoPhraseNoteUpdateWithWhereUniqueWithoutVideoTrainingItemInput[]
  updateMany?: Prisma.VideoPhraseNoteUpdateManyWithWhereWithoutVideoTrainingItemInput | Prisma.VideoPhraseNoteUpdateManyWithWhereWithoutVideoTrainingItemInput[]
  deleteMany?: Prisma.VideoPhraseNoteScalarWhereInput | Prisma.VideoPhraseNoteScalarWhereInput[]
}

export type VideoPhraseNoteUncheckedUpdateManyWithoutVideoTrainingItemNestedInput = {
  create?: Prisma.XOR<Prisma.VideoPhraseNoteCreateWithoutVideoTrainingItemInput, Prisma.VideoPhraseNoteUncheckedCreateWithoutVideoTrainingItemInput> | Prisma.VideoPhraseNoteCreateWithoutVideoTrainingItemInput[] | Prisma.VideoPhraseNoteUncheckedCreateWithoutVideoTrainingItemInput[]
  connectOrCreate?: Prisma.VideoPhraseNoteCreateOrConnectWithoutVideoTrainingItemInput | Prisma.VideoPhraseNoteCreateOrConnectWithoutVideoTrainingItemInput[]
  upsert?: Prisma.VideoPhraseNoteUpsertWithWhereUniqueWithoutVideoTrainingItemInput | Prisma.VideoPhraseNoteUpsertWithWhereUniqueWithoutVideoTrainingItemInput[]
  createMany?: Prisma.VideoPhraseNoteCreateManyVideoTrainingItemInputEnvelope
  set?: Prisma.VideoPhraseNoteWhereUniqueInput | Prisma.VideoPhraseNoteWhereUniqueInput[]
  disconnect?: Prisma.VideoPhraseNoteWhereUniqueInput | Prisma.VideoPhraseNoteWhereUniqueInput[]
  delete?: Prisma.VideoPhraseNoteWhereUniqueInput | Prisma.VideoPhraseNoteWhereUniqueInput[]
  connect?: Prisma.VideoPhraseNoteWhereUniqueInput | Prisma.VideoPhraseNoteWhereUniqueInput[]
  update?: Prisma.VideoPhraseNoteUpdateWithWhereUniqueWithoutVideoTrainingItemInput | Prisma.VideoPhraseNoteUpdateWithWhereUniqueWithoutVideoTrainingItemInput[]
  updateMany?: Prisma.VideoPhraseNoteUpdateManyWithWhereWithoutVideoTrainingItemInput | Prisma.VideoPhraseNoteUpdateManyWithWhereWithoutVideoTrainingItemInput[]
  deleteMany?: Prisma.VideoPhraseNoteScalarWhereInput | Prisma.VideoPhraseNoteScalarWhereInput[]
}

export type VideoPhraseNoteCreateNestedManyWithoutCaptionInput = {
  create?: Prisma.XOR<Prisma.VideoPhraseNoteCreateWithoutCaptionInput, Prisma.VideoPhraseNoteUncheckedCreateWithoutCaptionInput> | Prisma.VideoPhraseNoteCreateWithoutCaptionInput[] | Prisma.VideoPhraseNoteUncheckedCreateWithoutCaptionInput[]
  connectOrCreate?: Prisma.VideoPhraseNoteCreateOrConnectWithoutCaptionInput | Prisma.VideoPhraseNoteCreateOrConnectWithoutCaptionInput[]
  createMany?: Prisma.VideoPhraseNoteCreateManyCaptionInputEnvelope
  connect?: Prisma.VideoPhraseNoteWhereUniqueInput | Prisma.VideoPhraseNoteWhereUniqueInput[]
}

export type VideoPhraseNoteUncheckedCreateNestedManyWithoutCaptionInput = {
  create?: Prisma.XOR<Prisma.VideoPhraseNoteCreateWithoutCaptionInput, Prisma.VideoPhraseNoteUncheckedCreateWithoutCaptionInput> | Prisma.VideoPhraseNoteCreateWithoutCaptionInput[] | Prisma.VideoPhraseNoteUncheckedCreateWithoutCaptionInput[]
  connectOrCreate?: Prisma.VideoPhraseNoteCreateOrConnectWithoutCaptionInput | Prisma.VideoPhraseNoteCreateOrConnectWithoutCaptionInput[]
  createMany?: Prisma.VideoPhraseNoteCreateManyCaptionInputEnvelope
  connect?: Prisma.VideoPhraseNoteWhereUniqueInput | Prisma.VideoPhraseNoteWhereUniqueInput[]
}

export type VideoPhraseNoteUpdateManyWithoutCaptionNestedInput = {
  create?: Prisma.XOR<Prisma.VideoPhraseNoteCreateWithoutCaptionInput, Prisma.VideoPhraseNoteUncheckedCreateWithoutCaptionInput> | Prisma.VideoPhraseNoteCreateWithoutCaptionInput[] | Prisma.VideoPhraseNoteUncheckedCreateWithoutCaptionInput[]
  connectOrCreate?: Prisma.VideoPhraseNoteCreateOrConnectWithoutCaptionInput | Prisma.VideoPhraseNoteCreateOrConnectWithoutCaptionInput[]
  upsert?: Prisma.VideoPhraseNoteUpsertWithWhereUniqueWithoutCaptionInput | Prisma.VideoPhraseNoteUpsertWithWhereUniqueWithoutCaptionInput[]
  createMany?: Prisma.VideoPhraseNoteCreateManyCaptionInputEnvelope
  set?: Prisma.VideoPhraseNoteWhereUniqueInput | Prisma.VideoPhraseNoteWhereUniqueInput[]
  disconnect?: Prisma.VideoPhraseNoteWhereUniqueInput | Prisma.VideoPhraseNoteWhereUniqueInput[]
  delete?: Prisma.VideoPhraseNoteWhereUniqueInput | Prisma.VideoPhraseNoteWhereUniqueInput[]
  connect?: Prisma.VideoPhraseNoteWhereUniqueInput | Prisma.VideoPhraseNoteWhereUniqueInput[]
  update?: Prisma.VideoPhraseNoteUpdateWithWhereUniqueWithoutCaptionInput | Prisma.VideoPhraseNoteUpdateWithWhereUniqueWithoutCaptionInput[]
  updateMany?: Prisma.VideoPhraseNoteUpdateManyWithWhereWithoutCaptionInput | Prisma.VideoPhraseNoteUpdateManyWithWhereWithoutCaptionInput[]
  deleteMany?: Prisma.VideoPhraseNoteScalarWhereInput | Prisma.VideoPhraseNoteScalarWhereInput[]
}

export type VideoPhraseNoteUncheckedUpdateManyWithoutCaptionNestedInput = {
  create?: Prisma.XOR<Prisma.VideoPhraseNoteCreateWithoutCaptionInput, Prisma.VideoPhraseNoteUncheckedCreateWithoutCaptionInput> | Prisma.VideoPhraseNoteCreateWithoutCaptionInput[] | Prisma.VideoPhraseNoteUncheckedCreateWithoutCaptionInput[]
  connectOrCreate?: Prisma.VideoPhraseNoteCreateOrConnectWithoutCaptionInput | Prisma.VideoPhraseNoteCreateOrConnectWithoutCaptionInput[]
  upsert?: Prisma.VideoPhraseNoteUpsertWithWhereUniqueWithoutCaptionInput | Prisma.VideoPhraseNoteUpsertWithWhereUniqueWithoutCaptionInput[]
  createMany?: Prisma.VideoPhraseNoteCreateManyCaptionInputEnvelope
  set?: Prisma.VideoPhraseNoteWhereUniqueInput | Prisma.VideoPhraseNoteWhereUniqueInput[]
  disconnect?: Prisma.VideoPhraseNoteWhereUniqueInput | Prisma.VideoPhraseNoteWhereUniqueInput[]
  delete?: Prisma.VideoPhraseNoteWhereUniqueInput | Prisma.VideoPhraseNoteWhereUniqueInput[]
  connect?: Prisma.VideoPhraseNoteWhereUniqueInput | Prisma.VideoPhraseNoteWhereUniqueInput[]
  update?: Prisma.VideoPhraseNoteUpdateWithWhereUniqueWithoutCaptionInput | Prisma.VideoPhraseNoteUpdateWithWhereUniqueWithoutCaptionInput[]
  updateMany?: Prisma.VideoPhraseNoteUpdateManyWithWhereWithoutCaptionInput | Prisma.VideoPhraseNoteUpdateManyWithWhereWithoutCaptionInput[]
  deleteMany?: Prisma.VideoPhraseNoteScalarWhereInput | Prisma.VideoPhraseNoteScalarWhereInput[]
}

export type VideoPhraseNoteCreateWithoutVideoTrainingItemInput = {
  id?: string
  phrase: string
  note?: string
  userId?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  caption?: Prisma.VideoCaptionCreateNestedOneWithoutPhraseNotesInput
}

export type VideoPhraseNoteUncheckedCreateWithoutVideoTrainingItemInput = {
  id?: string
  captionId?: string | null
  phrase: string
  note?: string
  userId?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type VideoPhraseNoteCreateOrConnectWithoutVideoTrainingItemInput = {
  where: Prisma.VideoPhraseNoteWhereUniqueInput
  create: Prisma.XOR<Prisma.VideoPhraseNoteCreateWithoutVideoTrainingItemInput, Prisma.VideoPhraseNoteUncheckedCreateWithoutVideoTrainingItemInput>
}

export type VideoPhraseNoteCreateManyVideoTrainingItemInputEnvelope = {
  data: Prisma.VideoPhraseNoteCreateManyVideoTrainingItemInput | Prisma.VideoPhraseNoteCreateManyVideoTrainingItemInput[]
}

export type VideoPhraseNoteUpsertWithWhereUniqueWithoutVideoTrainingItemInput = {
  where: Prisma.VideoPhraseNoteWhereUniqueInput
  update: Prisma.XOR<Prisma.VideoPhraseNoteUpdateWithoutVideoTrainingItemInput, Prisma.VideoPhraseNoteUncheckedUpdateWithoutVideoTrainingItemInput>
  create: Prisma.XOR<Prisma.VideoPhraseNoteCreateWithoutVideoTrainingItemInput, Prisma.VideoPhraseNoteUncheckedCreateWithoutVideoTrainingItemInput>
}

export type VideoPhraseNoteUpdateWithWhereUniqueWithoutVideoTrainingItemInput = {
  where: Prisma.VideoPhraseNoteWhereUniqueInput
  data: Prisma.XOR<Prisma.VideoPhraseNoteUpdateWithoutVideoTrainingItemInput, Prisma.VideoPhraseNoteUncheckedUpdateWithoutVideoTrainingItemInput>
}

export type VideoPhraseNoteUpdateManyWithWhereWithoutVideoTrainingItemInput = {
  where: Prisma.VideoPhraseNoteScalarWhereInput
  data: Prisma.XOR<Prisma.VideoPhraseNoteUpdateManyMutationInput, Prisma.VideoPhraseNoteUncheckedUpdateManyWithoutVideoTrainingItemInput>
}

export type VideoPhraseNoteScalarWhereInput = {
  AND?: Prisma.VideoPhraseNoteScalarWhereInput | Prisma.VideoPhraseNoteScalarWhereInput[]
  OR?: Prisma.VideoPhraseNoteScalarWhereInput[]
  NOT?: Prisma.VideoPhraseNoteScalarWhereInput | Prisma.VideoPhraseNoteScalarWhereInput[]
  id?: Prisma.StringFilter<"VideoPhraseNote"> | string
  videoTrainingItemId?: Prisma.StringFilter<"VideoPhraseNote"> | string
  captionId?: Prisma.StringNullableFilter<"VideoPhraseNote"> | string | null
  phrase?: Prisma.StringFilter<"VideoPhraseNote"> | string
  note?: Prisma.StringFilter<"VideoPhraseNote"> | string
  userId?: Prisma.StringFilter<"VideoPhraseNote"> | string
  createdAt?: Prisma.DateTimeFilter<"VideoPhraseNote"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"VideoPhraseNote"> | Date | string
}

export type VideoPhraseNoteCreateWithoutCaptionInput = {
  id?: string
  phrase: string
  note?: string
  userId?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  videoTrainingItem: Prisma.VideoTrainingItemCreateNestedOneWithoutPhraseNotesInput
}

export type VideoPhraseNoteUncheckedCreateWithoutCaptionInput = {
  id?: string
  videoTrainingItemId: string
  phrase: string
  note?: string
  userId?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type VideoPhraseNoteCreateOrConnectWithoutCaptionInput = {
  where: Prisma.VideoPhraseNoteWhereUniqueInput
  create: Prisma.XOR<Prisma.VideoPhraseNoteCreateWithoutCaptionInput, Prisma.VideoPhraseNoteUncheckedCreateWithoutCaptionInput>
}

export type VideoPhraseNoteCreateManyCaptionInputEnvelope = {
  data: Prisma.VideoPhraseNoteCreateManyCaptionInput | Prisma.VideoPhraseNoteCreateManyCaptionInput[]
}

export type VideoPhraseNoteUpsertWithWhereUniqueWithoutCaptionInput = {
  where: Prisma.VideoPhraseNoteWhereUniqueInput
  update: Prisma.XOR<Prisma.VideoPhraseNoteUpdateWithoutCaptionInput, Prisma.VideoPhraseNoteUncheckedUpdateWithoutCaptionInput>
  create: Prisma.XOR<Prisma.VideoPhraseNoteCreateWithoutCaptionInput, Prisma.VideoPhraseNoteUncheckedCreateWithoutCaptionInput>
}

export type VideoPhraseNoteUpdateWithWhereUniqueWithoutCaptionInput = {
  where: Prisma.VideoPhraseNoteWhereUniqueInput
  data: Prisma.XOR<Prisma.VideoPhraseNoteUpdateWithoutCaptionInput, Prisma.VideoPhraseNoteUncheckedUpdateWithoutCaptionInput>
}

export type VideoPhraseNoteUpdateManyWithWhereWithoutCaptionInput = {
  where: Prisma.VideoPhraseNoteScalarWhereInput
  data: Prisma.XOR<Prisma.VideoPhraseNoteUpdateManyMutationInput, Prisma.VideoPhraseNoteUncheckedUpdateManyWithoutCaptionInput>
}

export type VideoPhraseNoteCreateManyVideoTrainingItemInput = {
  id?: string
  captionId?: string | null
  phrase: string
  note?: string
  userId?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type VideoPhraseNoteUpdateWithoutVideoTrainingItemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  phrase?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  caption?: Prisma.VideoCaptionUpdateOneWithoutPhraseNotesNestedInput
}

export type VideoPhraseNoteUncheckedUpdateWithoutVideoTrainingItemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  captionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phrase?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VideoPhraseNoteUncheckedUpdateManyWithoutVideoTrainingItemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  captionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phrase?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VideoPhraseNoteCreateManyCaptionInput = {
  id?: string
  videoTrainingItemId: string
  phrase: string
  note?: string
  userId?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type VideoPhraseNoteUpdateWithoutCaptionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  phrase?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  videoTrainingItem?: Prisma.VideoTrainingItemUpdateOneRequiredWithoutPhraseNotesNestedInput
}

export type VideoPhraseNoteUncheckedUpdateWithoutCaptionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  videoTrainingItemId?: Prisma.StringFieldUpdateOperationsInput | string
  phrase?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VideoPhraseNoteUncheckedUpdateManyWithoutCaptionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  videoTrainingItemId?: Prisma.StringFieldUpdateOperationsInput | string
  phrase?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type VideoPhraseNoteSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  videoTrainingItemId?: boolean
  captionId?: boolean
  phrase?: boolean
  note?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  videoTrainingItem?: boolean | Prisma.VideoTrainingItemDefaultArgs<ExtArgs>
  caption?: boolean | Prisma.VideoPhraseNote$captionArgs<ExtArgs>
}, ExtArgs["result"]["videoPhraseNote"]>

export type VideoPhraseNoteSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  videoTrainingItemId?: boolean
  captionId?: boolean
  phrase?: boolean
  note?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  videoTrainingItem?: boolean | Prisma.VideoTrainingItemDefaultArgs<ExtArgs>
  caption?: boolean | Prisma.VideoPhraseNote$captionArgs<ExtArgs>
}, ExtArgs["result"]["videoPhraseNote"]>

export type VideoPhraseNoteSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  videoTrainingItemId?: boolean
  captionId?: boolean
  phrase?: boolean
  note?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  videoTrainingItem?: boolean | Prisma.VideoTrainingItemDefaultArgs<ExtArgs>
  caption?: boolean | Prisma.VideoPhraseNote$captionArgs<ExtArgs>
}, ExtArgs["result"]["videoPhraseNote"]>

export type VideoPhraseNoteSelectScalar = {
  id?: boolean
  videoTrainingItemId?: boolean
  captionId?: boolean
  phrase?: boolean
  note?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type VideoPhraseNoteOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "videoTrainingItemId" | "captionId" | "phrase" | "note" | "userId" | "createdAt" | "updatedAt", ExtArgs["result"]["videoPhraseNote"]>
export type VideoPhraseNoteInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  videoTrainingItem?: boolean | Prisma.VideoTrainingItemDefaultArgs<ExtArgs>
  caption?: boolean | Prisma.VideoPhraseNote$captionArgs<ExtArgs>
}
export type VideoPhraseNoteIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  videoTrainingItem?: boolean | Prisma.VideoTrainingItemDefaultArgs<ExtArgs>
  caption?: boolean | Prisma.VideoPhraseNote$captionArgs<ExtArgs>
}
export type VideoPhraseNoteIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  videoTrainingItem?: boolean | Prisma.VideoTrainingItemDefaultArgs<ExtArgs>
  caption?: boolean | Prisma.VideoPhraseNote$captionArgs<ExtArgs>
}

export type $VideoPhraseNotePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "VideoPhraseNote"
  objects: {
    videoTrainingItem: Prisma.$VideoTrainingItemPayload<ExtArgs>
    caption: Prisma.$VideoCaptionPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    videoTrainingItemId: string
    captionId: string | null
    phrase: string
    note: string
    userId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["videoPhraseNote"]>
  composites: {}
}

export type VideoPhraseNoteGetPayload<S extends boolean | null | undefined | VideoPhraseNoteDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$VideoPhraseNotePayload, S>

export type VideoPhraseNoteCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<VideoPhraseNoteFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: VideoPhraseNoteCountAggregateInputType | true
  }

export interface VideoPhraseNoteDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['VideoPhraseNote'], meta: { name: 'VideoPhraseNote' } }
  /**
   * Find zero or one VideoPhraseNote that matches the filter.
   * @param {VideoPhraseNoteFindUniqueArgs} args - Arguments to find a VideoPhraseNote
   * @example
   * // Get one VideoPhraseNote
   * const videoPhraseNote = await prisma.videoPhraseNote.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends VideoPhraseNoteFindUniqueArgs>(args: Prisma.SelectSubset<T, VideoPhraseNoteFindUniqueArgs<ExtArgs>>): Prisma.Prisma__VideoPhraseNoteClient<runtime.Types.Result.GetResult<Prisma.$VideoPhraseNotePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one VideoPhraseNote that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {VideoPhraseNoteFindUniqueOrThrowArgs} args - Arguments to find a VideoPhraseNote
   * @example
   * // Get one VideoPhraseNote
   * const videoPhraseNote = await prisma.videoPhraseNote.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends VideoPhraseNoteFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, VideoPhraseNoteFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__VideoPhraseNoteClient<runtime.Types.Result.GetResult<Prisma.$VideoPhraseNotePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VideoPhraseNote that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoPhraseNoteFindFirstArgs} args - Arguments to find a VideoPhraseNote
   * @example
   * // Get one VideoPhraseNote
   * const videoPhraseNote = await prisma.videoPhraseNote.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends VideoPhraseNoteFindFirstArgs>(args?: Prisma.SelectSubset<T, VideoPhraseNoteFindFirstArgs<ExtArgs>>): Prisma.Prisma__VideoPhraseNoteClient<runtime.Types.Result.GetResult<Prisma.$VideoPhraseNotePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VideoPhraseNote that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoPhraseNoteFindFirstOrThrowArgs} args - Arguments to find a VideoPhraseNote
   * @example
   * // Get one VideoPhraseNote
   * const videoPhraseNote = await prisma.videoPhraseNote.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends VideoPhraseNoteFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, VideoPhraseNoteFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__VideoPhraseNoteClient<runtime.Types.Result.GetResult<Prisma.$VideoPhraseNotePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more VideoPhraseNotes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoPhraseNoteFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all VideoPhraseNotes
   * const videoPhraseNotes = await prisma.videoPhraseNote.findMany()
   * 
   * // Get first 10 VideoPhraseNotes
   * const videoPhraseNotes = await prisma.videoPhraseNote.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const videoPhraseNoteWithIdOnly = await prisma.videoPhraseNote.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends VideoPhraseNoteFindManyArgs>(args?: Prisma.SelectSubset<T, VideoPhraseNoteFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VideoPhraseNotePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a VideoPhraseNote.
   * @param {VideoPhraseNoteCreateArgs} args - Arguments to create a VideoPhraseNote.
   * @example
   * // Create one VideoPhraseNote
   * const VideoPhraseNote = await prisma.videoPhraseNote.create({
   *   data: {
   *     // ... data to create a VideoPhraseNote
   *   }
   * })
   * 
   */
  create<T extends VideoPhraseNoteCreateArgs>(args: Prisma.SelectSubset<T, VideoPhraseNoteCreateArgs<ExtArgs>>): Prisma.Prisma__VideoPhraseNoteClient<runtime.Types.Result.GetResult<Prisma.$VideoPhraseNotePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many VideoPhraseNotes.
   * @param {VideoPhraseNoteCreateManyArgs} args - Arguments to create many VideoPhraseNotes.
   * @example
   * // Create many VideoPhraseNotes
   * const videoPhraseNote = await prisma.videoPhraseNote.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends VideoPhraseNoteCreateManyArgs>(args?: Prisma.SelectSubset<T, VideoPhraseNoteCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many VideoPhraseNotes and returns the data saved in the database.
   * @param {VideoPhraseNoteCreateManyAndReturnArgs} args - Arguments to create many VideoPhraseNotes.
   * @example
   * // Create many VideoPhraseNotes
   * const videoPhraseNote = await prisma.videoPhraseNote.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many VideoPhraseNotes and only return the `id`
   * const videoPhraseNoteWithIdOnly = await prisma.videoPhraseNote.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends VideoPhraseNoteCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, VideoPhraseNoteCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VideoPhraseNotePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a VideoPhraseNote.
   * @param {VideoPhraseNoteDeleteArgs} args - Arguments to delete one VideoPhraseNote.
   * @example
   * // Delete one VideoPhraseNote
   * const VideoPhraseNote = await prisma.videoPhraseNote.delete({
   *   where: {
   *     // ... filter to delete one VideoPhraseNote
   *   }
   * })
   * 
   */
  delete<T extends VideoPhraseNoteDeleteArgs>(args: Prisma.SelectSubset<T, VideoPhraseNoteDeleteArgs<ExtArgs>>): Prisma.Prisma__VideoPhraseNoteClient<runtime.Types.Result.GetResult<Prisma.$VideoPhraseNotePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one VideoPhraseNote.
   * @param {VideoPhraseNoteUpdateArgs} args - Arguments to update one VideoPhraseNote.
   * @example
   * // Update one VideoPhraseNote
   * const videoPhraseNote = await prisma.videoPhraseNote.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends VideoPhraseNoteUpdateArgs>(args: Prisma.SelectSubset<T, VideoPhraseNoteUpdateArgs<ExtArgs>>): Prisma.Prisma__VideoPhraseNoteClient<runtime.Types.Result.GetResult<Prisma.$VideoPhraseNotePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more VideoPhraseNotes.
   * @param {VideoPhraseNoteDeleteManyArgs} args - Arguments to filter VideoPhraseNotes to delete.
   * @example
   * // Delete a few VideoPhraseNotes
   * const { count } = await prisma.videoPhraseNote.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends VideoPhraseNoteDeleteManyArgs>(args?: Prisma.SelectSubset<T, VideoPhraseNoteDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VideoPhraseNotes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoPhraseNoteUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many VideoPhraseNotes
   * const videoPhraseNote = await prisma.videoPhraseNote.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends VideoPhraseNoteUpdateManyArgs>(args: Prisma.SelectSubset<T, VideoPhraseNoteUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VideoPhraseNotes and returns the data updated in the database.
   * @param {VideoPhraseNoteUpdateManyAndReturnArgs} args - Arguments to update many VideoPhraseNotes.
   * @example
   * // Update many VideoPhraseNotes
   * const videoPhraseNote = await prisma.videoPhraseNote.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more VideoPhraseNotes and only return the `id`
   * const videoPhraseNoteWithIdOnly = await prisma.videoPhraseNote.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends VideoPhraseNoteUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, VideoPhraseNoteUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VideoPhraseNotePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one VideoPhraseNote.
   * @param {VideoPhraseNoteUpsertArgs} args - Arguments to update or create a VideoPhraseNote.
   * @example
   * // Update or create a VideoPhraseNote
   * const videoPhraseNote = await prisma.videoPhraseNote.upsert({
   *   create: {
   *     // ... data to create a VideoPhraseNote
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the VideoPhraseNote we want to update
   *   }
   * })
   */
  upsert<T extends VideoPhraseNoteUpsertArgs>(args: Prisma.SelectSubset<T, VideoPhraseNoteUpsertArgs<ExtArgs>>): Prisma.Prisma__VideoPhraseNoteClient<runtime.Types.Result.GetResult<Prisma.$VideoPhraseNotePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of VideoPhraseNotes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoPhraseNoteCountArgs} args - Arguments to filter VideoPhraseNotes to count.
   * @example
   * // Count the number of VideoPhraseNotes
   * const count = await prisma.videoPhraseNote.count({
   *   where: {
   *     // ... the filter for the VideoPhraseNotes we want to count
   *   }
   * })
  **/
  count<T extends VideoPhraseNoteCountArgs>(
    args?: Prisma.Subset<T, VideoPhraseNoteCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], VideoPhraseNoteCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a VideoPhraseNote.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoPhraseNoteAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends VideoPhraseNoteAggregateArgs>(args: Prisma.Subset<T, VideoPhraseNoteAggregateArgs>): Prisma.PrismaPromise<GetVideoPhraseNoteAggregateType<T>>

  /**
   * Group by VideoPhraseNote.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoPhraseNoteGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends VideoPhraseNoteGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: VideoPhraseNoteGroupByArgs['orderBy'] }
      : { orderBy?: VideoPhraseNoteGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, VideoPhraseNoteGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetVideoPhraseNoteGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the VideoPhraseNote model
 */
readonly fields: VideoPhraseNoteFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for VideoPhraseNote.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__VideoPhraseNoteClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  videoTrainingItem<T extends Prisma.VideoTrainingItemDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.VideoTrainingItemDefaultArgs<ExtArgs>>): Prisma.Prisma__VideoTrainingItemClient<runtime.Types.Result.GetResult<Prisma.$VideoTrainingItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  caption<T extends Prisma.VideoPhraseNote$captionArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.VideoPhraseNote$captionArgs<ExtArgs>>): Prisma.Prisma__VideoCaptionClient<runtime.Types.Result.GetResult<Prisma.$VideoCaptionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the VideoPhraseNote model
 */
export interface VideoPhraseNoteFieldRefs {
  readonly id: Prisma.FieldRef<"VideoPhraseNote", 'String'>
  readonly videoTrainingItemId: Prisma.FieldRef<"VideoPhraseNote", 'String'>
  readonly captionId: Prisma.FieldRef<"VideoPhraseNote", 'String'>
  readonly phrase: Prisma.FieldRef<"VideoPhraseNote", 'String'>
  readonly note: Prisma.FieldRef<"VideoPhraseNote", 'String'>
  readonly userId: Prisma.FieldRef<"VideoPhraseNote", 'String'>
  readonly createdAt: Prisma.FieldRef<"VideoPhraseNote", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"VideoPhraseNote", 'DateTime'>
}
    

// Custom InputTypes
/**
 * VideoPhraseNote findUnique
 */
export type VideoPhraseNoteFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoPhraseNote
   */
  select?: Prisma.VideoPhraseNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoPhraseNote
   */
  omit?: Prisma.VideoPhraseNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoPhraseNoteInclude<ExtArgs> | null
  /**
   * Filter, which VideoPhraseNote to fetch.
   */
  where: Prisma.VideoPhraseNoteWhereUniqueInput
}

/**
 * VideoPhraseNote findUniqueOrThrow
 */
export type VideoPhraseNoteFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoPhraseNote
   */
  select?: Prisma.VideoPhraseNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoPhraseNote
   */
  omit?: Prisma.VideoPhraseNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoPhraseNoteInclude<ExtArgs> | null
  /**
   * Filter, which VideoPhraseNote to fetch.
   */
  where: Prisma.VideoPhraseNoteWhereUniqueInput
}

/**
 * VideoPhraseNote findFirst
 */
export type VideoPhraseNoteFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoPhraseNote
   */
  select?: Prisma.VideoPhraseNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoPhraseNote
   */
  omit?: Prisma.VideoPhraseNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoPhraseNoteInclude<ExtArgs> | null
  /**
   * Filter, which VideoPhraseNote to fetch.
   */
  where?: Prisma.VideoPhraseNoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VideoPhraseNotes to fetch.
   */
  orderBy?: Prisma.VideoPhraseNoteOrderByWithRelationInput | Prisma.VideoPhraseNoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VideoPhraseNotes.
   */
  cursor?: Prisma.VideoPhraseNoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VideoPhraseNotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VideoPhraseNotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VideoPhraseNotes.
   */
  distinct?: Prisma.VideoPhraseNoteScalarFieldEnum | Prisma.VideoPhraseNoteScalarFieldEnum[]
}

/**
 * VideoPhraseNote findFirstOrThrow
 */
export type VideoPhraseNoteFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoPhraseNote
   */
  select?: Prisma.VideoPhraseNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoPhraseNote
   */
  omit?: Prisma.VideoPhraseNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoPhraseNoteInclude<ExtArgs> | null
  /**
   * Filter, which VideoPhraseNote to fetch.
   */
  where?: Prisma.VideoPhraseNoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VideoPhraseNotes to fetch.
   */
  orderBy?: Prisma.VideoPhraseNoteOrderByWithRelationInput | Prisma.VideoPhraseNoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VideoPhraseNotes.
   */
  cursor?: Prisma.VideoPhraseNoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VideoPhraseNotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VideoPhraseNotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VideoPhraseNotes.
   */
  distinct?: Prisma.VideoPhraseNoteScalarFieldEnum | Prisma.VideoPhraseNoteScalarFieldEnum[]
}

/**
 * VideoPhraseNote findMany
 */
export type VideoPhraseNoteFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoPhraseNote
   */
  select?: Prisma.VideoPhraseNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoPhraseNote
   */
  omit?: Prisma.VideoPhraseNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoPhraseNoteInclude<ExtArgs> | null
  /**
   * Filter, which VideoPhraseNotes to fetch.
   */
  where?: Prisma.VideoPhraseNoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VideoPhraseNotes to fetch.
   */
  orderBy?: Prisma.VideoPhraseNoteOrderByWithRelationInput | Prisma.VideoPhraseNoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing VideoPhraseNotes.
   */
  cursor?: Prisma.VideoPhraseNoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VideoPhraseNotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VideoPhraseNotes.
   */
  skip?: number
  distinct?: Prisma.VideoPhraseNoteScalarFieldEnum | Prisma.VideoPhraseNoteScalarFieldEnum[]
}

/**
 * VideoPhraseNote create
 */
export type VideoPhraseNoteCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoPhraseNote
   */
  select?: Prisma.VideoPhraseNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoPhraseNote
   */
  omit?: Prisma.VideoPhraseNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoPhraseNoteInclude<ExtArgs> | null
  /**
   * The data needed to create a VideoPhraseNote.
   */
  data: Prisma.XOR<Prisma.VideoPhraseNoteCreateInput, Prisma.VideoPhraseNoteUncheckedCreateInput>
}

/**
 * VideoPhraseNote createMany
 */
export type VideoPhraseNoteCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many VideoPhraseNotes.
   */
  data: Prisma.VideoPhraseNoteCreateManyInput | Prisma.VideoPhraseNoteCreateManyInput[]
}

/**
 * VideoPhraseNote createManyAndReturn
 */
export type VideoPhraseNoteCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoPhraseNote
   */
  select?: Prisma.VideoPhraseNoteSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the VideoPhraseNote
   */
  omit?: Prisma.VideoPhraseNoteOmit<ExtArgs> | null
  /**
   * The data used to create many VideoPhraseNotes.
   */
  data: Prisma.VideoPhraseNoteCreateManyInput | Prisma.VideoPhraseNoteCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoPhraseNoteIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * VideoPhraseNote update
 */
export type VideoPhraseNoteUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoPhraseNote
   */
  select?: Prisma.VideoPhraseNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoPhraseNote
   */
  omit?: Prisma.VideoPhraseNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoPhraseNoteInclude<ExtArgs> | null
  /**
   * The data needed to update a VideoPhraseNote.
   */
  data: Prisma.XOR<Prisma.VideoPhraseNoteUpdateInput, Prisma.VideoPhraseNoteUncheckedUpdateInput>
  /**
   * Choose, which VideoPhraseNote to update.
   */
  where: Prisma.VideoPhraseNoteWhereUniqueInput
}

/**
 * VideoPhraseNote updateMany
 */
export type VideoPhraseNoteUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update VideoPhraseNotes.
   */
  data: Prisma.XOR<Prisma.VideoPhraseNoteUpdateManyMutationInput, Prisma.VideoPhraseNoteUncheckedUpdateManyInput>
  /**
   * Filter which VideoPhraseNotes to update
   */
  where?: Prisma.VideoPhraseNoteWhereInput
  /**
   * Limit how many VideoPhraseNotes to update.
   */
  limit?: number
}

/**
 * VideoPhraseNote updateManyAndReturn
 */
export type VideoPhraseNoteUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoPhraseNote
   */
  select?: Prisma.VideoPhraseNoteSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the VideoPhraseNote
   */
  omit?: Prisma.VideoPhraseNoteOmit<ExtArgs> | null
  /**
   * The data used to update VideoPhraseNotes.
   */
  data: Prisma.XOR<Prisma.VideoPhraseNoteUpdateManyMutationInput, Prisma.VideoPhraseNoteUncheckedUpdateManyInput>
  /**
   * Filter which VideoPhraseNotes to update
   */
  where?: Prisma.VideoPhraseNoteWhereInput
  /**
   * Limit how many VideoPhraseNotes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoPhraseNoteIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * VideoPhraseNote upsert
 */
export type VideoPhraseNoteUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoPhraseNote
   */
  select?: Prisma.VideoPhraseNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoPhraseNote
   */
  omit?: Prisma.VideoPhraseNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoPhraseNoteInclude<ExtArgs> | null
  /**
   * The filter to search for the VideoPhraseNote to update in case it exists.
   */
  where: Prisma.VideoPhraseNoteWhereUniqueInput
  /**
   * In case the VideoPhraseNote found by the `where` argument doesn't exist, create a new VideoPhraseNote with this data.
   */
  create: Prisma.XOR<Prisma.VideoPhraseNoteCreateInput, Prisma.VideoPhraseNoteUncheckedCreateInput>
  /**
   * In case the VideoPhraseNote was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.VideoPhraseNoteUpdateInput, Prisma.VideoPhraseNoteUncheckedUpdateInput>
}

/**
 * VideoPhraseNote delete
 */
export type VideoPhraseNoteDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoPhraseNote
   */
  select?: Prisma.VideoPhraseNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoPhraseNote
   */
  omit?: Prisma.VideoPhraseNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoPhraseNoteInclude<ExtArgs> | null
  /**
   * Filter which VideoPhraseNote to delete.
   */
  where: Prisma.VideoPhraseNoteWhereUniqueInput
}

/**
 * VideoPhraseNote deleteMany
 */
export type VideoPhraseNoteDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VideoPhraseNotes to delete
   */
  where?: Prisma.VideoPhraseNoteWhereInput
  /**
   * Limit how many VideoPhraseNotes to delete.
   */
  limit?: number
}

/**
 * VideoPhraseNote.caption
 */
export type VideoPhraseNote$captionArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoCaption
   */
  select?: Prisma.VideoCaptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoCaption
   */
  omit?: Prisma.VideoCaptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoCaptionInclude<ExtArgs> | null
  where?: Prisma.VideoCaptionWhereInput
}

/**
 * VideoPhraseNote without action
 */
export type VideoPhraseNoteDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VideoPhraseNote
   */
  select?: Prisma.VideoPhraseNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VideoPhraseNote
   */
  omit?: Prisma.VideoPhraseNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoPhraseNoteInclude<ExtArgs> | null
}
